[BE] Location 패키지 코드 리팩터링
woowacourse-teams/2023-map-befine pull request #182
Opened 2023-08-02 10:40 UTC by junpakPark

## 작업 대상

Location 패키지에 포함된 모든 코드

## 📄 작업 내용

 - 코드 컨벤션 통일
 - 불필요 메서드 및 상수 제거
 - 도메인 객체 테스트 케이스 추가
 - 전체 테스트 코드 리팩터링
 - RestDocs 컨트롤러 테스트 작성
 - 통합 테스트 작성

## 🙋🏻 주의 사항

## 스크린샷

## 📎 관련 이슈

#175 
 
closed #175 

## 레퍼런스

2023-08-07 01:57 UTC, kpeel5839 requested changes
준팍 리팩토링 너무 고생하셨습니다!

코드가 아아아아주우우우우 깔끔해진 것 같아요!

마지막으로 논의 해볼만한 사항 남깁니다.

현재 모든 Info 객체가 가지고 있는 값들을 디미터 법칙을 이용해 꺼내올 수 있지 않을까요?

```java
PinInfo pinInfo = pin.getInfo();
new PinDetailResponse(
    pinInfo.getName()...
);

->

new PinDetailResponse(
    pin.getName()...
);
```

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/domain/AuthMember.java
> +    }
현재로서 AuthMember 의 from 메서드는 테스트에서만 사용하고 있네요!

지워도 될 것 같은데 준팍 생각은 어떠세요?

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/BasicAuthorizationExtractor.java
> +        if (!hasText(requestHeader)) { // Request Header 가 null 인데 decode 를 먼저 진행하게 되어서 문제 발생 (Guest 의 경우)
코드리뷰를 진행하는 이에게 질문을 남기는 주석이 아니라면 지워도 될 것 같다는 생각이 들어요.

그리고 해당 부분을 메서드 추출을 통해서 의미를 명확하게 하면 어떨까요?

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/common/resolver/AuthArgumentResolver.java
> +                .orElseGet(() -> new AuthInfo(""));
`""` 가 무엇을 의미하는지 상수화를 통해서 명확히 드러내도 좋겠네요

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/Domain/PinRepository.java
> +package com.mapbefine.mapbefine.pin.Domain;
패키지명이 대문자로 시작하네용

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +    }
개행 추가해줘도 될 것 같아요

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/dto/response/PinDetailResponse.java
> +                .map(Image::getImageUrl)
디미터의 법칙을 적용 해볼 수 있을 것 같아요

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicInfo.java
> +    }
이 부분까지도 Image 가 검증하게끔 해주면 더 깔끔해질 것 같아요

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/location/LocationIntegrationTest.java
> +    }
제가 하긴 했지만, 그냥 "Basic" + member.getEmail() 이게 더 깔끔할 것 같긴하네요.

준팍 생각은 어떠신가요?

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/CoordinateTest.java
> +        );
테스트를 아주 야물딱지게 짜셨군요 멋집니다 👍

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/LocationTest.java
> +    }
편의 메서드 테스트 짱짱맨입니다.

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
> +    // TODO : Custom Annotation 인 @ServiceTest 를 붙여서 동작시키면, 중복된 Location 을 전혀 찾아오지 못하는 문제가 발생 (터지는 테스트는 @DisplayName("핀을 저장하려는 위치(Location)가 존재하면 해당 위치에 핀을 저장한다." 이 테스트))
이 부분은 다 같이 문제를 찾아보고 싶네용

2023-08-07 01:57 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
> +        pinRepository.deleteAllByTopicId(topic.getId());
pinRepository 의 deleteAllByTopicId 는 지워도 될 것 같아요 (준팍이 리팩토링 할 부분은 아니지만)

2023-08-07 11:16 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/Domain/PinRepository.java
> +package com.mapbefine.mapbefine.pin.Domain;
반영했습니다

2023-08-07 11:16 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +    }
반영했습니다

2023-08-07 11:24 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicInfo.java
> +    }
이 부분은 TopicInfo의 책임이 맞지 않을까요?
해당 로직은 토픽이 생성될 때, 유저가 입력한 이미지가 없으면 Default Image를  사용한다는 의미입니다.

멤버의 프로필 사진이나 핀 이미지의 default Image가 정말 토픽의 default image와 동일하거나, 혹은 default image가 필요할까요?

2023-08-07 11:34 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/dto/response/PinDetailResponse.java
> +                .map(Image::getImageUrl)
지금 매튜가 제 코드 상에서 디미터의 법칙 위반이 아니냐고 지적했던 부분은
다 DTO로 변환 과정에 발생하는 일입니다.

> 디미터의 법칙은 결합도와 관련된 것이며, 객체의 내부 구조가 외부로 노출되는지에 대한 것이다. 
> Stream API 같은 경우에는 동일한 Stream으로 변환하여 반환 할 뿐, 캡슐화는 그대로 유지되므로 문제가 없다. 
> 만약 여러 .(도트)가 사용되더라도 객체의 내부 구현이 노출되지 않는다면 그것은 디미터의 법칙을 준수하는 코드이다.
> 또한 DTO 나 컬렉션 객체와 같은 자료 구조의 경우에는 물을 수 밖에 없다. 
> 만약 묻는 대상이 객체가 아닌 자료구조라면 당연히 내부를 노출해야 하므로 디미터의 법칙을 적용할 필요가 없다.

[[OOP] 디미터의 법칙(Law of Demeter)](https://mangkyu.tistory.com/147)

즉, 디미터의 법칙을 적용할 필요가 없는 사례를 제외하곤 다 정상적으로 적용이 되어있는데
굳이 리팩터링할 필요가 있을까요?

2023-08-07 11:38 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/dto/response/PinDetailResponse.java
> +                .map(Image::getImageUrl)
지금 매튜가 제 코드 상에서 디미터의 법칙 위반이 아니냐고 지적했던 부분은
다 DTO로 변환 과정에 발생하는 일입니다.

> 디미터의 법칙은 결합도와 관련된 것이며, 객체의 내부 구조가 외부로 노출되는지에 대한 것이다.
> Stream API 같은 경우에는 동일한 Stream으로 변환하여 반환 할 뿐, 캡슐화는 그대로 유지되므로 문제가 없다.
> 만약 여러 .(도트)가 사용되더라도 객체의 내부 구현이 노출되지 않는다면 그것은 디미터의 법칙을 준수하는 코드이다.
> 또한 DTO 나 컬렉션 객체와 같은 자료 구조의 경우에는 물을 수 밖에 없다.
> 만약 묻는 대상이 객체가 아닌 자료구조라면 당연히 내부를 노출해야 하므로 디미터의 법칙을 적용할 필요가 없다.

[[OOP] 디미터의 법칙(Law of Demeter)](https://mangkyu.tistory.com/147)

즉, 디미터의 법칙을 적용할 필요가 없는 사례를 제외하곤 다 정상적으로 적용이 되어있는데
굳이 리팩터링할 필요가 있을까요?

혹은 TopicInfo나 PinInfo의 래퍼클래스인 Topic과 Pin에
`getName()`과 같은 전달 메서드를 사용하는 건
객체들끼리 메서드를 주고 받는다기 보다는 데이터를 직접적으로 주고받는 것에 더 가깝지 않을까요?

2023-08-07 12:31 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/common/resolver/AuthArgumentResolver.java
> +                .orElseGet(() -> new AuthInfo(""));
반영했습니다

2023-08-07 12:31 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/BasicAuthorizationExtractor.java
> +        if (!hasText(requestHeader)) { // Request Header 가 null 인데 decode 를 먼저 진행하게 되어서 문제 발생 (Guest 의 경우)
반영했습니다

2023-08-07 12:31 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/domain/AuthMember.java
> +    }
반영했습니다

2023-08-07 12:34 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/location/LocationIntegrationTest.java
> +    }
반영했습니다

2023-08-08 04:27 UTC, yoondgu requested changes
```
P1: 꼭 반영해주세요 (Request changes)
P2: 적극적으로 고려해주세요 (Request changes)
P3: 웬만하면 반영해 주세요 (Comment)
P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
P5: 그냥 사소한 의견입니다 (Approve)
```

깔끔하게 잘 해주셔서 사소한 부분 위주로 코멘트 남겨보았습니다!! 수고 많으셨습니다 😀

2023-08-08 04:27 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/location/LocationIntegrationTest.java
> +                ("Basic" + member.getEmail()).getBytes()
P3. authHeader를 만들 때 Email을 대신하는 아무 String값을 쓰지 않고, MemberFixture를 사용하는 이유가 있을까요?  
검증된 이메일 형식으로만 authHeader값을 만들어 테스트하기 위함이라면 좋은 방법 같지만,  
지금은 Member에 이메일 형식 검증이 없기도 하고요!

2023-08-08 04:27 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/location/LocationIntegrationTest.java
> +    private static final String BASIC_FORMAT = "Basic %s";
P2. 사용하지 않는 상수 삭제 부탁드립니다!

2023-08-08 04:27 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/AddressTest.java
> +            //then
P2. 공백 추가 부탁드립니다~!

2023-08-08 04:27 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/AddressTest.java
> +    class IsSameAddress {
P3. 메서드에 따라 Nested 계층을 만들어주셨네요!  
메서드 별 테스트가 여러 개 있을 때 가독성이 올라가서 좋은 것 같아요.  

TODO의 우선 순위가 높진 않지만, 팀원들 간 합의가 이루어진다면  
아래와 같은 방법 중 하나를 정해서 도메인 별 테스트에서 모두 통일해보면 어떨까 싶네요  
방법1. 메서드 별 테스트가 2개 이상이면, Nested로 작성하기  
방법2. 무조건 메서드 별로 Nested로 작성하기

2023-08-08 04:27 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/LocationRepositoryTest.java
> +    void findAllByCoordinateAndDistanceInMeters(double distance, int size) {
P2. hoxy.. 저희 테스트 메서드명 컨벤션을 맞추는 건 어떨까요? ㅎㅎ
_Success 가 붙는 것이 불필요하다고 생각해서 빼셨으려나요

2023-08-08 04:48 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/location/presentation/LocationController.java
> +@RequestMapping("/location")
반영했습니다

2023-08-08 04:48 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/location/LocationIntegrationTest.java
> +    private static final String BASIC_FORMAT = "Basic %s";
반영했습니다

2023-08-08 04:54 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/location/application/LocationQueryService.java
> +    private static final double NEAR_DISTANCE = 3000.0;
반영했습니다

2023-08-08 04:54 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/location/LocationFixture.java
> +    public static final Coordinate UNDER_METER = Coordinate.of(37.6273644, 127.0447427);
반영했습니다

2023-08-08 04:54 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/AddressTest.java
> +            //then
반영했습니다

2023-08-08 04:54 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/LocationRepositoryTest.java
> +    void findAllByCoordinateAndDistanceInMeters(double distance, int size) {
반영했습니다

2023-08-08 04:57 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/location/LocationIntegrationTest.java
> +                ("Basic" + member.getEmail()).getBytes()
반영했습니다

2023-08-08 04:58 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/AddressTest.java
> +    class IsSameAddress {
저는 방법 1 생각하고 작성했습니다.
다른 분들은 어떠신지 궁금하네요~

2023-08-08 06:08 UTC, cpot5620 reviewed
준팍 고생 많으셨습니다 👍 

Location 패키지 위주로 리뷰 남겨놓았는데, 확인 부탁드려요 ~

2023-08-08 06:08 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicInfo.java
> +    }
근데 validation 하겠다는 메서드 명인데 왜 반환 값이 있는거죠 ?

물론 제가 수정했습니다 ㅎㅎ ~

2023-08-08 06:08 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/AddressTest.java
> +    class IsSameAddress {
저는 더 지저분한 것 같아요..
사실 사용을 안 해 버릇해서 그런걸수도 있습니다....

2023-08-08 06:09 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/AddressTest.java
> +    class IsSameAddress {
저는 더 지저분한 것 같아요..
사실 사용을 안 해 버릇해서 그런걸수도 있습니다....

2023-08-08 06:14 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/common/annotation/ServiceTest.java
> +@DataJpaTest(
@DataJpaTest에는 @Transactional 어노테이션이 존재한답니다 ㅎㅎ

2023-08-08 06:23 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/location/application/LocationQueryService.java
> +        Map<Topic, Long> topicCounts = countTopicsInLocations(nearLocation);
`pinCountsByTopic` 로 수정하였습니다

2023-08-08 06:24 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/location/application/LocationQueryService.java
> +    private Map<Topic, Long> countTopicsInLocations(List<Location> locations) {
`countPinsByTopicInLocations(List<Location> locations)`로 수정하였습니다

2023-08-08 06:26 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/location/domain/AddressTest.java
> +    class IsSameAddress {
사실 저도 자주 사용하지 않아서 조금 낯설기는 해요.
근데 요 클래스를 봤을 때는 장점을 느껴서, 천천히 어떻게 할지 정해보죠!

2023-08-08 06:37 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/location/application/LocationQueryService.java
> +                NEAR_DISTANCE_METERS);
반영했습니다

2023-08-08 06:37 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/location/application/LocationQueryService.java
> +    private static final double NEAR_DISTANCE_METERS = 3000.0;
반영했습니다

2023-08-08 06:37 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/location/domain/Location.java
> +    }
반영했습니다

2023-08-08 06:37 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/location/presentation/LocationController.java
> +    }
반영했습니다.

2023-08-08 06:37 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/common/annotation/ServiceTest.java
> +@DataJpaTest(
@kpeel5839 이거 제가 수정할까요?

2023-08-08 06:40 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Role.java
> +    private final String title;
key는 스프링 시큐리티에서 사용하는 권한코드이고, 
title은 view(프론트)단에서 사용할 명칭입니다

아직 스프링 시큐리티를 사용하진 않지만 추후 확장을 고려하여 미리 만들었습니다

2023-08-08 07:25 UTC, yoondgu approved these changes
변경 요청 드렸던 부분들 반영 확인했습니다!

2023-08-08 07:47 UTC, cpot5620 approved these changes
리뷰 반영 해주셔서 감사합니두~

2023-08-08 08:02 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/common/annotation/ServiceTest.java
> +@DataJpaTest(
호걱스호걱스 모르고 넣었네용

2023-08-08 08:03 UTC, kpeel5839 approved these changes
준팍 고생하셨더연!

2023-08-08 08:06 UTC, merged