[BE] Member 관련 기능 개발
woowacourse-teams/2023-map-befine pull request #237
Opened 2023-08-07 12:13 UTC by kpeel5839

## 작업 대상

Member 관련 기능

## 📄 작업 내용

- 유저 권한 부여
- 유저 권한 삭제
- 토픽에 권한을 가진 유저 목록 조회
- 토픽에 권한을 가진 유저 단일 조회
- 유저 생성
- 유저 목록 조회
- 유저 단일 조회
- 유저가 만든 핀 조회
- 유저가 만든 토픽 조회

## 🙋🏻 주의 사항

고민해볼만한 부분을 주석으로 남긴 것이 있습니다.

## 스크린샷

## 📎 관련 이슈

 
#161 #173 

## 레퍼런스

2023-08-08 06:13 UTC, junpakPark requested changes
매튜 고생하셨습니다~
몇가지 의견 남겨봤는데 확인 부탁드려요!

2023-08-08 06:13 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Role.java
> +    }
해당 메서드는 어떤 의도로 넣으셨는지 여쭤봐도 될까요?

[[Java] @JsonCreater : Enum Type Request DTO Mapping](https://velog.io/@rmswjdtn/Spring-Enum-Type-Request-DTO-Mapping)

위 블로그 참조하시면 아시겠지만, Enum의 `name()`이 아닌 Enum의 `values()`를 enum으로 매핑할 때
해당 어노테이션과 메서드를 사용하더라구요.

저희의 경우는 name으로 바로 매핑하니 해당 메서드는 불필요할 것 같습니다.

2023-08-08 06:13 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberDetailResponseTest.java
> +class MemberDetailResponseTest {
혹시 어떤 사유에서 DTO를 테스트 하셨는지 여쭤봐도 될까요?

2023-08-08 06:41 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Role.java
> +    }
네네 현재로서는 불필요하지만, 추후 key 혹은 title 로 입력을 받게 되었을 때, filter 부분만 수정하면 정상적으로 돌아갈 수 있도록 하기 위해서 남겨놨어요.

2023-08-08 06:44 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +    }
해당 메서드의 경우, 본인이 만든 토픽, 핀이니 따로 권한에 따라서 필터링 할 필요는 없지 않을까요?

2023-08-08 06:44 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +    }
nickname 을 생각하긴 했습니다.

네이밍을 바꿔야할까요? 혹은 그냥 name 으로 가야할까요?

2023-08-08 06:46 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberDetailResponseTest.java
> +class MemberDetailResponseTest {
정적 팩토리 메서드를 사용하기 때문에 테스트했습니당.

2023-08-08 06:53 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +    }
추후에 해당 유저가 만든 토픽이나 핀을 확인하는 기능을 추가할 때 해당 메서드 재활용 가능하지 않을까요?

2023-08-08 06:53 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +    }
닉네임으로 생각하셨다면 네이밍을 바꾸는 게 좋을 것 같습니당!

2023-08-08 06:57 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +    }
추후에 해당 유저가 만든 토픽이나 핀을 확인하는 기능을 추가할 때 
해당 메서드 재활용 가능하지 않을까요?

멤버 ID를 파라미터로 받고, 필터링을 넣어주면 조금 더 다양하게 활용 가능할 것 같습니다

2023-08-08 08:39 UTC, cpot5620 requested changes
나름 큰 도메인이었을텐데, 고생 많으셨습니다 👍👍👍
코멘트가 조금 많은데 ㅎㅎ 천천히 읽어주세요 !

2023-08-08 08:39 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +        validateRole(role);
validate 메서드들의 위치가 변경되어야 할 것 같아요 !

2023-08-08 08:39 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Role.java
> +                .equalsIgnoreCase(input);
IgnoreCase로 하신 이유가 있을까요 ?

2023-08-08 08:39 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberInfoTest.java
> +        void success() {
테스트 명 컨벤션 !!

2023-08-08 08:39 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberCommandServiceTest.java
> +                .isEqualTo(member);
해당 테스트가 실패하네용

```java
java.lang.AssertionError: 
Expecting:
  com.mapbefine.mapbefine.member.domain.Member@76351c98
to be equal to:
  com.mapbefine.mapbefine.member.domain.Member@6f664ab3
when recursively comparing field by field, but found the following 2 differences:

field/property 'createdAt' differ:
- actual value   : 2023-08-08T17:34:35.215712 (java.time.LocalDateTime)
- expected value : null

field/property 'updatedAt' differ:
- actual value   : 2023-08-08T17:34:35.215712 (java.time.LocalDateTime)
- expected value : null
```

2023-08-08 08:39 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberCommandServiceTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
현재 예외 클래스가 정해지지 않은 상태에서 표준 예외를 사용하고 있는데요.
권한이 도입되면서, 발생할 수 있는 예외가 여러 개라고 생각해요 ㅎㅎ

현재로썬, 테스트 의도에 맞게 발생한 예외가 맞는지 확인할 수 있는 방법은 `예외 메세지 확인`이 유일할 것 같은데요.
전체적으로 메세지도 검증해보는 것은 어떨까요 ?

2023-08-08 09:53 UTC, yoondgu requested changes
```
P1: 꼭 반영해주세요 (Request changes)
P2: 적극적으로 고려해주세요 (Request changes)
P3: 웬만하면 반영해 주세요 (Comment)
P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
P5: 그냥 사소한 의견입니다 (Approve)
```

매튜 새 기능 구현 하느라 넘 수고 많으셨습니다!!
같이 맞춰보면 좋을 만한 부분 위주로 코멘트 남겼습니다 ~!

2023-08-08 10:43 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberDetailResponseTest.java
> +class MemberDetailResponseTest {
별도의 검증로직이나 Enum등 반환값을 예측하기 힘든 정적 팩터리 메서드가 아니기때문에 불필요하다는 느낌이 듭니다.
다른 분들은 어떠세요?

2023-08-08 10:45 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Role.java
> +    }
지금 당장 필요한 메서드가 아니라면 나중에 추가하는 건 어떨까요?
해당 메서드가 어떤 사유에서 존재하는 지 헷갈릴 위험이 있을 것 같습니다.

2023-08-08 11:09 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
> +    }
이거 좋은데요?
이렇게 가면 Info 시리즈들을 진짜 VO 처럼 쓸 수 있겠군용

2023-08-08 12:16 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +                .getId();
저 부분 할 때 강박이 도져서..

2023-08-08 12:20 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +        }
저는 부정이 좋은데!

2023-08-08 12:20 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +        }
농담이고 반영하도록 하겠슴돠~

2023-08-08 12:23 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +        validateRole(role);
서로의 순서가 바뀌어야 한다는 것일까요?

아니면 imageUrl 검증이 Role 검증보다 뒤에 있어서 그런 것일까요?

2023-08-08 12:31 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Role.java
> +                .equalsIgnoreCase(input);
철자는 동일하지만 소문자, 대문자 차이로 제대로 매핑해주지 못하는 경우를 방지해주기 위해서 였어용

2023-08-08 12:33 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberCommandServiceTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
음 저 같은 경우는 hasMessage 를 잘 사용하지 않는 편인데요.

이유는 에러메세지를 상수화해서 관리하지 않는다면, 예외 메세지가 수정될 때에도 테스트 코드를 수정해야한다는 것이 너무 번거로워서였어연

하지만

> 현재로썬, 테스트 의도에 맞게 발생한 예외가 맞는지 확인할 수 있는 방법은 예외 메세지 확인이 유일할 것 같은데요.
전체적으로 메세지도 검증해보는 것은 어떨까요 ?

이게 너무 맞는말이긴하네용 ㅎㅎ

2023-08-08 12:34 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
> +        MemberInfo memberInfo = MemberInfo.of(name, email, imageUrl, role);
오우 2번이 너무 끌려버리는데요 ㅋㅋㅋㅋ

좋습니다

2023-08-08 12:35 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
> +    }
굳입니다 역시 도이 똒똒똒똒이!

2023-08-08 12:36 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberInfoTest.java
> +        void whenNameIsInvalid_thenFail(String invalidName) {
넵!

2023-08-08 12:45 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +        if (!authMember.canTopicUpdate(topic)) {
validateMemberCanTopicUpdate 의 네이밍을 말씀하시는걸까요? 아니면 canTopicUpdate 가 아닌 isCreator 라는 메서드를 써야하지 않냐는 말씀이신가용?

2023-08-08 12:49 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/Domain/PinRepository.java
> +    List<Pin> findByCreator(Member creator);
처음에는 id 를 사용했다가, 일관성 유지하려고 매개변수로 객체를 넘겼었는데 지금보니 다른 메서드들이 모두 id 를 넘기고 있군요 아차차차!

2023-08-08 12:50 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +        List<Topic> topicsByCreator = topicRepository.findByCreator(member);
https://github.com/woowacourse-teams/2023-map-befine/pull/237#discussion_r1287071203

쥬니한테 답변했습니다!

2023-08-08 12:50 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberTopicPermissionRepository.java
> +    boolean existsByTopicAndMember(Topic topic, Member member);
넹~!

2023-08-08 12:51 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberTopicPermissionRepository.java
> +    List<MemberTopicPermission> findByTopic(Topic topic);
됴아연

2023-08-08 12:51 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +    }
이 부분은 도이가 구두로 말씀해주셔서 수정했습니당!

2023-08-08 13:09 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +        validateNull(authMember.getMemberId());
이 부분은 findByCreator 를 위해 member 를 찾아주는 과정에서 id 가 null 이게 되면 InvalidDataAccessApiUsageException 이 터져서 사전처리였어용.

하지만, findByCreator 에 Id 값을 넘기면 이 구문은 없어도 되겠네요!

2023-08-08 13:16 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +        validateNull(authMember.getMemberId());
이전에는 findByCreator 를 위해서 memberRepository.findById() 하는 과정에서 id 가 null 이게 되면 예외가 터져서 위와 같이 처리해줬는데

findByCreator 에는 null 을 넣더라도 예외가 발생하지 않아서 위 검증은 필요 없을 것 같네용

2023-08-08 13:44 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/dto/response/MemberDetailResponse.java
> +        LocalDateTime updateAt
아니 도이 제꺼 모니터링 하고 계십니까..

대단합니다 감사해요!!

2023-08-09 00:40 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +    }
반영했슴둥

2023-08-09 01:10 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +        validateNull(authMember.getMemberId());
위의 제 코멘트는 번복하도록 하겠습니다. 일단 해당 메서드가 필요할 것 같긴하네요

2023-08-09 04:41 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +        validateRole(role);
이 부분은 제가 잘못 생각했던 것 같아요 ㅎㅎ 죄송합니다 ~!

2023-08-09 04:42 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Role.java
> +                .equalsIgnoreCase(input);
명세에 맞지 않게 온 요청에 대해서도 처리해주겠다는 의미일까요 ?

이는 잘못된 요청으로 보아도 되지 않을까요 ?

2023-08-09 04:43 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberCommandServiceTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
추가 의견을 덧붙이자면, 예외 메세지가 수정되었을 때 (= 프로덕트 코드가 변경되었을 때) 테스트에 영향을 미치는 것은 당연한 수순인 것 같아요.

2023-08-09 04:46 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +        if (!authMember.canTopicUpdate(topic)) {
Creator만 토픽에 대한 수정 권한이 있기 때문에, 위와 같은 코멘트를 남겨두었는데요.

다시 생각해보니 지금 메서드도 괜찮을 것 같아요 !
추후에, 수정 권한이 생성자뿐만 아니라 다른 유저에게도 추가될 수 있으니까요 ㅎㅎ

2023-08-09 04:52 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +                MemberTopicPermission.createPermissionAssociatedWithTopicAndMember(topic, member);
>Member 와 Topic 중 어떤 것을 이용하여 저장할까?? (물론 Member 쪽에 쏠리긴하지만 찝찝해버령)

Member 소유로 가지고 있는 Topic이기 때문에 Member를 이용하면 될 것 같아요.

>이걸 생명주기라고 해야할까요? Member 와 Topic 은 이미 생성되어 있고, 수정된 정보가 MemberTopicPermission 이외에는 없었습니다.

멤버에게 토픽 권한이 추가되었다는 것은 멤버의 정보가 업데이트 된 것이겠죠 ? 
그렇다면, 멤버의 업데이트된 정보가 저장 되면서 MemberTopicPermission가 저장되는 것이 흐름이나, 객체적인 측면에서 자연스러워 보여요.

2023-08-09 05:20 UTC, cpot5620 approved these changes
리뷰 반영 잘 해주셨습니다 👍👍👍

다만, MemberTopicPermission은 추후에 다시 고민해보는 걸로 하죠 !!
잊지 말아주세요 >_ㅇ

2023-08-09 05:21 UTC, yoondgu approved these changes
수고 많으셨습니다 !! 👍👍👍

2023-08-09 05:24 UTC, junpakPark approved these changes
고생하셨습니다!

2023-08-09 05:24 UTC, merged