[BE] 핀(Pin) 패키지 코드 리팩터링(PinImage 기능 구현 포함)
woowacourse-teams/2023-map-befine pull request #240
Opened 2023-08-07 16:47 UTC by yoondgu

## 작업 대상

Pin 패키지에 존재하는 코드

## 📄 작업 내용

#151 의 task 참고 부탁드립니다.

## 🙋🏻 주의 사항

### 1
충돌을 줄이기 위해 사전에 준팍, 매튜의 브랜치를 pull받아 작업하였습니다.
현재 코드 변경량이 꽤 많은데, 두 분의 브랜치가 머지 된 후에 리뷰하시면 더 편할 것 같습니다.
커밋 범위는 다음과 같습니다! 

### 2
함께 이야기하고 싶은 내용을 TODO 주석으로 작성하였습니다.

### 3
다른 코드에 영향이 갈 변경 사항 중 하나는,
Pin의 PinInfo, PinImage의 Image와 같은 포장 객체들을 생성 시 직접 받는 방식으로 수정했습니다.
이유는 커밋 바디에 작성하였습니다.

### 4
서비스 테스트 리팩터링은
given, when 부분의 코드를 줄여보면 좋을 것 같은데 연관 관계 매핑 로직에 따라서 코드 변경이 많을 것 같아 
지금은 많이 진행하지 못했습니다.

## 스크린샷

## 📎 관련 이슈

 
closed #151

## 레퍼런스

2023-08-08 00:46 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            // TODO pin.addImage()가 특히 자연스러운 로직인거 같은데 setter 안쓰는 일관성 유지를 위해 일단 이렇게 했습니다.. 계속 이렇게 할지 논의 필요해보여요
.

2023-08-08 00:48 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +    // TODO 예외처리 패턴 추상화
authMember.canXXX true이면 로직 실행 / 아니면 예외 발생 의 패턴이 메서드마다 같아서, 추상화해서 중복을 줄이면 좋을 것 같아요
하지만 아직 통일된 형식이 아니라 같이 얘기해보면 좋겠습니다!

2023-08-08 11:59 UTC, junpakPark requested changes
아직 수정중이실 것 같아서 간단하게만 남겼습니다!
확인 부탁드려요~!!

2023-08-08 11:59 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
> +    public ResponseEntity<Void> addImage(AuthMember member, @PathVariable Long pinImageId) {
네이밍이 위의 메서드와 겹치는 것 같습니다!
`removeImage()`로 수정 부탁드려요~ㅎㅎ

2023-08-08 12:06 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
> +    public ResponseEntity<Void> addImage(AuthMember member, @PathVariable Long pinImageId) {
앗 이런 실수가 있었네요!! 반영하겠습니다

2023-08-08 12:12 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            // TODO pin.addImage()가 특히 자연스러운 로직인거 같은데 setter 안쓰는 일관성 유지를 위해 일단 이렇게 했습니다.. 계속 이렇게 할지 논의 필요해보여요
지금도 URI는 `pins/images`인데, PinImageController로 별도로 분리하자는 말씀이실까요?!  
테이블 구조로는 Pin과 PinImage가 나눠져있지만,
도메인을 개념적으로 생각했을 때 Pin에 대한 기능 중 PinImage가 속해있기 때문에 PinController, Service에서 관리하는 것이 자연스럽다고 생각했어요!  
분리하자고 해주신 이유가 궁금합니다~

2023-08-08 12:13 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +    private static final double DUPLICATE_LOCATION_DISTANCE = 10.0;
반영했습니다

2023-08-08 12:13 UTC, kpeel5839 requested changes
도이 고생하셨습니다!!

코멘트 조금 남겼습니다~! 확인 부탁 드려욘

2023-08-08 12:13 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            pinImageRepository.deleteAllByPinId(pinId);
p4; 저희가 그 때 pinImage 를 hard-delete 하기로 결정하긴 했지만, 실제 구현된 것을 보고 다시 생각해보니 의아해서 코멘트 남겨요!

pinRepository 를 왜 soft-delete 하는지에 대해서 다시 생각해봐야하지 않을까란 생각도 드네요.

저희가 유저들이 지운 데이터들까지도 알뜰살뜰하게 활용하기 위해서?

아니면 지운 것들을 유저가 원한다면 다시 롤백 할 수 있게 하기 위해서일까요?

만일 후자라면 pinImage 도 soft-delete 해야하지 않을까란 의견을 남기고 떠납니다.. 총총총

2023-08-08 12:13 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinInfo.java
>          if (name == null) {
p3; 쥬니짱이 Objects.isNull(...) 이 있다네용 ㅎ

2023-08-08 12:13 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
> +    // TODO PinCommandServiceTest에서 테스트할 내용이 맞을까요? 토픽테스트에서 하는 건 어떨까요?
사실상 PinCommandService 는 save 할 때에만 사용되네요.

동의합니다!

2023-08-08 12:13 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinRepositoryTest.java
> +    // TODO 토픽 삭제 시에도 핀 이미지 삭제 처리되어야 할 것 같아요
동의합니다!

2023-08-08 12:13 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
> +                        .header(LOCATION, 1L)
뭐죠! 이건 Response Header 에 Location 을 추가하는건가요??!

2023-08-08 12:13 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
> +                        headerWithName(AUTHORIZATION).optional().description("Optional")
이것도 뭐죠! 왜 혼자만 좋은 거 알고 계시죠!

2023-08-08 13:03 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +    // TODO 예외처리 패턴 추상화
Topic 서비스 코드에서처럼, 서비스 별 validate 메서드를 사용하도록 수정해보겠습니다!

2023-08-08 13:24 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
> +    }
만일 Location 헤더 값을 반환한다면, 해당 URI에 조회가 가능해야 한다는 것에 동의합니다!  
리팩터링 중에 아이크에게 필요 여부를 물어보니, 구현 방식에 따라 다를 수 있다고 해서  
일단은 넣어주었는데요.. ㅎㅎ  
넣어주었으면 조회 API도 같이 있는 게 맞지만, 당장 필요한 게 아니라 구현하지 않았습니다.  
사용하지 않는 기능을 미리 넣는 것은 좋지 않다고 생각해서  
반대로 Location 반환을 일단 삭제하고 추후 조회 기능 필요 시 구현하는 것으로 하면 어떨까요?

2023-08-08 13:34 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            pinImageRepository.deleteAllByPinId(pinId);
전자(데이터 활용)의 관점에서 생각했을 때, Pin은 우리 서비스에서 만든 핵심 데이터이지만 이미지는 좀 더 사용자의 직접적인 데이터라는 점에서 hard-delete를 생각했어요.  
하지만 우리 서비스의 특성 중 하나가 여러 사람이 데이터를 변경할 수 있는 것이라는 점에서,  
삭제-복구의 유연함이 중요하다는 걸 생각하면 PinImage도 soft-delete 하는 게 더 좋아보이네요.  

다른 분들의 의견도 동일하시다면
당장 이미지 저장공간을 우려할 필요는 없어보이니 soft-delete로 변경하겠습니다!

2023-08-08 13:37 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            pinImageRepository.deleteAllByPinId(pinId);
저도 두 분 의견에 동의합니당ㅋㅋ

2023-08-08 13:38 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
> +    }
역시 똒똒똒똒 도이입니다~!

2023-08-08 13:39 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            pinImageRepository.deleteAllByPinId(pinId);
국문학과이시네요..

2023-08-08 13:43 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
> +    // TODO PinCommandServiceTest에서 테스트할 내용이 맞을까요? 토픽테스트에서 하는 건 어떨까요?
이 메서드는 지우도록 하겠습니다!
@cpot5620  TopicCommandServiceTest에서 delete 테스트로 검증해주시면 감사하겠습니당

2023-08-08 13:47 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
> +                        headerWithName(AUTHORIZATION).optional().description("Optional")
해당 헤더가 필수가 아닌 경우에는 문서에 표시해줘야 할 것 같아서 넣었는데  
또 별도의 설정을 해줘야지 저 description을 볼 수 있나봐요 ㅠㅠ  
일단 코드로라도 명시해두었습니다

2023-08-08 13:53 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinRepositoryTest.java
> +    // TODO 토픽 삭제 시에도 핀 이미지 삭제 처리되어야 할 것 같아요
삭제할게욘 ~

2023-08-08 14:59 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
> +    }
반영 완료

2023-08-08 14:59 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            pinImageRepository.deleteAllByPinId(pinId);
반영 완료

2023-08-08 15:05 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            pinImageRepository.deleteAllByPinId(pinId);
아직 쥬니는 확인하지 못했지만, 코드 내용도 비교해볼 수 있도록 soft delete으로 변경한 내역 푸쉬하였습니다!

2023-08-08 15:06 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            pinImageRepository.deleteAllByPinId(pinId);
반영완료

2023-08-08 15:06 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinInfo.java
>          if (name == null) {
반영완료

2023-08-08 15:08 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinRepositoryTest.java
> +    // TODO 토픽 삭제 시에도 핀 이미지 삭제 처리되어야 할 것 같아요
다시 보니까, JPQL로 작성한 메서드인 `deleteAllByTopicId`를 테스트하기 위함이라 필요없지는 않네용 .. ㅎㅎ 리팩터링만 진행하겠습니다

2023-08-08 15:18 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
> +                        .header(LOCATION, 1L)
반영완료

2023-08-08 15:45 UTC, cpot5620 reviewed
우선, 리뷰가 늦어져서 죄송합니다 ㅠ_ㅠ

코드에서 고민을 많이 하신게 느껴졌어요. 고생 많으셨습니다 도이 👍👍👍

코멘트 남겨두었으니, 확인 부탁드려요 !

2023-08-08 15:45 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinInfo.java
> +            throw new IllegalArgumentException("핀 이름은 필수입니다.");
캬 ~!~!~! Ojbects.isNull 아주 좋아영

2023-08-08 15:45 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
>          return pin;
저는 개인적으로 return 이전에 개행을 넣어주는게 가독성 측면에서 더 좋다고 생각합니다 !

도이는 어떠신가요 ?

2023-08-08 15:45 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
> +        }
매개 변수명이 copy인 것은 의도하신 것일까요 ?

2023-08-08 15:45 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinInfo.java
> -    }
불변 객체로 만드셨군요 👍

2023-08-08 15:45 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +    public long save(AuthMember authMember, PinCreateRequest request) {
primitive 값으로 반환해주시는 이유가 있을까요 ?

2023-08-08 15:45 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            pinImageRepository.deleteAllByPinId(pinId);
엇.. 이곳에 있었군요.

이미 코멘트 달아놓았는데, 그대로 복붙 하면 다음과 같습니다.

---

S3를 사용하게 된다면, 해당 코드가 수정될까요 ?

만약, soft-deleting 하는 방식을 유지한다면 PinImageTable에 불필요한 정보들이 남을 것 같아서요.
아마 제 의견은
핀은 soft-deleting하여 추후에 데이터 통계 등으로 재사용할 수 있지만, 이미지는 그럴 가능성이 없을 것 같다.
였던 것 같아요 !

저번에 같이 이야기 했던 것 같은데, 결론이 안 났었나요 ?
그렇다면 내일 이야기 더 해보는 걸로 !

2023-08-08 15:45 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
>  class PinCommandServiceTest {
'**해당 토픽에 대한 핀 생성시 권한이 없는 경우**'에 대한 테스트가 없는 것 같아요 !!

2023-08-08 16:09 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
>          return pin;
앗 공감합니다!! 놓친 부분이라 바로 반영하겠습니다!

2023-08-08 16:10 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
> +        }
메서드 분리 단축키의 폐해로군요 .. 변수명 pin으로 수정하겠습니다 ~!

2023-08-08 16:13 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinQueryServiceTest.java
> +                pin);
수정했습니다!

2023-08-08 16:13 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
>  class PinCommandServiceTest {
테스트 추가하겠습니다 !!

2023-08-08 16:35 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +    public long save(AuthMember authMember, PinCreateRequest request) {
앗 제가 잘못 생각한 것 같아요 ㅎㅎㅎ
id값으로는 null을 반환할 일 없는(반환하면 안되는) 메서드이기 때문에
null일 수도 있는 Wrapper보다 primitive가 이 메서드를 더 믿고 사용할 수 있게 해준다고 생각합니다!

2023-08-08 16:43 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +        throw new IllegalArgumentException("해당 토픽의 핀을 수정할 권한이 없습니다.");
아 제가 주석에 내용을 넘 함축해서 썼네요 !!
컬렉션에 값을 넣어주는 것은 충분히 가능하다고 생각하고요  
주석에 쓴 말의 의미는 
지금처럼 .createXXX 메서드 내부에서 연관 관계 매핑을 위해 컬렉션에 값을 넣어주는 것(.addXXX)보다,  
.addXXX 메서드를 호출할 때 그 내부에서 연관 관계 매핑을 해주는 게  (일반적인 양방향 편의메서드)
연관 관계를 이해하기에 더 자연스러운 것 같은데,
그러려면 내부에서 연관 관계 매핑을 위해 setter를 써야 한다는 게 다시 고민이라는 뜻이었습니다!!

지금 방식
```java
    public static PinImage createPinImageAssociatedWithPin(Image image, Pin pin) {
        PinImage pinImage = new PinImage(image, pin);
        pin.addPinImage(pinImage);

        return pinImage;
    }
```

일반적인 방식
```java
public void addPinImage(PinImage pinImage) {
        pin.addPinImage(pinImage);
        PinImage.setPin(this);
}
```

2023-08-09 00:48 UTC, junpakPark approved these changes
새로 남긴 코멘트들은 다 P4입니다 ㅎㅎ
고생하셨어요 도이!

2023-08-09 00:48 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +        return topicRepository.findById(topicId)
이 로직은 중복되는 것 같은데
`validateExistId(Long id)` 이런 메서드로 분리하고
메시지를 "유효하지 않은 Id"입니다"로 변경해주는 건 어떨까요?

2023-08-09 00:48 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
> +            // TODO pin.addImage()가 특히 자연스러운 로직인거 같은데 setter 안쓰는 일관성 유지를 위해 일단 이렇게 했습니다.. 계속 이렇게 할지 논의 필요해보여요
Pin에 이미 많은 로직이 포함되어 있고, 앞으로도 포함될 가능성이 높기 때문에
우선적으로 분리 가능한 PinImage를 분리하는 건 어떨까 하는 생각에 말씀드렸습니당 ㅎㅎ

PinImageService를 별도로 나눈다면 이벤트로 처리하는 것도 가능할 것 같구요 ㅎㅎ
도메인적으로는 속해있다는 말씀은 공감됩니다!
분리하더라도 같은 패키지 내에서 계속 관리해주면 좋을 것 같네요 ㅎㅎ

2023-08-09 01:09 UTC, yoondgu commented
### 정해야 할것
- [ ] PinImage soft delete vs hard delete  
- [ ] Pin copy 로직 정하기
- [ ] 연관관계 편의 메서드 검토

2023-08-09 06:10 UTC, cpot5620 approved these changes
고생하셨습니다.

이제 바톤을 제게 넘기시죠..

저는 이만... 충돌 해결하러...

2023-08-09 06:12 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinInfo.java
> +            throw new IllegalArgumentException("핀 이름은 필수입니다.");
오타났어요 Objects 입니다

2023-08-09 06:13 UTC, kpeel5839 approved these changes
역시 도이 야무집니다!

고생하셨어요~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2023-08-09 06:14 UTC, merged