[BE] feature/#250 지도 같이보기 기능 구현
woowacourse-teams/2023-map-befine pull request #257
Opened 2023-08-10 08:23 UTC by junpakPark

## 작업 대상

- [x] atlas 패키지
  - [x] AtlasController
  - [x] AtlasQueryService
  - [x] AtlasCommandService
  - [x] Atlas
  - [x] AtlasRepository
## 📄 작업 내용

- [x] 유저의 모아볼 Topic 목록 조회
- [x] 유저의 모아볼 Topic 등록
- [x] 유저의 모아볼 Topic 삭제
- [x] Location 테스트 일부 리팩터링

## 🙋🏻 주의 사항

## 스크린샷

## 📎 관련 이슈

#250 
 
closed #250 
## 레퍼런스

2023-08-10 14:49 UTC, cpot5620 reviewed
고생 많으셨습니다 준팍 !
크게 리뷰 드릴 것이 없네요 ㅎㅎ 

천천히 읽고 답변 남겨주세요.

2023-08-10 14:49 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/atlas/domain/Atlas.java
> +        return new Atlas(topic, member);
return 절 이전에 개행해주는 건 어떤가용 ?

2023-08-10 14:49 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandService.java
> +        }
LoginRequired로 막아두는 것도 좋지만, 2차적으로 null 검증을 해주는 것은 어떠신가요 ?

2023-08-10 14:49 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasQueryService.java
> +    }
```java
 .filter(member::canRead)
```
해당 구문이 있는 이유는 사용자가 추후에 토픽의 접근 권한을 수정할 수도 있기 때문 인가요 ?

2023-08-10 14:49 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/atlas/presentation/AtlasController.java
> +    }
Location Header에 id값을 넣지 않은 것은 의도하신 것일까요 ?

2023-08-10 15:13 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasQueryService.java
> +    }
yayay~

2023-08-10 15:15 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/atlas/presentation/AtlasController.java
> +    }
yayay~ 세인과 함께 사용 흐름을 생각해봤을 때, 
모아보기에 들어가있는 토픽을 따로 확인하는 경우는 없다고 판단해서
Location header에서 id 값을 제외했습니다

2023-08-11 00:59 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandService.java
> +        }
반영했습니다

2023-08-11 03:18 UTC, yoondgu requested changes
```
P1: 꼭 반영해주세요 (Request changes)
P2: 적극적으로 고려해주세요 (Request changes)
P3: 웬만하면 반영해 주세요 (Comment)
P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
P5: 그냥 사소한 의견입니다 (Approve)
```

빠르고 깔끔하게 구현해주셨군요!! 수고 많으셨습니당
사소한 부분들만 몇 가지 코멘트 남겼습니다. P2만 반영해주셔도 바로 approve 하도록 하겠습니다!

2023-08-11 05:50 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/atlas/application/AtlasQueryServiceTest.java
> +        topics.forEach(topic -> atlasRepository.save(Atlas.from(topic, member)));
제가 사용한 forEach는 Stream의 forEach가 아니라
collection의 forEach(향상된 for문)이라 item46.에는 해당 사항 없는 걸로 알고 있습니다!

[Collection.forEach와 Stream.forEach는 뭐가 다를까?](https://tecoble.techcourse.co.kr/post/2020-09-30-collection-stream-for-each/)
[Stream의 foreach 와 for-loop 는 다르다.](https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/)
> Stream.forEach() 대신 **향상된 for문**을 사용해도 충분히 가독성 좋은 코드가 될 수 있다.

혹시 제가 잘못이해한것일까요?

2023-08-11 05:51 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandServiceTest.java
> +    @DisplayName("")
반영했습니다

2023-08-11 05:51 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/atlas/AtlasIntegrationTest.java
> +    @DisplayName("모아보기에 추가되어있는 지도 목록을 조회한다")
반영했습니다

2023-08-11 05:51 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandServiceTest.java
> +    @DisplayName("")
반영했습니다

2023-08-11 05:52 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/atlas/AtlasIntegrationTest.java
> +        );
반영했습니다

2023-08-11 07:09 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/atlas/application/AtlasQueryServiceTest.java
> +        topics.forEach(topic -> atlasRepository.save(Atlas.from(topic, member)));
앗 제가 Collection의 stream의 차이를 혼동했네요!! 알려주셔서 감사합니당

2023-08-11 07:09 UTC, yoondgu approved these changes
수고많으셨습니다 !!

2023-08-11 15:15 UTC, kpeel5839 approved these changes
전체적으로 코드가 깔끔하고 이미 다른 분들이 많이 리뷰를 해주셔서 말씀 드릴 것이 크게 없네요.

다만, 논의해봐야 할 정책들이 조금 있는 것 같아요.

결국 같이보기 개수의 제한을 둘 것 같은데 (현재 한번에 표현할 수 있는 핀의 색깔이 7개), 이 경우 사용자가 특정 개수 이상의 토픽을 같이보기에 담게 되면 가장 먼저 추가되었던 토픽이 같이보기에서 삭제된다던가 등의 동작들이 추가될 것 같기도 하네요.

그리고 저희가 지금껏 적용안하기는 했지만 isDeleted 가 true 인 경우 해당 토픽을 가져오지 않는 로직등도 필요할 것 같기도 하네요.

계속 같이 논의해봐용!

너무 고생하셨습니다 준팍! 👍

2023-08-11 15:15 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandService.java
> +    }
순서가 호출 순서대로 변경되어야겠네요!

findTopicById

validateReadPermission

findMemberById

이렇게용 ㅎㅎ

2023-08-12 09:19 UTC, cpot5620 approved these changes

2023-08-13 06:11 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandService.java
> +    }
반영했습니다

2023-08-14 04:53 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +    }
P4. 메서드 분리를 하는 것은 좋지만, convertToResponse 대신 topicsInAtlas.contains(topic) 을 분리하는 게 어떨까요?
TopicResponse.from 메서드 자체가 convert하는 로직인 것 같아서요!

2023-08-14 04:53 UTC, kpeel5839 approved these changes
고생하셨습니다~!

2023-08-14 04:53 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandService.java
> +    }
알러뷰

2023-08-14 05:21 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +    }
반영했습니다

2023-08-14 15:21 UTC, cpot5620 approved these changes
준팍 전반적인 코드 리팩토링 수행하시느라 고생 많으셨습니다 ~!
확실히 코드가 깔끔해졌어요 ㅋㅋ
제 코드를 다시 확인해보니, 성능 신경쓰다가 정작 중요한 부분을 많이 놓쳤네요 😥

코멘트 몇 가지(?) 남겨두었는데, 확인 부탁드려요.

늘 말씀드리지만, 꼭 적용 안 하셔도 되고 반대 의견이 있다면 코멘트만 별도로 남겨주세요 !!

프론트에서 모아보기 기능 구현중에 있는 걸로 알고 있어서, Approve부터 하겠습니다 ~!

---

추가로, 코멘트를 위에서부터 하나하나 적용 및 답변하지 마시고, 전체적으로 한 번 읽고나서 적용해주세요.

중복되는 내용의 코멘트도 있고, 앞 쪽의 코멘트에서는 ~~를 적용해달라고 했지만, 뒷 쪽에서는  동일한 내용임에도 불구하고, 의견을 나누어봐야 할 사항이 있는 경우가 있어서요 !

2023-08-14 15:21 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
> +    }
Service 계층에서 네이밍을 정할 때, find와 get이 함께 쓰이고 있는데요.

혹시, 어떤 기준에서 나뉘는 건가요 ? 

```
단순히 Repository 메서드 호출 및 검증 -> find
데이터 가공 -> get
```
이 맞을까요 ?

2023-08-14 15:21 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
> +
개행이 한 줄 더 추가되어있네요 !

2023-08-14 15:21 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
> +    public List<TopicResponse> findAllTopicsByMemberId(AuthMember authMember, Long memberId) {
메서드 명을 자주보다보니, 익숙해져 있었는데 해당 메서드 명이 조금 어색한 것 같기도 합니다. (너무 Repository스러운 이름 같아요)

`사용자가 만든 모든 토픽을 조회한다`라는 이름의 적절한 메서드명이 없을까요 ?
ex) findAllCreatingTopicsOfMember / findAllTopicsCreatedByMember 등

2023-08-14 15:21 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
> +            @Param("memberId") Long memberId);
리팩토링 과정에서, 더이상 사용되지 않는 메서드들이 다수 존재하는데요.

이는 과감하게 쳐내도 될 것 같습니다 !

나중에 필요하게 되면, 커밋 로그를 찾아서 체리픽 혹은, 복붙하면 되니까요.

2023-08-14 15:21 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicWithBookmarkStatus.java
> +public class TopicWithBookmarkStatus {
> 리팩토링 과정에서, 더이상 사용되지 않는 메서드들이 다수 존재하는데요.<br>
이는 과감하게 쳐내도 될 것 같습니다 !<br>
나중에 필요하게 되면, 커밋 로그를 찾아서 체리픽 혹은, 복붙하면 되니까요.

해당 클래스도 마찬가지입니당

2023-08-14 15:21 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicDetailResponse.java
>  ) {
문득 든 생각인데요, 생각보다 조금 큰 작업일 수도 있지만 `updatedAt`은 맨 마지막에 위치하는게 좋을 것 같아요.

중요도가 조금 떨어지는(?) 데이터니까요 !?

꼭 적용하실 필요는 없고, 매튜, 도이 의견 듣고 의견 조율해봅시다 !

2023-08-14 15:21 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandServiceTest.java
> +@ServiceTest
아... 이 어노테이션 이야기 나눠보기로 했는데 까먹었네요 허허

2023-08-14 15:21 UTC, cpot5620 commented on frontend/src/pages/AskLoginPage.tsx
>  export default function AskLoginPage() {
아으 프론트시치;;

2023-08-15 01:51 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicDetailResponse.java
>  ) {
저도 동감합니다 !!

2023-08-15 08:17 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
> +
저도 "내 핀 목록 보기" 기능이라면 PathVariable이 없어도 되지 않을까? 싶네요!
또 그렇게 된다면
`pins/members` 보다 기존 API 구조인 `members/pins`가 자연스러운 것 같기도 하네요 ㅜㅜ

2023-08-15 08:33 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
내 핀 목록을 조회하는 것이라면 사실상 authMember와 memberId가 동일한 상황이기 때문에
authmember.canRead를 검증하는 것은 불필요하지 않을까요?
그 대신, 51번 줄 전에 `authMember.isMember(memberId)` 와 같이 memberId의 동일 여부만 확인해주는 게 어떨까요?

2023-08-15 08:45 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> -        List<TopicResponse> responses = memberQueryService.findTopicsByMember(authMember);
저도 준팍이랑 대화할 때에는 사용자의 토픽/핀 조회를 TopicController, PinController가 가져가는 게 자연스럽겠다 생각했는데,
URI의 구성을 보면 기존의 `members/topics`, `members/pins` 가 의미적으로 자연스럽지 않나 생각이 드네요 🥲

`members/atlas`, `members/bookmarks`가 추가되다보니
특정 사용자에 대한 자원을 조회하는 다른 API들도 같은 형식일거라고 생각되는데 그렇지 않아서 헷갈리는 것 같아요!
사용자의 모아보기, 즐겨찾기를 찾듯이 사용자가 만든 지도, 핀을 찾을 때에도 현재 배포된 버전처럼  `members/topics`, `members/pins`로 가져가는 게 일관성도 더 있지 않나 싶습니다

2023-08-15 09:01 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> -        List<TopicResponse> responses = memberQueryService.findTopicsByMember(authMember);
다른 내부적인 구조 리팩터링은 배포 이후에 천천히 생각하더라도
이 부분은 변경할 때마다 프론트에서 쓰는 API 명세 변경이 클 것 같아서, 확실하게 정하고 넘어가면 좋겠습니다!!

2023-08-15 09:30 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
> +
추후에 특정 사용자가 만든 핀의 목록을 볼 수 있는 기능에 사용할 수도 있지만, 개인적인 생각으로는 본인이 만든 핀의 목록을 조회하는 API 와 분리 되었으면 좋겠네요!

2023-08-15 09:31 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicDetailResponse.java
>  ) {
젇후영~

2023-08-15 09:41 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
> +    public static TopicResponse from(Topic topic, Boolean isInAtlas, Boolean isBookmarked) {
P4. 이전에 Topic 관련 코드리뷰에서도 달았던 내용인데, 크리티컬한 이슈는 아니라 P4로 달아둡니다.
boolean 타입으로 null이 들어올 수 있는 Wrapper 타입을 사용하는 게 맞을까용?

2023-08-15 09:43 UTC, yoondgu reviewed
실수로 코멘트를 개별로 달아버렸네요.. ㅎㅎ ㅜㅜ!!
수요일까지 기능 완료하는 것을 1순위로 보았을 때, 당장 짚고 넘어갔으면 하는 부분만 P2로 남겼습니다!

2023-08-15 09:58 UTC, kpeel5839 approved these changes

2023-08-15 09:58 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> -        List<TopicResponse> responses = memberQueryService.findTopicsByMember(authMember);
설득이 되는군요!

저도 `member/~` 이런 식으로 가는 것이 자연스러운 것 같습니다~!

2023-08-15 09:58 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
그리고 오히려 authMember.canRead() 로 검증하게되면 올바르지 않은 반환값을 얻을 수 있을 것 같네요.

pathvariable 로 받은 memberId 와 authMember 의 id 는 다를 수 있으니까요

2023-08-15 12:30 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +
해당 TODO는 `findAll()`메서드에 대해서 생각했던 TODO입니다.
해당 API를 사용하는 장소가 admin 페이지라고 판단했기 때문입니다.

다시 생각해보니 지금 단계에서는 `findAll()`이 
특정 토픽에서 유저에게 권한을 줄 때
사용할 수도 있다는 생각이 들어 해당 TODO를 제거했습니다

2023-08-15 12:33 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +        List<TopicResponse> responses = memberQueryService.findAllTopicsInBookmark(authMember);
> members/atlas, members/bookmarks가 추가되다보니
> 로그인한 사용자에 대한 자원을 조회하는 다른 API들도 같은 형식일거라고 생각되는데 그렇지 않아서 헷갈리는 것 같아요!
> 사용자의 모아보기, 즐겨찾기를 찾듯이 사용자가 만든 지도, 핀을 찾을 때에도 현재 배포된 버전처럼 members/topics, members/pins로 가져가는 게 일관성도 더 있지 않나 싶습니다

이 부분은 도이의 의견과 상충되는 것 같은데 교통정리가 필요할 것 같습니다 @yoondgu

2023-08-15 12:43 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
해당 메서드에 대해서는 내 핀 목록 조회라기 보다는
특정 멤버의 핀 목록 조회용으로 만들어준 메서드라서 현재와 같이 구현되었습니다.

@kpeel5839 
pathvariable 로 받은 memberId 와 authMember 의 id가 다른 것을 전제로 만든 API가 맞습니다.
그리고 다를 경우에는, 현재 접속한 유저의 권한을 기준으로 Pin 목록을 보여주는 것이
우리의 도메인 규칙이기 때문에 현재와 같이 구현하였습니다.

그리고 authMember와 MemberId가 동일한 경우에는
내 핀 목록을 조회하기라는 목적을 정확하게 수행합니다.

일단 저는  다음 두 가지 고민 때문에 이와 같이 구현을 하였습니다.
1. 내 핀 목록 조회와 멤버 핀 목록 조회의 API가 분리되는 것이 정말 프론트엔드가 일하기 쉬워지는 것이 맞을까?
2. API가 분리되는 것이 편하다고 할 때, 서비스도 이를 처리하는 로직이 별도로 유지되어야만 하는 이유는 무엇일까?

이 부분에 대해서 @yoondgu 와  @kpeel5839 에게 왜 별도로 유지 되어야한다고 생각하시는 지 여쭤봐도 될까요?

2023-08-15 12:45 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
> +
> 혹시, 추후에 특정 사용자가 만든 핀의 목록을 볼 수 있는 기능이 추가되는 것을 생각하여 위와 같이 설계하신걸까요 ?
> 아니면, 관리자 계정을 위한 기능인가요 ?

@cpot5620 의 질문 중 첫번째 이유 때문에 현재와 같이 구현하였습니다.
저는 내 핀 목록 조회와 멤버 핀 목록 조회의 분리에 대해서
아래 링크에 남긴 이유 때문에 현재와 같은 선택을 했는데요.

[멤버 핀 목록조회로 구현한 이유](https://github.com/woowacourse-teams/2023-map-befine/pull/257/files/1ef8041fe4897005967c76b13a9f021198c945e8..0c2d500a18cc122c996ece2d28fc24363f9e0d3f#r1294543191)

이 부분에 대해서 합의가 된다면 따르도록 하겠습니다.

2023-08-15 12:47 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
> +    }
해당 부분은 IDE 도움을 받아 메서드 분리하다보니 현재와 같이 구성되었습니다.
find로 통일하는 게 좋을 것 같은데 어떠세요?

2023-08-15 12:55 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +
멤버 관련 조회 API들의 사용처가 좀 더 명확해져야
이와 관련된 조회 권한을 고려해볼 수 있을 것 같습니다.

2023-08-15 12:57 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
> +    public static TopicResponse from(Topic topic, Boolean isInAtlas, Boolean isBookmarked) {
이 부분에 대해서 @cpot5620 와 @yoondgu 가 합의 되시면 따르겠습니다

2023-08-15 13:14 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
맞네요 준팍 저 부분은 현재 조회한 사람의 입장에서 생각해야 한다는 사실을 잊고 있었어요.

지금까지 분리가 되어야 한다고 생각한 이유는 준팍이 말씀하신 1번과 연관이 되어있는데요. 

저는 반대로 분리하는 것이 프론트가 편할 수도 있다고 생각했기 때문이에요.

그렇기 때문에 이 부분은 한번 프론트엔드 크루분들에게 여쭤보아야 할 것 같네요.

1번이 정해진다면 2번도 자연스레 정해지겠네요

2023-08-15 13:15 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
1. 지금 스프린트에서 구현중인 기능, 프론트엔드에서 바로 필요로 하는 기능 중 특정 회원의 정보를 조회하는 것이 있나요?!  

저는 yagni원칙과 같이, "추후 필요할 수도 있는 사항"에 대해 고려하는 것은 지양해야 한다고 생각합니다. 그래서 해당 API 구현에서는 지금 당장의 요구사항인 "내 정보 조회"에 집중했으면 하는 의도로 말씀 드렸습니다.  


2. 그럼에도 확장성 있는 설계를 고려하는 것은, 저도 좋다고 생각해요. 그런데 왜 분리해서 생각하려고 하는지 이유를 말씀드려볼게요.  

API 또한 "하나의 함수는 하나의 일만 한다"고 생각해보면, 추상화를 하는 것과 여러 일을 동시에 맡는 것은 다르다고 생각됩니다..!!
왜냐하면 "내 정보 조회"와 "특정 회원 조회"는 사실 생각보다 많이 다른 기능이라고 생각해요.
내 정보 조회에서는 보다 민감한 정보를 보여줄 수도 있지만, 내가 아닌 다른 회원의 프로필을 조회할 때는 그러면 안되겠죠.  
따라서 결국 두 기능은 추상화해도 다른 기능이기에, 한 API에서 관리할 경우 오히려 앞서 말씀드린 차이로 인한 문제의 여지가 있어보여요.  
그래서 API를 분리하는 것이 좋다고 생각이 듭니다! 

어디까지나 제 주관적인 생각이기에 다르게 생각하시는 점 편하게 말해주세요!!

2023-08-15 13:21 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
> +    public static TopicResponse from(Topic topic, Boolean isInAtlas, Boolean isBookmarked) {
저는 수정 요청은 아니구 궁금해서 같이 얘기해보고 싶은 거라 ㅋㅋㅋ 지금도 괜찮습니다!

2023-08-15 13:23 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
아 지금 API는 특정 회원의 핀 목록 조회이지만, 회원 정보 조회에서도 같은 형식으로 접근하게 될 것 같아 회원 정보로 예시를 든 점 양해 부탁드립니다 !!

2023-08-15 13:33 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicDetailResponse.java
>  ) {
> Topic에 대한 정보는 해당 배열 위에 존재해야
응집성이 있다고 생각했는데

이 부분은 공감이 되네요 !

데이터의 응집성 vs 중요도(?)의 관점에 따라 달라질 것 같아요.

크게 중요한 부분은 아니기때문에, 정말 나~중에 고쳐도 되는 부분인 것 같아서, 지금은 현 코드 유지하는걸 제안드립니다.

2023-08-15 13:38 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
@kpeel5839 세인한테 물어봤는데 둘 다 큰 상관 없다고 하네요 ㅋㅋ

@yoondgu 회원정보는 확실히 도이의 말씀대로 별개의 API로 관리하는 것이 좋을 것 같네요!

유저의 private한 pin과 public한 pin에 대한 접근 권한을 기준으로
필터링한 상태라 본인만 보고 싶은 Pin, 남들이 봐도 되는 Pin이
이미 구분되어 있는 상태라고 생각했는데
혹시 제가 아직 고려하지 못한 사항이 있다면 가르쳐주실 수 있을까요?

2023-08-15 13:44 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
도이가 예시를 들어주신, 회원 정보 조회의 경우에는 별도의 API로 구성되어야 하는 것이 맞다고 생각합니다.

하지만, 핀 목록 조회에서는 위와 같은 상황이 있을까 ? 라는 의문이 들긴 하네요.
(내부 로직적으로 canRead()를 수행하지 않아도 된다는 점 ㅋㅋ..?)

그럼에도 불구하고 통일성(?)을 위해, 분리하는 것에 한 표 던지겠습니당

> 내 핀 목록 조회와 멤버 핀 목록 조회의 API가 분리되는 것이 정말 프론트엔드가 일하기 쉬워지는 것이 맞을까?

프론트엔드보다는 백엔드 개발자가 우선적으로 고려되어야 한다고 생각합니다.
코드를 구성하는 방식? 이라고 해야할지는 모르겠지만, 통일성이 있어야 백엔드 개발자가 일하기 쉬워질 것 같아요.
회원 정보 API는 별도로 관리하고, 핀 정보 API는 통합해서 관리하면, 통일성이 떨어질 것 같아서요 !

2023-08-15 13:46 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +        List<TopicResponse> responses = memberQueryService.findAllTopicsInBookmark(authMember);
URI의 자연스러움 vs 기능에 따른 패키지 분리 일까요 ?

저는 두 의견 모두 공감이 되서, 다른 분들 의견에 따라 가도록 하겠습니당

2023-08-15 13:49 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
앗 지우고 달았는데 그새 다 읽으셨었군요 ㅎㅎㅎㅎ 죄송합니다^^..

2023-08-15 13:50 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
쥬니 말씀대로 회원정보 API와 함께 통일성을 가져가는 것도 좋을 것 같긴 하네요..

2023-08-15 13:51 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
정리하자면, Controller 분리 / Service 통합이 맞을까요?

2023-08-15 13:52 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
넵넵

2023-08-15 13:55 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
> +    public static TopicResponse from(Topic topic, Boolean isInAtlas, Boolean isBookmarked) {
> boolean 타입으로 null이 들어올 수 있는 Wrapper 타입을 사용하는 게 맞을까용?

저는 Wrapper 타입을 사용하여야 한다고 생각해요.

만약, 로직 오류가 있어서 null 값이 반환되고 있지만, primitive는 null일 경우 false로 인식하게 되기 때문에 문제 원인을 파악하기 어려울 것이라고 생각해요.
해당 값이 null인지, false인지에 따라 어느 부분에서 문제가 발생했는지 파악하기 쉽지 않을까요 ?

2023-08-15 14:02 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
> +    }
앗 근데 생각해보니 

PinController에서는 `pins/members/{memberId}`로 특정 유저의 Id로 핀 조회 하고,
MemberController 에서 `members/pins`으로 나의 핀 조회를 하는 건 어떨까요?

혹은 myPage용 QueryController를 별도로 둬서 
로그인 유저 기준 조회성 API(모아보기, 즐겨찾기, 나의 핀, 나의 지도)들은 한 곳에 모아두고,
memberController는 말 그대로 Member 도메인 관련 CRUD만 수행하게 하는 방법도 있을 것 같습니다.

2023-08-16 00:06 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
> +    public static TopicResponse from(Topic topic, Boolean isInAtlas, Boolean isBookmarked) {
저는 @cpot5620 의견에 동의가 되네용 ㅋㅋ

2023-08-16 00:29 UTC, junpakPark commented on backend/src/docs/asciidoc/bookmark.adoc
> +operation::bookmark-controller-test/delete-all-topics-in-bookmark[snippets='http-request,http-response']
반영했습니다

2023-08-16 00:29 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
> +            @Param("memberId") Long memberId);
반영했습니다

2023-08-16 00:29 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicWithBookmarkStatus.java
> +public class TopicWithBookmarkStatus {
반영했습니다

2023-08-16 01:56 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
> +    public static TopicResponse from(Topic topic, Boolean isInAtlas, Boolean isBookmarked) {
현 상황 유지로 합의

2023-08-16 02:06 UTC, merged