[BE] feature/#251 최신 지도 조회 API 구현
woowacourse-teams/2023-map-befine pull request #258
Opened 2023-08-10 12:35 UTC by junpakPark

## 작업 대상

- [x] TopicController
- [x] TopicQueryService
- [x] PinRepository 

## 📄 작업 내용

- [x] 가장 최근에 핀이 추가되거나 업데이트된 순으로 지도된 지도 목록을 반환한다

## 🙋🏻 주의 사항

[이번 PR Commit 범위](https://github.com/woowacourse-teams/2023-map-befine/pull/258/files/53ec9b4f1eea969470dd32e5a73a458bd98784d2..fd6561155d04da94495d44d86e3b8dff0c97b03a)
## 스크린샷

## 📎 관련 이슈

#251 
 
closed #251 
## 레퍼런스

2023-08-10 15:02 UTC, cpot5620 reviewed
엄청 빠르게 구현해주셨네요 👍 👍 

한 가지 궁금한 점이 있어서 코멘트 남겨두었는데 확인 부탁드려요 !

2023-08-10 15:02 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
>  }
질문이 있습니다 !

Topic에 대해서 distinct를 통해 중복을 제거하려고 하신 것 같은데, 해당 동작이 올바르게 수행 되나요 ?
Topic에 별다른 equals&hascode가 정의되어있지 않아서 여쭤봅니다 !
뭔가 될 것 같기도 한데... 잘 몰라서 ㅎㅎ..

만약, 올바르게 동작하지 않는다면
Repository에서 topicId에 대해 중복되지 않은 것들을 갖고오도록 하는 방법도 있을 것 같아요 !

2023-08-10 15:17 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
>  }
Topic에 별다른 equals&Hashcode가 정의 되어있지 않더라도
같은 객체로 처리해주더라구요! 
JPA 학습이 짧아서 왜 그런지 설명은 못하겠지만...
테스트 코드를 통해서 해당 동작이 정상적으로 수행되는 건 확인 완료했습니다 ㅎㅎ

2023-08-11 04:06 UTC, yoondgu requested changes
마찬가지로 빠르게 잘 구현해주셨네요!!
RestDocs 문서화 + P2 코멘트 하나만 반영해주시면 바로 approve하겠습니당

2023-08-11 04:06 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
> +    @DisplayName("")
P2. DisplayName 적어주세요 !!

2023-08-11 05:59 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
> +    }
개행 반영했습니다

2023-08-11 05:59 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
> +    @DisplayName("")
추가했습니다!

2023-08-11 07:10 UTC, yoondgu approved these changes

2023-08-12 09:06 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
>  }
준팍 말씀대로, 영속성 컨텍스트에서 수행해주는 것이 맞는 것 같네요 ~

한 가지 걱정이되는 부분은,  서비스 특징상(핀 복사 등) findAll로 데이터를 가져올 경우 너무 많은 데이터를 가져오지 않을까 ? 싶습니다.
단순히 limit을 걸어두자니, 특정 토픽에 있는 핀들만 최근에 업데이트 되어 있을 경우 원하는 결과를 못가져올 것 같긴 해서.. 

Topic에도 updatedAt이라는 컬럼이 있다보니 위의 문제를 개선할 수 있지 않을까요 ?

처음 리뷰 당시에 이 부분을 인지하지 못했었네요 ㅠㅠ 죄송합니다 !

2023-08-12 10:50 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
>  }
제가 알기로, Topic의 updatedAt은
TOPIC 테이블에 존재한 row가 변화할 때만 업데이트 된다고 알고 있습니다.

그래서 지금과 같은 상황에서 Topic의 updatedAt으로 해결할 경우,
Topic이 새로 생기거나, Topic의 설명이나 이름이 바뀐 경우를 기준으로 나열되게 됩니다.

저희의 도메인 요구사항은
새로운 게시글이 추가되거나, 게시글의 내용이 변경된 게시판을 찾는 게 목적이지
새로 만들어진 게시판이나, 게시판의 이름이나 내용이 변경된 게시판을 찾는게 목적이 아니라는 점에서

Topic의 updatedAt을 사용하는 건 어려울 것으로 판단되는데
혹시 제가 잘못 이해한 부분이 있을까요?

2023-08-12 11:59 UTC, kpeel5839 approved these changes
확실히, 이전에 얘기 나눴던 것처럼 토픽에 핀이 추가되었을 때 상태를 갱신해줘야 할 필요가 있겠네요.

깔끔한 코드 잘봤습니다.

고생하셨습니다~!

2023-08-12 11:59 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
>  }
현재로서는 topic 에 마지막으로 핀이 추가된 시각 등을 컬럼으로 두고, pin 을 추가할 때 해당 컬럼을 갱신한 뒤, 정렬하여 가져오는 것이 가장 부하가 적어보이긴하네용!

2023-08-12 11:59 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
> +@DataJpaTest
ServiceTest 를 DataJpaTest 로 변경한 이유가 있을까용?

테스트를 더 가볍게 하기 위해서??

2023-08-13 05:16 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
> +@DataJpaTest
성능적인 요소는 전혀 고려하지 않았습니다.

제가 변경한 이유는 다음과 같습니다.

1. ServiceTest란 네이밍이 지나치게 추상화되어있기 때문입니다.
  해당 어노테이션의 이름만 보았을 때, 이게 `DataJpaTest`인지, `SpringBootTest`인지 한 눈에 파악이 어렵습니다.
  어떤 역할을 하는지 확인하기 위해선 해당 어노테이션을 열어봐야한다는 단점이 있습니다.

2. 별도의 어노테이션으로 만들어 줄 필요가 없기 때문입니다.
  `@DataJpaTest` 안에는 이미 `@Transactional`이 포함되어 있습니다.
  `@ServiceTest` 내에서 실질적으로 역할을 하는 어노테이션은  다음의 어노테이션 하나 뿐입니다.
  ```
@DataJpaTest(
        includeFilters = @Filter(
                type = FilterType.ANNOTATION, value = Service.class
        )
 )
 ```
 
 3. service 객체들을 `@AutoWired` 해야만 하는 이유에 대해 설득 되지 않았기 때문입니다.
   `@DataJpaTest`를 통해서 `@repository`를 `@AutoWired` 해온 후
   `@BeforeEach`와 setUp을 통해서 충분히 Service 객체를 만들어 줄 수 있습니다.
   해당 방법보다 `@ServiceTest` 방법을 우선시한 이유에 대해 혼자서 추측할 수 없었기 때문에 제외하였습니다.

2023-08-13 07:17 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
>  }
비즈니스적인 updatedAt이 필요하다.. 정도로 결론을 내리면 될까요 허헛

2023-08-13 07:57 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
> +@DataJpaTest
준팍 의견에 대한 제 생각은 아래와 같습니다 ! 

> ServiceTest란 네이밍이 지나치게 추상화되어있기 때문입니다.
해당 어노테이션의 이름만 보았을 때, 이게 DataJpaTest인지, SpringBootTest인지 한 눈에 파악이 어렵습니다.

저는 오히려 **"Service계층에서 사용하는 어노테이션"** 이라는 의미가 명확하게 나타난다고 생각합니다.

DataJpaTest와 SpringBootTest의 예시를 들어주셨는데, DataJpaTest의 includeFilters를 사용하였는지, SpringBootTest의 excludeFilters를 사용하였는지가 중요할까요 !?

> 별도의 어노테이션으로 만들어 줄 필요가 없기 때문입니다.
@DataJpaTest 안에는 이미 @Transactional이 포함되어 있습니다.
@ServiceTest 내에서 실질적으로 역할을 하는 어노테이션은 다음의 어노테이션 하나 뿐입니다.

`DataJpaTest`의 경우에는 JPA 관련 컴포넌트들을(엔티티 및 레포지토리 인터페이스) 빈으로 등록하기 때문에, JPA Repository 관련 테스트를 수행할 때 사용하는 것이 적절한 것 같아요.
`SpringBootTest`는 사용하지 않는 여러 컴포넌트들이 모두 빈 등록이 되기 때문에, 아무래도 낭비가 있겠죠.

단순히 Service 계층에서만 테스트를 수행하기에 적절한 어노테이션이 없기 때문에, 지금과 같은 커스텀 어노테이션이 필요하다고 생각합니다 ! (물론, 중복 사용되고 있는 `@Transactional` 어노테이션은 제거되어야 겠지요 😃)

>service 객체들을 @AutoWired 해야만 하는 이유에 대해 설득 되지 않았기 때문입니다.
@DataJpaTest를 통해서 @repository를 @AutoWired 해온 후
@BeforeEach와 setUp을 통해서 충분히 Service 객체를 만들어 줄 수 있습니다.
해당 방법보다 @ServiceTest 방법을 우선시한 이유에 대해 혼자서 추측할 수 없었기 때문에 제외하였습니다.

모든 서비스 테스트마다 `@BeforeEach`에서 필드에 존재하는 Service 클래스를 초기화 해주는 것은 불필요한 작업이지 않을까요 ?
또한, 우리는 스프링 프레임워크를 통해, 싱글톤으로 관리되는 서비스 객체를 사용하고자 하는 것이잖아요 ?
실제 프로덕션 코드에서는 싱글톤으로 관리되지만, 테스트에서는 싱글톤이 아닌 아닌 객체로 테스트한다는 것은 올바른 테스트 방법이 아닌 것 같아요.

위의 커스텀 어노테이션을 사용했을때, 또 하나의 장점으로는 우리가 작성한 서비스 클래스의 어노테이션을 빠뜨렸는지, 아닌지를 확인할 수 있다는 점이 있을 것 같아요. Service 어노테이션이 붙은 클래스를 빈 등록 대상으로 넣어주었기 때문에, 테스트 코드에 있는 `@Autowired`가 동작하지 않겠죠 ?

어디까지나 개인적인 의견일 뿐이고, 태클 환영입니당 !

2023-08-13 08:32 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
> +@DataJpaTest
> 저는 오히려 "Service계층에서 사용하는 어노테이션" 이라는 의미가 
> 명확하게 나타난다고 생각합니다.

쥬니 말씀대로 의미적으로는 명시적이나, 
기존의 표준적인 스프링 어노테이션에 익숙한 개발자 입장에선 
`@ServiceTest`의 내부 동작이나 포함된 어노테이션들을 모를 수 있으므로, 
처음 볼 때는 헷갈릴 수 있습니다.

> DataJpaTest와 SpringBootTest의 예시를 들어주셨는데, 
> DataJpaTest의 includeFilters를 사용하였는지, 
> SpringBootTest의 excludeFilters를 사용하였는지가 중요할까요 !?

저는 이 부분은 굉장히 중요하다고 생각합니다.
`@DataJpaTest`와 `@SpringBootTest`는 애초에 사용 목적이 확연하게 다르고, 
어떤 어노테이션을 쓰느냐에 따라 테스트 환경이 확연하게 차이가 나기 때문입니다.

어떤 어노테이션을 쓰느냐에 따라 무엇을 테스트 하고 싶은지를 명확히 표현할 수 있는데
커스텀 어노테이션을 사용하므로써, 표준 어노테이션을 사용할 때의 장점을
잃게 되는 것은 주의해야한다고 생각합니다.

> 또한, 우리는 스프링 프레임워크를 통해, 싱글톤으로 관리되는 서비스 객체를 
> 사용하고자 하는 것이잖아요 ?
> 위의 커스텀 어노테이션을 사용했을때, 또 하나의 장점으로는 우리가 작성한 
> 서비스 클래스의 어노테이션을 빠뜨렸는지, 아닌지를 확인할 수 있다는 점이 있을 것 같아요.

우리가 서비스 테스트를 하는 목적이 해당 부분을 검증하고자 하는 것이라면
차라리 `@DataJpaTest`보다는 `@SpringBootTest`과 `@Transactional`를  함께 
사용하는 것이 더 올바른 방향이라고 생각합니다.

> 모든 서비스 테스트마다 @BeforeEach에서 필드에 존재하는 
> Service 클래스를 초기화 해주는 것은 불필요한 작업이지 않을까요 ?

이 부분은 @BeforeAll 어노테이션으로 해결 가능할 것 같습니다.
그리고 @Service가 많아질 수록 컴포넌트 스캔 비용이 늘어날 것 같은데
@BeforeAll을 쓰면 테스트 당 한번의 비용만 발생하지 않을까요?

추가적으로, 새롭게 만들어질 테스트에서 새로운 설정을 요구하는 경우,
지금의 `@ServiceTest` 유연성이 떨어지므로, 
새로운 어노테이션을 만들어야 하거나 `@DataJpaTest`에 기존의 설정에 새로운 설정을
추가한 어노테이션을 그대로 써야하는 경우가 발생할 수 있습니다.

2023-08-13 08:53 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
> +@DataJpaTest
> 우리가 서비스 테스트를 하는 목적이 해당 부분을 검증하고자 하는 것이라면
차라리 @DataJpaTest보다는 @SpringBootTest과 @Transactional를 함께
사용하는 것이 더 올바른 방향이라고 생각합니다.

`@SpringBootTest` 어노테이션은 너무 범위가 넓다고 생각해요.
모든 Bean들을 스캔해오기 때문에, 해당 어노테이션을 통해 Repository, Service, Controller 등 모든 계층에 대한 테스트를 수행할 수 있잖아요 ?
Service 계층을 테스트하려면, Service ~ Repository 계층까지의 빈들만 필요하기 때문에 `@DataJpaTest` + Service 클래스를 불러오는 지금의 커스텀 어노테이션이 적절하다고 생각했어요 ㅎㅎ

> 이 부분은 @BeforeAll 어노테이션으로 해결 가능할 것 같습니다.
그리고 @service가 많아질 수록 컴포넌트 스캔 비용이 늘어날 것 같은데
@BeforeAll을 쓰면 테스트 당 한번의 비용만 발생하지 않을까요?

의견 전달에 조금 착오가 있었던 것 같네요 ㅎㅎ
제가 말씀드린 불필요한 작업이라는 것은, 성능적인 측면보다는 초기화 작업을 위한 프로그래머의 코드 작업을 의미하고자 했습니다.

`@BeforeAll`을 통해, 실제 초기화 비용이 한 번만 발생한다고 말씀하셨지만, 이를 싱글톤 객체로 보아도 무방할지는 조금 의문이네요 ! 

>추가적으로, 새롭게 만들어질 테스트에서 새로운 설정을 요구하는 경우,
지금의 @ServiceTest 유연성이 떨어지므로,
새로운 어노테이션을 만들어야 하거나 @DataJpaTest에 기존의 설정에 새로운 설정을
추가한 어노테이션을 그대로 써야하는 경우가 발생할 수 있습니다.

빈을 등록하는 어노테이션의 새로운 설정을 요구하는 상황을 경험해본 적이 없어서, 공감이 어렵네요 ㅠ_ㅠ 가능하다면 예시 부탁드리겠습니다 !

제가 이해한 바로는, `@DataJpaTest` 설정에 더불어 Service 계층 뿐만 아니라 다른 Component 들을 주입받아야 하는 경우를 의미하시는 것 같아요.
서비스 계층에 대한 테스트에서 위와 같은 상황이 존재할까요 ? 존재한다면, 그건 서비스 계층 테스트가 아니지 않을까 싶어요 !

2023-08-13 09:58 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
> +@DataJpaTest
제 입장은 아래 3가지 입니다.

1. Service 객체를 반드시 @AutoWired로 가져와야만 하는 경우, `@Transactional`과 불필요한 빈들을 exclude한 `@SpringBootTest`를 사용하는 방식으로 가는 것이 옳다.

2. Service 객체를 반드시 @AutoWired로 가져오지 않아도 되는 경우, `@DataJpaTest`와 `@BeforeAll`을 통해 Service 객체를 만들어주는 방식이 옳다.

3. 코드의 줄수를 줄이는 것보다는, 누가 봐도 이해할 수 있는 코드를 쓰는 것이 더 중요하기 때문에 @ServiceTest와 같은 과도한 추상화는 지양하는 것이 좋다.

다음은 쥬니의 질문에 대한 저의 생각입니다.

> @SpringBootTest 어노테이션은 너무 범위가 넓다고 생각해요.
> 모든 Bean들을 스캔해오기 때문에, 해당 어노테이션을 통해 
> Repository, Service, Controller 등 모든 계층에 대한 테스트를 수행할 수 있잖아요 ?

이 부분은 쥬니가 말씀하신대로 exclude 처리하면 되지 않을까요?

`@DataJpaTest`에서 Repository와 Service 관련 컴포넌트만 갖고 오게 설정할 수 있듯,
`@SpringBootTest`에서도 동일한 설정이 가능하니까요!

이렇게 설정하면 둘의 기능이 동일한데 왜 `@SpringBootTest`를 더 사용하냐고 물으신다면, `@DataJpaTest`는 원래 JPA 엔티티와 리포지토리에 대한 테스트를 위한 어노테이션인 반면, `@SpringBootTest`는 통합 테스트를 위한 어노테이션이기 때문입니다.

그리고 우리는 Service 테스트를 통합 테스트로 진행하고 있습니다.
(=`@Query`가 없는 Repository에 대한 테스트를 진행하지 않기 때문에)

> @BeforeAll을 통해, 실제 초기화 비용이 한 번만 발생한다고 말씀하셨지만, 
> 이를 싱글톤 객체로 보아도 무방할지는 조금 의문이네요 !

1. 우리가 검증하려고 하는 것이 Service 객체가 반드시 싱글턴이어야만 검증이 가능한가요?
2. 설사 그렇다고하더라도 `@BeforAll`을 통해서 해당 테스트 클래스 내에서 한번만 생성된다면 동작 방식은 싱글턴과 동일하지 않나요? 
3. `@AutoWired`를 통해 가져왔을 때와 `@BeforeAll`을 통해 가져왔을 때는 어떤 차이가 있나요?

> 빈을 등록하는 어노테이션의 새로운 설정을 요구하는 상황을 경험해본 적이 없어서, 
> 공감이 어렵네요 ㅠ_ㅠ 가능하다면 예시 부탁드리겠습니다 !

DataJpaTest에서 설정할 수 있는 항목들은 다음과 같습니다.
1. properties
2.showSql
3.bootstrapMode
4.useDefaultFilters
5. includeFilters
6. excludeFilters
7. excludeAutoConfiguration

현재는 includeFilters만 사용하고 있지만, 
추후 설정에 따라서 서비스별로 별도의 항목들을 설정해야할 경우가 생길 수 있습니다.
그런 경우마다 새로운 어노테이션을 만들어줄 수 없으니, 일관성을 위해서 지금부터도
커스텀 어노테이션을 만드는 것을 지양하자는 의미였습니다.

2023-08-13 10:31 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
> +@DataJpaTest
이렇게까지 이야기가 길어져야 하는 부분인가 싶긴 하지만, 재밌네요 히히 

>Service 객체를 반드시 @Autowired로 가져와야만 하는 경우, @Transactional과 불필요한 빈들을 exclude한 @SpringBootTest를 사용하는 방식으로 가는 것이 옳다.

프로젝트에 등록되어있는 빈들 중에서 exclude로 걸러내는 작업이 너무 방대하지 않을까 싶네요.
컨트롤러, 인터셉터, 컴포넌트 등 너무 많은 빈들을 걸러주어야 하지 않나요?

>Service 객체를 반드시 @Autowired로 가져오지 않아도 되는 경우, @DataJpaTest와 @BeforeAll을 통해 Service 객체를 만들어주는 방식이 옳다.

`@Autowired`를 통해 의존성 주입을 해주지 않는다면, 우리가 굳이 스프링 프레임워크를 사용할 필요가 있을까 ? 를 고민해봐야 하지 않을까 싶어요. 
프로그램 제어(의존성 주입 등)를 스프링에 위임하고, 비즈니스 로직에만 집중하기 위해 스프링을 사용하는 것 아닌가요 ?
이는 단순히, 프로덕트 코드뿐만 아니라 테스트에도 적용되는 내용이라고 생각해요.

>코드의 줄수를 줄이는 것보다는, 누가 봐도 이해할 수 있는 코드를 쓰는 것이 더 중요하기 때문에 @servicetest와 같은 과도한 추상화는 지양하는 것이 좋다.

누가봐도 이해할 수 있는 코드를 쓰는 것이 더 중요하다는 말에 동의합니다 !
다만, 지금 사용하고 있는 어노테이션이 과도하게 추상화 되어있다는 것은 잘 이해가 되지 않네요.
네이밍에서도 충분히 그 의미를 나타내고 있다고 생각해서요 ! (이 부분은 사람마다 받아들이기 나름이니, 서로 이해하고 넘어가야 하는 부분인 것 같네요 !)

>우리가 검증하려고 하는 것이 Service 객체가 반드시 싱글턴이어야만 검증이 가능한가요?

프로덕트 환경에서 싱글톤으로 관리된다면, 테스트에서도 싱글톤이어야 하지 않을까요 ?

> 설사 그렇다고하더라도 @BeforAll을 통해서 해당 테스트 클래스 내에서 한번만 생성된다면 동작 방식은 싱글턴과 동일하지 않나요?

맞습니다 ! 해당 테스트 클래스 내에서는 그렇겠지요. 
다만, 해당 서비스 클래스가 다른 테스트에서 쓰이지 않느냐 ?를 고민해보아야 할 것 같아요.
서비스 클래스를 사용하는 모든 곳에서는 각 테스트 클래스 내에서만 싱글톤으로 관리되는 객체를 사용하는 것이니까요.

>@AutoWired를 통해 가져왔을 때와 @BeforeAll을 통해 가져왔을 때는 어떤 차이가 있나요?

해당 테스트 클래스 내부에서는 싱글톤으로 관리되겠지만, 다른 클래스에서 사용하는 해당 서비스 객체와는 별개의 객체 아닐까요 ? 

>현재는 includeFilters만 사용하고 있지만,
추후 설정에 따라서 서비스별로 별도의 항목들을 설정해야할 경우가 생길 수 있습니다.

위 옵션들을 서비스별로 다르게 설정해야할 경우가 발생하여, 설정 환경에 따라 다르게 동작한다면 그것은 더이상 서비스 테스트가 아니지 않을까요 ?

2023-08-13 10:33 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
> +@DataJpaTest
너무 이야기가 길어지는 것 같으면, 월요일에 매튜 도이랑 함께 이야기해서 정해봐도 좋을 것 같아요 ㅎㅎ

정말 만사능통한 말이지만, '정답은 없다'의 영역이니까요 !!!!!

2023-08-16 02:25 UTC, merged