[BE] feature/#264 토픽에 대한 즐겨찾기 API
woowacourse-teams/2023-map-befine pull request #275
Opened 2023-08-12 16:06 UTC by cpot5620

## 작업 대상

각 토픽에 대한 즐겨찾기 관련 API
토픽 조회시, 즐겨찾기 여부 반환 로직 추가

[관련 이슈](#264)
## 📄 작업 내용

## 🙋🏻 주의 사항

토픽 조회시, TopicRepository에서 모든 토픽을 조회한 뒤에 각각의 토픽 id를 통해 BookmarkRepository를 매번 조회하는 것은 비효율적이라고 판단하였습니다.

Join 연산을 통해 한 번에 해결할 수 있을 것이라고 판단했고, 이에따라 TopicReposiotry에 JPQL이 다수 추가 되었습니다.

또한, 사용자에 따라 토픽 및 토픽에 대한 즐겨찾기 여부를 반환하기 위한 `TopicWithBookmarkStatus`가 추가되었습니다.

이를 Dto로 봐야할지.. 의문이긴 합니다만, 제 생각에는 topic.domain 패키지 내부에 repository 패키지를 두고 TopicRepository 및 해당 클래스를 두는 것이 자연스럽다고 생각합니다. (아직 적용한 상태는 아닙니다.)

추가로, 로그인 유저 / 비로그인 유저에 따라 사용하는 메서드를 다르게 하도록 분리했습니다.
(비로그인 유저는 즐겨찾기 여부를 확인할 필요가 없기 때문에, 이로 인해 join 연산을 수행하는 것은 불필요하다고 판단하였습니다.)

JPQL을 사용한 현재 로직에 대해서 궁금한 점이나, 개선해야 할 점 등 다양한 의견 많이 주시면 감사하겠습니다.
제가 작성한 코드임에도 불구하고 마음에 안 드는 부분이 상당수 존재하고, 많은 고민을 해보았지만 더 나은 방안을 찾지 못하였습니다.

현재 구현한 코드를 다 갈아엎고, 단순히 findAll 만을 통해 자바코드로 풀어내는 방안도 고려중이오니, 서슴없이 의견 내주시면 감사하겠습니다.

## 스크린샷

## 📎 관련 이슈

 
closed #264 
## 레퍼런스

2023-08-12 16:13 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
> +public class BookmarkController {
즐겨찾기라는게 아무래도, 유저와 관련된 내용이다 보니 위와 같이 URI를 작성하였습니다.

MemberController와 별도의 컨트롤러라는 점에서, 위 URI가 잘못된 구조인 것 같기도 합니다.

의견 부탁드립니다 !

2023-08-12 16:13 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
> +    }
즐겨찾기에 대한 Id를 반환해주어야 하는가 ? 라는 질문을 준팍이 하셨던 것 같아서 코멘트 남깁니다.

사용자가 자신의 즐겨찾기 목록에 존재하는 토픽을 삭제하려면, 해당 토픽의 id보다는 해당 즐겨찾기의 id를 요청하는 것이 맞다고 판단했습니다.

2023-08-13 10:57 UTC, junpakPark requested changes
쥬니 고생하셨습니다!
몇가지 사항에 대해 질문 남겼습니다 ㅎㅎ

2023-08-13 10:57 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/Bookmark.java
> +    }
연관관계를 꼭 맺어줘야할까요?

2023-08-13 10:57 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
> +public class BookmarkController {
저는 members 빼는 게 더 좋을 것 같습니다!

2023-08-13 10:57 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
> +    }
즐겨찾기에 같은 토픽이 여러개 들어갈 수 없으니, TopicId와 MemberId로 충분히 탐색할 수 있지 않을까요?
즐겨찾기 Id를 넣어주는 Response를 만들 경우 프론트에서 보여주는 내용은 동일한데 다양한 Response에 대해서 상태 관리를 해줘야하지 않을까하는 생각이 드네용ㅎㅎ

2023-08-13 11:00 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/dto/response/BookmarkResponse.java
> +public record BookmarkResponse(
BookMarkResponse 따로 만들어주기보다는 TopicResponse로 통합해서 처리 가능하지 않을까요?
TopicResponse만 있어도 BookMark를 찾는데 필요한 정보는 다 있다는 생각이 드네요 ㅎㅎ

2023-08-13 11:49 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/Bookmark.java
> +    }
생각해보니 Members엔 넣어주는게 더편할 수 있겠네요 ㅎㅎ

2023-08-13 15:52 UTC, yoondgu requested changes
쥬니  수고많으셨습니당!!
PR에 작성주신 내용을 보니 설계에 대한 고민을 많이 해주신 것 같아서, 
설계 관련 질문 위주로 코멘트 남겼습니다!

2023-08-13 15:52 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/dto/response/BookmarkResponse.java
> +public record BookmarkResponse(
저도 동의합니다.
처음에는 DTO를 통합함으로써 결합도가 높아져 안좋다고 생각했는데,
사실 Bookmark에 대한 Response는 Member가 즐겨찾기를 한 Topic에 대한 응답이기에
도메인 논리로만 생각하더라도 TopicResponse를 반환해도 자연스럽다는 생각이 듭니다!

2023-08-13 15:52 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/Bookmark.java
> +    private Long id;
P4. Bookmark가 id를 가지도록 하신 이유가 궁금합니다!
사실 Bookmark는 어떤 Member가 어떤 Topic을 즐겨찾기로 저장했는지 확인하기 위한 엔티티이고,
Response 클래스에 준팍의 코멘트처럼, memberId, topicId로도 식별이 가능하기 때문에
별도의 id 없이 복합키를 쓸 수도 있을 것 같아서요!
아니면 Bookmark의 Id를 사용해야 하는 비즈니스 로직이 있을까용?
제가 놓치고 있는 부분이 있을 것 같아 여쭤봅니다!!!

2023-08-13 15:52 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
> +            @Param("memberId") Long memberId);
Long에 null을 전달하면 어차피 BookmarkStatus가 모두 false일 것이기 때문에
서비스에서 memberId가 null일 때도 이 메서드를 호출하도록 해서
비로그인/로그인 로직을 통합하는 것은
Null에 대해 안정적이지 못한 방식이라서 쓰지 않으신걸까요..?!

2023-08-13 15:52 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
> +    }
P3. canDelete boolean을 반환하는 부분을 canDelete() 메서드로 분리해줘도 좋겠네요!

2023-08-13 15:52 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
> +    }
topicId, memberId로 식별하고, 그렇게 되면 아예 id 대신 두가지를 복합키로 하는 방식도 괜찮아보입니다!

2023-08-13 15:52 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
> +    }
토픽 같이보기 기능에서 IsInAtlas를 판단하는 로직과 같이
즐겨찾기에서도 member의 모든 즐겨찾기 토픽을 조회한 뒤, contains로 isBookmarked를 판단할 수도 있을텐데
join으로 푸는 방법을 택하시게 된 이유가 궁금합니다!

2023-08-14 00:37 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/Bookmark.java
> +    }
다시 생각해보니 topic이 북마크된 숫자도 반환해야하니 필요하겠군요
굿굿...

2023-08-14 02:31 UTC, kpeel5839 requested changes
쥬니짜응 고생하셨어요!

고생이 느껴지는 코드들이네요

멋져부렁

2023-08-14 02:31 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkQueryService.java
> +                .toList();
대부분의 변환 로직이 굉장히 간략화 될 것 같아서 좋을 것 같습니다!

킹치만, 아주 조금 우려가 되는 부분은

```java
public Bookmark toBookmark(Topic topic) {
    ...
}

return topic.stream()
        .map(this::toBookmark)
        .map(BookmarkResponse::from)
        .toList();

->

List<Bookmark> bookmarks = topic.stream()
        .map(this::toBookmark)
        .toList();

return BookmarkResponse.from(bookmarks)
```

(toBookmark 는 예시를 들기 위해서 사용한 임의의 변환 메서드입니다.)

위와 같은 경우 원래 한번의 스트림으로 해결할 수 있었지만, 해당 정팩매를 둠으로써 중간에 toList() 를 통해 추출해내야 한다는 단점도 생길 수 있을 것 같아요.

이런 경우에서만 정팩메를 사용하지 않는다는 저희만의 컨벤션을 만들거나, 혹은 더 나아가 이런 경우는 발생하지 않을 것 같다고 판단되면 추가해도 너무 좋을 것 같습니다!

2023-08-14 02:31 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/Bookmark.java
> +    // TODO: 2023/08/11 필요한 검증이 무엇이 있을까.. 현재로썬 외부에서 검증하는 방법 밖에 ?
쥬니짱 제가 위에서 코멘트 드렸던 부분

> 음 그리고 사용자가 즐겨찾기를 중복으로 실행하는 경우도 고려할 수 있을 것 같아요 쥬니짱.

> 물론 화면딴에서는 쥬니짱이 추가해주신 isBookmarked 로 인해 중복으로 즐겨찾기 하는 경우는 막을 수 있겠지만, 악의적인 유저가 Postman 을 이용하여 중복으로 즐겨찾기 요청을 계속 보내게되면 동일한 정보들이 DB 에 저장될 수도 있지 않을까? 하는 우려가 들기도 하네요

을 여기서 해결할 수 있지 않을까? 싶어요!

`(topic/member).alreadyContainsBookmark()` 이런 메서드를 만들어 해당 토픽이나 멤버에 현재 추가하려는 bookmark 가 이미 존재하는지 확인한다면

중복으로 저장되는 경우도 쉽게 막을 수 있을 것 같긴한데

쥬니짱짱 생각은 어떠세요?

2023-08-14 02:31 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/Bookmark.java
> +    // TODO: 2023/08/11 필요한 검증이 무엇이 있을까.. 현재로썬 외부에서 검증하는 방법 밖에 ?
물론 위 방식을 기용하면 equals, hashcode 를 추가해줘야 할 것 같긴하네요

2023-08-14 02:31 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/dto/response/BookmarkResponse.java
> +public record BookmarkResponse(
저는 현재 topicResponse 에 isBookmarked 가 포함되어 있어, 현재 방식도 괜찮아보이긴합니다.

만일 topicResponse 로 반환하게 된다면, TopicResponse.from(Topic topic) 을 호출해야할테고, 그렇다면 무조건 isBookmarked 가 false 로 설정되게 될테니까요.

2023-08-14 02:31 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
> +public class BookmarkController {
젇후영~~~~~!

2023-08-14 02:31 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
> +    }
유연성 제한: id 컬럼 없이 memberId와 topicId만 사용하면 테이블 내에서 각 행을 고유하게 식별할 수 있습니다. 하지만 id를 사용하는 경우, 나중에 유연하게 스키마를 변경하거나 다른 관련 정보를 추가하는 데 더 유리할 수 있습니다.

성능 이슈: 복합키로 인덱스를 생성할 경우, 검색 성능이 향상될 수 있지만, 조건에 따라 성능이 저하될 수도 있습니다. 특히 대량의 데이터에서 복합키를 사용하면 인덱스 크기가 커져서 일부 검색 작업에서 더 많은 리소스를 필요로 할 수 있습니다.

복잡성 증가: 복합키를 사용하면 데이터베이스 쿼리 및 조인 작업이 복잡해질 수 있습니다. 특히 다른 테이블과의 조인 작업에서 조금 더 복잡한 SQL문이 필요할 수 있습니다.

데이터 무결성 유지: 복합키를 사용하는 경우, 데이터 무결성을 유지하기 위해 추가적인 제약 조건이나 처리 로직이 필요할 수 있습니다. 이를 관리하는 것도 고려해야 합니다.

확장성 제한: 나중에 테이블에 다른 컬럼을 추가하거나 변경할 때, 복합키가 있는 경우 일부 작업이 더 복잡해질 수 있습니다.

gpt가 복합키를 사용했을 때의 단점은 이렇다고 하네용.

2023-08-14 04:43 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
> +    }
id를 제거하는 방식이 아닌, 삭제 등의 요청에 대해 복합키를 사용하는 방식으로 결정하겠습니다 !

2023-08-14 05:07 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/Bookmark.java
> +    private Long id;
복합키를 기본키로 사용하는 구현 방식이 복잡하여 (Serializable, equals&hashCode 재정의 등) 기본키 자동 생성 전략을 택했는데요 ! 

즐겨찾기를 삭제할 때, 각 id 값을 통해 삭제를 요청해야 올바른 흐름이라고 생각했어요.

하지만 이럴 경우, 토픽의 데이터를 내려줄 때 즐겨찾기 목록인지 아닌지에 따라 response body가 달라진다는 점에서 프론트에서 관리해야하는 포인트들이 더 생기는 것 같네요.

준팍과 도이의 의견을 일부 반영하여, 내부적으로는 기본키를 유지하되, 비즈니스 로직(즐겿자기 삭제 등)에서는 복합키로 처리하도록 하겠습니다.

2023-08-14 05:29 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
> +public class BookmarkController {
반영했습니다 ~

2023-08-14 05:30 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkQueryService.java
> +                .toList();
저도 개인적으로 List 자체를 넘겨주는 것 좋습니다 ㅎㅎ

매튜가 착각한 것 같은데, List로 추출하지 않고 stream에서 한 번에 처리할 수 있지 않나요 !?

2023-08-14 05:40 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
> +            @Param("memberId") Long memberId);
비로그인 사용자라면, 항상 BookmarkStatus가 false이겠죠 ?

비로그인 유저임에도 불구하고 Join 연산을 수행하는 것은 비효율적이라고 생각했습니다.

2023-08-14 05:40 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
> +    }
해당 사항 반영했습니다 ㅏ!

2023-08-14 05:48 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
> +    }
실제 성능은 확인해보아야 겠지만, join 연산을 통해 풀어내는 것이 성능적 이점이 있다고 판단했습니다.

select 쿼리 2번 + 자바 코드로 isBookmarked를 판단하기 위한 stream 연산 수행을 join 한 번에 풀어낼 수 있으니까요 !

2023-08-14 05:49 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
> +    }
> 물론 화면딴에서는 쥬니짱이 추가해주신 isBookmarked 로 인해 중복으로 즐겨찾기 하는 경우는 막을 수 있겠지만, 악의적인 유저가 Postman 을 이용하여 중복으로 즐겨찾기 요청을 계속 보내게되면 동일한 정보들이 DB 에 저장될 수도 있지 않을까? 하는 우려가 들기도 하네요

아앗.. 포스트맨이 있었군요.
저는 프론트 크루들을 전적으로 신뢰하고 있었기 떄문에, 별다른 검증을 하지 않았는데 ㅎㅎ

해당 사항 반영하였습니다 !

2023-08-14 06:05 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/Bookmark.java
> +    // TODO: 2023/08/11 필요한 검증이 무엇이 있을까.. 현재로썬 외부에서 검증하는 방법 밖에 ?
좋은 방법인 것 같아요 ㅎㅎ
다만, 한 가지 우려되는 부분은 member 혹은 topic에서 OneToMany로 가지고 있기 때문에, 이후에 지연 로딩을 적용할 것이잖아요 ?

즐겨찾기는 매우 가벼운 비즈니스 로직인데, 매번 모든 정보를 가져와야 한다는 점이 걱정되네요 ㅎㅎ

이에따라, Service 계층에서 검증을 수행하도록 하겠습니다 !

2023-08-14 07:50 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/Bookmark.java
> +    // TODO: 2023/08/11 필요한 검증이 무엇이 있을까.. 현재로썬 외부에서 검증하는 방법 밖에 ?
네네 제 생각에도 Repository 에서 확인하는 것이 성능상 이점이 있을 것 같지만, 뭔가 조금 더 객체지향적으로 해결하려면 위와 같은 방법을 채택하는 것이 어떨까 해서 말씀드렸었습니당 홍홍홍

2023-08-14 08:11 UTC, yoondgu approved these changes
수고 많으셨습니당 ~!!

2023-08-14 08:13 UTC, kpeel5839 approved these changes
변경된 부분 확인했습니다!! 감사해오오오어어어어어어어엉~

2023-08-14 08:14 UTC, junpakPark approved these changes
고생하셨습니다 쥬니~

2023-08-14 08:38 UTC, merged