[BE] feature/#255 소셜로그인 구현
woowacourse-teams/2023-map-befine pull request #277
Opened 2023-08-13 11:50 UTC by kpeel5839

## 작업 대상

카카오 소셜로그인

## 📄 작업 내용

- 카카오 소셜로그인 구현

## 🙋🏻 주의 사항

이해를 돕기 위해 `Oauth Flow` 를 아래 사진을 이용하여 간단하게 설명드리도록  하겠습니다.

아래의 사진을 보시면 `Resource Owner`, `Client`, `Authorization Server, Resource Server` 등이 있습니다.

간단하게 `Resource Owner` 는 우리 서비스에 접속한 사용자

`Client` 는 우리 괜찮을지도 서비스

`Authorization Server, Resource Server` 는 구글, 카카오 등의 정보를 제공하는 플랫폼입니다.

저희가 이번에 구현한 플랫폼은 카카오구요

말랑의 블로그를 참고하여 확장에 유연하도록 구현하였으니, `Naver`, `Google`, `Facebook` 등등 추가하기는 아주 쉬울 것입니다.

---
# Oauth Flow

- 사용자가 로그인 버튼을 누르는 경우

사용자가 프론트에서 만들어 준 로그인 버튼을 누릅니다.

버튼을 누름과 동시에 `/oauth/kakao` 로 요청을 보내게 됩니다.

이 때, 사용자에게 `kakao` 로그인 화면을 제공하기 위해 `client_id (카카오에게 발급받은 KEY, 짜피 URL 에 다 공개되서 보안이 중요하지는 않음)`, `response_code (고정된 값)`, `redirect_uri (사용자가 로그인에 성공하면 돌아갈 uri)`, `scope (사용자에게 정보 제공 동의를 받을 항목들)` 등을 이용해 url 을 가공하여 반환합니다.

```java
@GetMapping("/{oauthServerType}")  
public ResponseEntity<Void> redirection(  
        @PathVariable OauthServerType oauthServerType,  
        HttpServletResponse response  
) throws IOException {  
    String redirectUrl = oauthService.getAuthCodeRequestUrl(oauthServerType);  
    response.sendRedirect(redirectUrl);  
  
    return ResponseEntity.ok().build();  
}
```

- 위 url 을 통해 사용자가 로그인을 성공한 경우

사용자가 로그인을 성공하게 된다면 프론트엔드는 저희가 url 에 담아 보낸 redirect_uri 로 redirection 되면서 auth code 를 함께 받게 됩니다.

프론트엔드는 이 auth code 를 이용하여 `oauth/login/kakao?code={auth code}` 로 요청을 보내게 됩니다.

이제 백엔드는 해당 요청과 함께 담겨온 code 를 이용하여, kakao 서버에 요청을 보내게 됩니다. 

그러려면 저희가 외부에 요청을 보낼 기술이 필요하겠죠.

이 때 사용한 기술은 `Http Interface Client` 이고,

아래 코드는 위에서 언급한 `Http Interface Client` 를 이용하여 Kakao 서버에 요청을 보내게 되는 부분입니다.

```java
public interface KakaoApiClient {  
  
    @PostExchange(url = "https://kauth.kakao.com/oauth/token", contentType = APPLICATION_FORM_URLENCODED_VALUE)  
    KakaoToken fetchToken(@RequestBody MultiValueMap<String, String> params);  
  
    @GetExchange("https://kapi.kakao.com/v2/user/me")  
    KakaoMemberResponse fetchMember(@RequestHeader(name = AUTHORIZATION) String bearerToken);  
}
```

보시면 아시다시피 토큰을 발급받기 위해서는 `fetchToken()` 을 이용해 `https://kauth.kakao.com/oauth/token` 에 정상적인 정보들을 `body` 에 담아 보내야합니다.

이 때, `body` 에 담는 값은 `grant_type`, `client_id`, `redirect_uri`, `code (로그인 성공시 프론트에게 넘겨받은 auth code`, `client_secret (카카오에게 발급받은 secret key, 아주 중요해버렷)` 입니다.

정상적인 정보를 잘 담아 보냈다면 `Token` 을 발급받게 될 것이고, 해당 `Token` 을 이용하여 `fetchMember()` 를 통해 `https://kapi.kakao.com/v2/user/me`  에 요청을 보내면 됩니다.

`Token` 이 정상적으로 Kakao 에게 발급받은 `Token` 이 맞다면 `해당 유저의 정보`를 받아오게 되고, 우리는 이 값을 이용하여 `처음 로그인한 유저이면` DB 에 저장하고, 이미 DB 에 해당 멤버의 정보가 존재하여 `처음 로그인한 유저가 아니라` 판단이 되면 저장하지 않습니다.

위와 같은 동작을 모두 완료한 후, 유저의 정보와, 유저의 id 값을 암호화하여 만든 JWT를 함께 반환합니다.

---

아무래도 `Oauth` 에 대한 지식이 부족하다면 이해가 힘든 코드들이라 설명이 길었습니다.

혹시나 설명이 부족하다고 생각이 드신다면 말씀해주세요. 

귀에다가 속삭여 드릴게요!

## 스크린샷

<img width="856" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/89840550/27cb6b75-0a42-4d55-9150-1193121e63ef">

[출처 - 말랑의 블로그](https://ttl-blog.tistory.com/1434)

## 📎 관련 이슈

#254 #255 

 

#255 

## 레퍼런스

[기가막힌 말랑의 블로그](https://ttl-blog.tistory.com/1434)

2023-08-13 12:03 UTC, junpakPark requested changes
굉장히 큰 작업인데 멋지게 해내셨군요 ㅎㅎ
몇가지 피드백 및 질문 남겨봤습니다!

2023-08-13 12:03 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
> +
기본 닉네임 생성을 위한거죠? ㅋㅋ 귀엽네요

2023-08-13 12:15 UTC, junpakPark requested changes
ㅋㅋ 몇개 생각나서 더 추가해봅니다

2023-08-13 12:15 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/BearerAuthorizationExtractor.java
> +    private static final String BEARER_TYPE = "Bearer";
위에 개행을 넣어주는 건 어떨까요?

2023-08-13 12:15 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/BearerAuthorizationExtractor.java
> +        return null;
```
public AuthInfo extract(HttpServletRequest request) {
    return Collections.list(request.getHeaders(AUTHORIZATION))
            .stream()
            .filter(this::isBearerType)
            .map(this::extractAuthHeaderValue)
            .findFirst()
            .map(AuthInfo::new)
            .orElse(null);
}

private boolean isBearerType(String value) {
    return value.toLowerCase().startsWith(BEARER_TYPE.toLowerCase());
}

private String extractAuthHeaderValue(String value) {
    String authHeaderValue = value.substring(BEARER_TYPE.length()).trim();
    int commaIndex = authHeaderValue.indexOf(',');
    if (commaIndex > 0) {
        return authHeaderValue.substring(0, commaIndex);
    }
    return authHeaderValue;
}
```

메서드 분리와 스트림을 이용해서 간결하게 만들어 보는 건 어떨까요?

2023-08-13 16:04 UTC, yoondgu commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-webflux'
카카오에 보내는 HTTP 요청을 쉽게 하기 위해 HttpInterface를 사용하는데, 
이 경우 webflux 의존성을 추가해주어야 합니다. ㅜㅜ
여러 선택지 중 HttpInterface가 가장 깔끔한 코드로, 직관적으로 사용할 수 있다고 해서 이를 사용했습니다.
WebClient는 마찬가지로 webflux 의존성을 추가해야 하고,
webflux 의존성이 필요없는 RestTemplate은 코드가 복잡해진다고 하더라고요!
깊게 고민해보지 못했는데, 과도한 의존성 추가일지 검토해보도록 하겠습니다

2023-08-13 16:13 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/BearerAuthorizationExtractor.java
> +        return null;
헉 이 부분 리팩터링을 놓쳤네요..!! 감사합니다 👍👍

2023-08-14 00:39 UTC, junpakPark commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-webflux'
아항 필요하다면 의존성 추가도 좋다고 생각합니다!
진짜 궁금해서 물어본거였어요....

2023-08-14 00:49 UTC, junpakPark approved these changes
리뷰 남긴 사항 잘 반영해주셔서 감사합니다 ㅎㅎ
새로 남긴 피드백은 P4입니다.
Approve하겠습니다.
수고 많으셨습니다!

2023-08-14 00:49 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/MapbefineApplication.java
> +@ConfigurationPropertiesScan
```
@Configuration
@ConfigurationPropertiesScan
public class PropertiesConfig {
}
```

제가 `@EnableJpaAuditing`를 JpaConfig 파일로 분리해놨었는데요
`@ConfigurationPropertiesScan`도 분리해보는 것은 어떨까요?

용도는 추후에 필요한 빈 설정이나 추가적인 구성 요소를 추가할 때,
어노테이션 별로 관리하기 위함입니다!

2023-08-14 00:56 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java
> +    private boolean isAuthMemberNotRequired(HandlerMethod handlerMethod) {
@yoondgu @kpeel5839 

approve 했지만 추하게 피드백을 더 달자면...
P4: 가독성을 위해 아래와 같이 한번 더 메서드 분리하는 건 어떨까요? ㅋㅋ

```

    private boolean isAuthMemberNotRequired(HandlerMethod handlerMethod) {
        return Arrays.stream(handlerMethod.getMethodParameters())
                .noneMatch(this::isEqualsToAuthMember);
    }

    private boolean isEqualsToAuthMember(MethodParameter parameter) {
        return parameter.getParameterType().equals(AuthMember.class);
    }
```

2023-08-14 04:40 UTC, cpot5620 approved these changes
고생 많으셨습니다 도이 매튜...

OAuth 지식이 부족하다보니, 깊이 있는 코드리뷰가 어려웠습니다 ㅠㅠ
한 가지 코멘트만 남겨두었는데, 확인 부탁드려요 ~!

2023-08-14 04:40 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/presentation/OauthController.java
> +    }
redirect라면 200 반환이 맞을까요 ~?

2023-08-14 04:41 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/presentation/OauthController.java
> +    }
302 ?

2023-08-14 05:28 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/MapbefineApplication.java
> +@ConfigurationPropertiesScan
현재로서는 추가가 힘드네용... 추후에 수정하도록 하겠씀돠! 쭌뺶

2023-08-14 05:29 UTC, merged