[FE]Feature/#382 반응형 대응
woowacourse-teams/2023-map-befine pull request #387
Opened 2023-09-08 10:03 UTC by semnil5202

## 작업 대상

추후 작성 예정

## 📄 작업 내용

## 🙋🏻 주의 사항

## 스크린샷

## 📎 관련 이슈

 

## 레퍼런스

2023-09-11 05:07 UTC, afds4567 approved these changes
레벨 3부터 골칫거리였는데 세인 덕분에 해결됬네요 👍 
테코톡 핑계삼아 모르는거 위주로 커멘트 남겼습니다~

2023-09-11 05:07 UTC, afds4567 commented on frontend/src/components/Modal/index.tsx
> +  @media (max-width: 744px) {
이 부분이 회의 때 보여준 테블릿 대응 모달이네요 👍

2023-09-11 05:07 UTC, afds4567 commented on .github/workflows/fe-pull-request.yml
> +          working-directory: frontend
왜 안되냐고 왜안되냐고 왜안되냐고

2023-09-11 05:07 UTC, afds4567 commented on .github/workflows/fe-pull-request.yml
> +  jest_cypress:
왜 테스트 통과 안되냐고

2023-09-11 05:15 UTC, afds4567 commented on frontend/src/pages/RootPage.tsx
> +        <NavbarHighlightsProvider>
Navbar컴포넌트에서만 사용되는줄 알았는데 SeeAllPopularTopics같은 페이지에도 사용됬었군요

2023-09-11 22:36 UTC, GC-Park requested changes
세인 반응형 너무나 고생했습니다!!

제가 코드를 보다가 사소한 것들에서 궁금한 것들이 많이 생겨 코멘트가 많아졌습니다!

간략하게 답해주셔도 괜찮습니다! 천천히 리뷰 주십시오 !!

2023-09-11 22:36 UTC, GC-Park commented on frontend/src/pages/SelectedTopic.tsx
> +      setSelectedPinId(null);
오호 `setSelectedPinId(null);`을 명시적으로 넣어주는 이유가 따로 있을까요?! 에러가 있었나요?!

2023-09-11 22:36 UTC, GC-Park commented on frontend/src/pages/SelectedTopic.tsx
> +  }
'calc(100vw - 40px)'가 아닌 calc(50vw - 40px);을 넣어준 이유가 있을까요?!!

그리고 1076px은 아이패드 화면을 위한 기준값 일까요?!

2023-09-11 22:36 UTC, GC-Park commented on .github/workflows/fe-pull-request.yml
> +          start: npm run dev
👍

2023-09-11 22:36 UTC, GC-Park commented on frontend/cypress.config.ts
> +    defaultCommandTimeout: 10000,
👍👍 🫡

2023-09-12 07:30 UTC, semnil5202 commented on frontend/src/pages/SeeAllPopularTopics.tsx
useParams로 구분하는 것도 좋아보입니다. 해당 부분 추후 논의사항에 추가해놓을께요~

2023-09-12 07:31 UTC, semnil5202 commented on frontend/src/pages/SelectedTopic.tsx
> +      as="section"
네 as 어트리뷰트 말씀하시는거죠?

2023-09-12 07:33 UTC, semnil5202 commented on frontend/src/components/Layout/index.tsx
> +const LogoWrapper = styled.section<{ $mediaWidth: '372px' | '100vw' }>`
공통으로 선언해서 사용한다는게 어떤 말씀이실까요?

2023-09-12 08:30 UTC, GC-Park approved these changes

2023-09-12 09:23 UTC, merged