[BE] Feat/#378 Admin API 구현
woowacourse-teams/2023-map-befine pull request #405
Opened 2023-09-13 13:56 UTC by cpot5620

## 작업 대상

관리자 페이지에 사용할 API 구현
## 📄 작업 내용

 - 사용자 관리 기능
 - 토픽 삭제 기능
 - 토픽 특정 이미지 삭제 기능
 - 핀 삭제 기능
 - 핀 특정 이미지 삭제 기능
## 🙋🏻 주의 사항

**1. 기존에 존재하는 API를 활용할 수 없는 기능들에 대해서 별도의 Service를 통해 구현했습니다.**

ex) 일반 사용자가 조회할 수 있는 Member의 정보와 Admin이 조회할 수 있는가 정보가 다르다.
-> AdminQueryService에서 구현

**2. 특정 멤버를 서비스로부터 차단(탈퇴)시킬 경우, 관련된 Topic, Pin을 삭제해야합니다.**
hard-deleting 할 경우, 추후 문제가 될 수 있는 요소가 존재한다고 판단했습니다.
ex) 범죄 등에 사용 될 경우 증거 자료 유지 필요 (?)
이에따라, soft-deleting을 수행해야했습니다.

cascde remove + @SqlDelete 어노테이션을 사용하려 했으나, Entity에 native Query가 존재한다는 점이 별로...라고 생각했습니다.
또한, @SqlDelete를 달아둘 경우, 영속성 컨텍스트가 flush 될 때 해당 쿼리문으로 바꿔서 나가기 때문에 테스트에 어려움이 생겼습니다.
(보다 자세한 설명이 필요하다면 요청 부탁드립니다)
이에따라, JPQL을 활용하여 soft-deleting을 구현했습니다.

**3. 권한 등을 부여할 때 회원 조회가 일어나는데, 2번 상황으로 인해 차단 된 회원도 조회될 가능성이 존재합니다.**
이에따라, MemberInfo 내부에 Status라는 필드를 추가했습니다. 
해당 Status는 일반 사용자(Normal), 탈퇴 회원(DELETE), 차단 회원(BLOCK)으로 구성되어 있습니다.
탈퇴 회원과 차단 회원을 분리한 이유는, 추후 재 가입시에 차단 회원인 경우 가입을 금지시켜야한다고 판단했기 때문입니다.
 
4. RestDocs + Repository + Service 계층까지는 테스트를 구현했으나, E2E 테스트가 미구현된 상태입니다.
리뷰 반영을 고려했을 때, E2E 테스트 구현 후 PR 요청시 일정을 맞추기 어려울 것이라고 판단하여 우선적으로 PR 요청 보냅니다.

## 스크린샷

## 📎 관련 이슈

 
closed #378 
## 레퍼런스

2023-09-14 09:20 UTC, yoondgu requested changes
바쁜 중에 수고 많으셨습니다 !!  🕹
좋은 점들 코멘트도 남길 게 많았지만  
일정 상 쉽게 리뷰 확인 하실 수 있도록 질문/제안 위주로만 코멘트 남겼어요.  

질문은 `Q.`, 제안은 `P2`, `P3` 남겼고, `P2` 부분만 변경 요청입니다!

그리고 쥬니 설명 듣고 나니, 기존의 회원 조회 API에서는 불필요한 정보들을 빼야할 것 같네요!!  
이 부분은 다 같이 인지하고 넘어갔으면 해서 코멘트에 남깁니다 ~

```
{
  "id" : 1,
  "nickName" : "member",
  "email" : "member@naver.com", // 다른 회원도 이 회원의 이메일을 알게 됨. 빼야할듯
  "imageUrl" : "https://map-befine-official.github.io/favicon.png", 
  "updatedAt" : "2023-09-13T15:11:47.683507704"
}
```

2023-09-14 09:20 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminQueryService.java
> +    }
P2.

이 코드 흐름에서 Member를 찾지 못한다면 400번대(사용자 잘못의 오류)보다는 코드나 데이터가 잘못되어서 발생하는 것 아닐까요 ??
Interceptor에서 이미 검증을 하니까요..!!
그래서 다른 서비스에서는 같은 상황에 대해서 아래와 같이 internal server error로 처리되는 예외를 던지고 있습니당

(동일한 흐름의 코드들 모두 해당하는 코멘트입니다!)

```java
    private Member findMemberById(Long id) {
        return memberRepository.findById(id)
                .orElseThrow(() -> new NoSuchElementException("findCreatorByAuthMember; member not found; id=" + id));
    }
```

2023-09-14 10:02 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/presentation/AdminController.java
> +    @DeleteMapping("/pins/images/{imageId}")
`pins/{imageId}/images` 라는 URL은 조금 부자연스럽게 느껴지는 것 같아요.
imageId는 1:1로 매핑되는 값인데, 뒤에 `/images`가 추가된다는게 어색하게 느껴지네요 ㅠ_ㅠ

차라리 `pinImages/{imageId}`는 어떨까요 !?

2023-09-14 10:14 UTC, junpakPark requested changes
쥬니 많이 바뀌었는데도 깔끔해서 리뷰하기 편했습니다
몇가지 제안 간단히 남겨뒀습니다.
제가 고려하지 못한 이유가 있다면 이유만 간단히 남겨주세요

수고하셨습니다~!!

2023-09-14 10:14 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminQueryService.java
> +        validateAdminPermission(admin);
P4. AuthMember 안에 `isRole(Role role)` 메서드를 두는 건 어떨까요?
Interceptor에서 이미 데이터를 가져오고 있는데 검증을 위해서 한번 더 가야하는 것 같아서용 ㅋㅋ

만약 해당 메서드 도입한다면 여기선 `authMember.isRole(Role.ADMIN)`로 변경 가능할 것 같네요!

2023-09-14 10:14 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminQueryService.java
> +        List<Member> members = memberRepository.findAllByMemberInfoRole(Role.USER);
P5. 전체 사용자가 아닌 USER만 찾는 것 같은데 ADMIN은 어떤 이유에서 제외하셨는지 궁금합니당ㅋㅋ

2023-09-14 10:14 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/admin/presentation/AdminController.java
> +    @DeleteMapping("/pins/images/{imageId}")
전 이 부분은 쥬니가 한 게 더 자연스럽다구 생각합니다.
Topics/ 구체적인 Topic/ 해당 토픽의 이미지
핀 / 핀의 이미지들 / 구체적인 이미지
이런 흐름이라고 생각해서요!

Pins 다음에 PinId가 들어가면 의미가 더 명확해지긴 하겠지만
불필요한 정보를 받을 필요도 없다고 생각하기 때문에 지금도 괜찮은 것 같네요

2023-09-14 10:14 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/AuthService.java
> +    }
차라리 validateRole 자체를 AuthService에 두는 건 어떨가요?

2023-09-14 10:17 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/admin/presentation/AdminController.java
> +    @DeleteMapping("/pins/images/{imageId}")
오 쥬니 새로운 의견대로 가는 게 제일 깔끔하겠는데요?

2023-09-14 10:17 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/admin/presentation/AdminController.java
> +    @DeleteMapping("/pins/images/{imageId}")
아 이부분은 제가 생각을 잘못한 것 같아요!!! 쥬니가 하신대로 진행하는 것 동의합니다 ~

2023-09-14 10:37 UTC, kpeel5839 requested changes
쥬니 너무 고생했어요~~~

다른 분들이 이미 의견 많이 남겨주셔서 저는 대부분 궁금한 사항들로 남겼습니다.

고생하셨어요 알러뷰

2023-09-14 10:37 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/dto/AdminMemberDetailResponse.java
> +    // TODO: 2023/09/12 topics, pins 모두 member를 통해 얻어올 수 있다. Service에서 꺼내서 넘겨줄 것인가 ? 아니면 DTO에서 꺼내올 것인가 ?
제가 최근들어 N + 1 문제에 대해서 알게되서 그런지, Member 에서 꺼내오는 것이 추후 Join 을 통해서 성능 개선하기에 쉬울 것 같아요.

2023-09-14 10:37 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +    }
그리고 Permission 과 Bookmark, Atlas 등등은 안지워도 될까요?

2023-09-14 10:37 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
> +
테스트 꼼꼼하게 작성해주셨네요 정말 고생하셨습니다

2023-09-14 10:37 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/admin/presentation/AdminControllerTest.java
> +                    37,
산스장 가보고 싶다

2023-09-14 11:09 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/application/OauthService.java
> +        throw new MemberForbiddenException(MemberErrorCode.FORBIDDEN_MEMBER_STATUS, member.getId());
> 특정 자원에 접근하는 것이 아니라 로그인을 시도하는 것이기 때문에 NOT_FOUND 보다 UNAUTHORIZED 로 하는 건 어떨까요 ?

NOT_FOUND ????? FORBIDDEN 이야기 하신거죠 ㅎㅎ?
해당 사항 동의합니당 ! 반영토록 하겠습니다.

> 탈퇴 혹은 차단된 회원입니다. 이 에러 메시지를 주는 군요!
에러 메시지에서 로그인을 시도한 사용자에게 해당 id가 탈퇴/차단된 회원이라는 정보를 노출하는 대신
에러 메시지는 다른 로그인 실패 시 메시지와 똑같이 하고, 저희끼리 에러 코드로만 식별하는 건 어떨까요?

에러 코드를 통해 식별한다는 것은 프론트도 마찬가지일까요 ?
차단당한 사용자가 로그인할 때, 차단되었다는 사실을 알려주는 것이 자연스럽다고 생각했어요.
프론트측에서 에러 코드로 다르게 처리해준다면, 도의 의견에 동의합니다 !!

(당연히 해줄거니까) 반영하도록 하겠습니다 ㅎㅎ

--- 

Auth 관련해서 ERROR_CODE가 너무 분산되어 있어서, 클래스 auth 패키지 내부에 exception 패키지 추가했는데 확인부탁드려용

2023-09-14 11:11 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
> +        PinImage deletedPinImage = pinImageRepository.findById(pinImage.getId()).get();
맞아요.......해야되요 ㅠㅠㅠㅠㅠㅠㅠㅠ

2023-09-14 11:16 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/presentation/AdminController.java
> +    public ResponseEntity<List<AdminMemberResponse>> findAllMembers(AuthMember authMember) {
Service에서 이중으로 검증하기 위함이었어요 !
사실 Admin 객체를 받는 것이 조금 더 자연스러울 것 같긴 하네요.
아니면, ArgumentResolver 사용해서 Member 객체를 받아도 될 것 같아요.

어떤 방법이든 Service에서 검증해줄 수는 있으니까요.

어떤 방법이 좋을까요 ?

---

별거 아니지만, Member 객체를 그대로 받아버리면 임의로 조작해서 Role을 수정해줄 수도 있을 것 같아요. (새로 생성하는 등의 방법)
이정도는 믿음으로 가야할까요 ㅎㅎ?

2023-09-14 11:32 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/AuthService.java
> +    }
아래와 같이 수정하였습니다 ! 

```java
    public boolean isAdmin(Long memberId) {
        if (Objects.isNull(memberId)) {
            return false;
        }

        Optional<Member> member = memberRepository.findById(memberId);

        return member.map(Member::isAdmin)
                .orElse(false);
    }
```

2023-09-14 11:35 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +    }
사실 Permission, Bookmark 해야되는거 알고 있는데, 귀찮아서요 ...
너무 많은 Repository를 알고 있어요......

2023-09-14 12:13 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Status.java
> +    BLOCKED("STATUS_BLOCKED", "차단된 사용자");
맞습니다 !!!!!!!!!!!!

2023-09-14 12:19 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminQueryService.java
> +    }
이전 PR들에서 해당 부분을 전혀 인지 못했었던 것 같네요.
우선, 코드 통일성을 위해 해당 사항은 반영하도록 하겠습니다.

다만, Interceptor에서 검증을 수행하기 때문에, Server ERROR로 본다는 것은 Service 계층이 Interceptor에 의존적인 것 같다는 생각이 듭니다.

2023-09-14 12:25 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminQueryService.java
> +        List<Member> members = memberRepository.findAllByMemberInfoRole(Role.USER);
ADMIN이 ADMIN을 삭제할까봐...?
관리자들 사이에서의 개인정보는 지켜주고 싶어서 ..?
별 다른 이유는 없습니다 ㅎㅎ 

그냥 관리자는 일반 유저들을 관리한다고 생각해서 위와 같이 구현했던 것 같아요.

모든 회원을 조회하도록 수정하는 것이 자연스럽다면, blockMember 메서드에서 삭제하려는 Member가 Admin인지 검증하는 로직이 필요하겠네요.

어떻게 생각하시나용

2023-09-14 12:26 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminQueryService.java
> +        validateAdminPermission(admin);
https://github.com/woowacourse-teams/2023-map-befine/pull/405#discussion_r1325795511

위 코멘트와 관련이 있는 것 같아요.

다른 분들의 의견처럼 Interceptor에서 수행하기 때문에, Service에서 검증이 필요 없다고 하시면 기존 코드 그대로 가져가도 될 것 같아요.
만약, 지금처럼 이중 검증을 수행한다면 해당 사항 반영하는 것이 더 좋을 것 같긴 하네요 ㅎㅎ..

내일 이야기 나누어보고 결정하도록 하겠습니다.

2023-09-14 12:52 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminQueryService.java
> +
어쩔 tv!

2023-09-14 12:53 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +    }
그쵸 사실 굉장히 귀찮은 것 같아요.. 이 부분은 추후에 의논을 통해서 해결해볼까요?

2023-09-14 13:10 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminQueryService.java
> +    }
> Service 계층이 Interceptor에 의존적인 것 같다는 생각이 듭니다.
이 부분 확실히 논의해야 할 부분인 것 같네요! 내일 얘기해보아요~

2023-09-14 13:48 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/application/OauthService.java
> +        throw new MemberForbiddenException(MemberErrorCode.FORBIDDEN_MEMBER_STATUS, member.getId());
<img width="700" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/50602742/18618a7d-3d1b-48e2-9de8-696d0a5329b9">

처음 써보셔서 수정하신게 더 웃긴데요

2023-09-15 05:07 UTC, yoondgu approved these changes
https://github.com/woowacourse-teams/2023-map-befine/pull/405#discussion_r1325590532
에 대한 논의는, 일단 변경 없이 가기로 이야기되었고 API 제공 후 고민할 수 있는 내용이라고 생각해서
approve 합니다!

2023-09-15 05:13 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminQueryService.java
> +        validateAdminPermission(admin);
해당 사항 반영했습니당 ~!

2023-09-15 05:48 UTC, junpakPark approved these changes
고생하셨습니다~!!

2023-09-15 05:54 UTC, merged

2023-09-15 05:58 UTC, kpeel5839 approved these changes
고생했어요 둥글레차