[BE] Feature/#399 내 정보(회원 닉네임) 수정 API 구현
woowacourse-teams/2023-map-befine pull request #408
Opened 2023-09-14 07:49 UTC by yoondgu

## 작업 대상

- 회원 닉네임 수정 API 구현
- 로컬 실행 환경용 더미데이터 설정 (+ 설정 파일 증가로 인해 로그 파일 디렉터리 분리)
- '유저', '멤버', '회원' 으로 분화된 도메인 용어를 '회원'으로 통일 

## 📄 작업 내용

회원 닉네임 수정 API를 구현하였는데,  
사실상 이를 **내 정보 수정 API**라고 보시면 될 것 같습니다.  
내 정보 수정 기능 중, 현재는 정책 상으로 닉네임 만 수정 가능하게 한 것이기 때문입니다.   
(다른 정보도 수정하게 될 시, 추후 body에 다른 필드들을 추가하면 됨)  

또 내 정보 수정의 경우, 모든 정보를 수정할 일은 없다고 판단해, PUT 대신 PATCH 로 진행했습니다.  
아래와 같은 이유 때문입니다.  

- Id, oauthId는 테이블에서 쓰는, 변하지 않는 정보
- Role은 내 정보 수정에서 스스로 바꿀 수 있으면 안됨
- 최대로 봐도 nickName, email, imageUrl만 변경 가능하다.

## 🙋🏻 주의 사항

## 스크린샷

## 📎 관련 이슈

 
closed #399

## 레퍼런스

2023-09-14 09:54 UTC, cpot5620 requested changes
고생하셨어요 !!

Approve 할까 하다가, request changes 합니다 ^_^ 히힛

2023-09-14 09:54 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +    }
커스텀 예외 `MemberNotFoundException` 구현하지 않았나요 !?

2023-09-14 09:54 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +
Patch라는 명명이 너무 API스러운 것 같아요.

흠.. 적절한 네이밍이 뭐가 있을까용

2023-09-14 09:54 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +    public ResponseEntity<Void> updateMyInfo(AuthMember authMember, @RequestBody MemberUpdateRequest request) {
`/my/profiles`라는 URL은 어떤가요 ?

2023-09-14 09:56 UTC, junpakPark requested changes
도이 코드 꼼꼼히 봐도 제 눈엔 흠이 잘 보이지 않네요!
메서드명 관련 질문 하나 남겼습니다!

2023-09-14 09:56 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
> +        memberInfo = memberInfo.createForPatch(nickName);
`createForPatch()`라는 네이밍은 Patch로 인해 `MemberInfo`가 새로 생성되었다는 의미이신가요?

2023-09-14 10:19 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +    }
https://github.com/woowacourse-teams/2023-map-befine/pull/405#discussion_r1325629065

쥬니 pr 코드리뷰로 남긴 내용과 연결되어서 링크로 남깁니다 !

2023-09-14 10:20 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +
ㅇㅈ합니다.. 고민해보고 수정할게요!

2023-09-14 10:22 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +    public ResponseEntity<Void> updateMyInfo(AuthMember authMember, @RequestBody MemberUpdateRequest request) {
이 부분은 쪼금 고민되는데 다른 분들 생각은 어떠신가요! @junpakPark @kpeel5839

2023-09-14 10:23 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
> +        memberInfo = memberInfo.createForPatch(nickName);
'부분 변경'의 의미로 patch 라는 단어를 썼는데, 쥬니 코멘트 대로 넘 api 의존적인 것 같아서 네이밍 수정해볼게요!

2023-09-14 10:27 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +    public ResponseEntity<Void> updateMyInfo(AuthMember authMember, @RequestBody MemberUpdateRequest request) {
my 자체가 유저 본인을 의미하는 거라 뒤에 뭔가 안 붙여줘도 될 것 같긴한데
뭔가 my가 저한테 좀 어색하게 느껴지긴하네여 ㅋㅋ

2023-09-14 10:56 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +    }
저 댓글이 이 의미였군요 이해했슴돠

2023-09-14 11:04 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberRepository.java
>      Optional<Member> findByMemberInfoEmail(String email);
만일 email 이 컬럼에서 빠지면 nickName 이 되어야 할 것 같네용

2023-09-14 11:05 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +    public ResponseEntity<Void> updateMyInfo(AuthMember authMember, @RequestBody MemberUpdateRequest request) {
음 저는 위 코드들과 일관성을 유지하기 위해서 쥬니 의견도 괜찮은 것 같아요

2023-09-14 11:06 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/dto/request/MemberUpdateRequest.java
> +}
또이 제가 지식이 부족해서 그럴 수도 있는데, 현재로서는 MemberUpdateRequest 에 컬럼이 하나인데 Dto 로 만드신 이유가 있을까요 ~ ?

2023-09-14 11:09 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProviderTest.java
> +
저 이 부분을 정확히 이해 못한 것 같아요!

PostMan 으로 테스트하기 위해서 더미데이터를 넣으시고, application.yml 을 수정하신 걸로 알고 있는데, 해당 createToken 테스트가 존재하는 이유가 무엇일까요?

PostMan 에서 사용할 Header 의 값을 쉽게 얻기 위해서 만드신건가요 ?

2023-09-14 11:13 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +
음 그리고 현재는 nickName 에 unique 제약 조건이 있어 DB 에 이미 존재하는 nickName 으로 사용자가 변경할 경우 예외가 터지겠지만, 그 예외가 DB 딴에서 터진다는 것이 조금 문제일 것 같아요!

프론트에서 사용자가 현재 입력한 nickName 이 이미 존재하는 nickName 이라는 것을 표현하기 위해서는 조금 더 친절한 예외가 발생해야 할 것 같아서요.

nickName 이 중복 되는지 검증하여, 중복된다면 예외를 던지는 방향은 어떠신가요?

2023-09-14 11:15 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberCommandServiceTest.java
> +}
제가 남긴 의견에 의해서 닉네임을 중복으로 수정하는 경우, 예외가 발생하는 경우도 테스트 해봐야 할 것 같은데

도이 생각은 어떠신가요?

2023-09-14 11:17 UTC, kpeel5839 commented
아따 intellij 로 코드리뷰 하는 거 쉽지 않네요. 계속해서 아무 말도 안쓰고 버튼을 눌러버려요.

리뷰는 간단하게 남겼습니다!

한번 읽어보시고 답변 달아주세요!

너무 고생하셨어요 도이!

역시 꼼꼼하시네요.

2023-09-14 12:13 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +    public ResponseEntity<Void> updateMyInfo(AuthMember authMember, @RequestBody MemberUpdateRequest request) {
과반수의 의견으로 /my/profiles 로 수정하겠습니다 ~~!!

2023-09-14 12:19 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/dto/request/MemberUpdateRequest.java
> +}
String으로 받을까도 고민했는데,  
Json 형식으로 된 RequestBody를 String으로 받으면  
직접 Json 파싱을 해줘야 하는 걸로 알고 있어서요! ("도이"를 받는 게 아니라 nickName 에 해당하는 값을 꺼내야 함)  
차라리 하나더라도 Dto로 받는 게 낫겠다고 판단했어요. 일관성도 있고요!  

하지만 혹시 다른 좋은 방법이 있을까요?!?

2023-09-14 12:21 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProviderTest.java
> +
> PostMan 에서 사용할 Header 의 값을 쉽게 얻기 위해서 만드신건가요 ?

맞습니당  
파악하기 어려운 버그가 생겼을 때는 급하게 PostMan을 해볼텐데 그럴 때 이 부분에서 번거로움이 있는 것 같아서요!  
사실 이번 PR과는 다소 무관한 커밋이지만.....ㅎㅎ  
테스트를 추가해야 하는 부분이기도 하고용

2023-09-14 12:25 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +
닉네임 중복 검증이 확실히 필요해보이네요 !! 추가하도록 하겠습니돠

2023-09-14 12:26 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberCommandServiceTest.java
> +}
동의합니다!! 중복 검증 추가하면서, 테스트도 작성하도록 할게요 ~!

2023-09-14 12:44 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +    // TODO 카카오에서 email 선택 동의라 체크 안하고 가입하면 DB에서 터질듯
저는 또 막상 이메일 자체를 빼거나 안받으려니(null) 고민스럽네요..    
저희가 가입한 사용자에게 연락할 수 있는 길이 전혀 없다는 점 때문이에요.  

그래서 다시 찾아보니 저희 카카오 API 계정을 비즈앱(사업자용)으로 변경하면 이메일 선택을 필수로 할 수 있네요....?!ㅎㅎ  
복잡한 검수가 필요한 줄 알았는데..  
그냥 이메일 필수로 만드는거 어때요?^.^하하  
![image](https://github.com/woowacourse-teams/2023-map-befine/assets/97426362/189477f4-755a-4338-8b80-11776c3c61ab)

2023-09-14 12:49 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +    // TODO 카카오에서 email 선택 동의라 체크 안하고 가입하면 DB에서 터질듯
그런게 있으면 바로 가야죵

2023-09-14 12:50 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/dto/request/MemberUpdateRequest.java
> +}
그런 이유가 있다면 충분히 킹득이 됩니다. 답변 감사해요~! 그냥 궁금했더연

2023-09-14 12:52 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +    public ResponseEntity<Void> updateMyInfo(AuthMember authMember, @RequestBody MemberUpdateRequest request) {
킹반수

2023-09-14 13:05 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +
준팍 의견으로 반영하겠습니다 ~!!

2023-09-14 16:33 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberRepository.java
>      Optional<Member> findByMemberInfoEmail(String email);
이 메서드 사용처를 봤는데, 테스트에서 생성한 Member를 찾는 경우라 findById 도 가능하더라고요.  
id를 모르는 경우에 필요한 쿼리가 아니라면, 최대한 기본키로 찾는게 좋을 것 같아서 findById로 바꿨습니다!!

2023-09-14 16:37 UTC, yoondgu commented
[리뷰 반영 커밋 범위](https://github.com/woowacourse-teams/2023-map-befine/pull/408/files/5ffb6cb2c8eed81ddefd2cc82895e49fd14172f2..4232fe20115eac227a44df3d6182c3d7dfd9b89a) 입니다.
PR 리뷰요청했을 때  
- 로그 환경설정 파일 디렉토리 분리
- 용어 정리
이 부분 커밋이 Push가 안되어있었어서 ㅠㅠ 지금은 Files Changed 에서 보시기 불편할거에요.

2023-09-14 16:44 UTC, kpeel5839 approved these changes
또이 고생하셨어요~~~!

근데.... 안 주무시나요..?

2023-09-14 16:44 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
> +        if (memberRepository.existsByMemberInfoNickName(nickName)) {
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

2023-09-14 16:44 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/exception/MemberErrorCode.java
> +    ILLEGAL_NICKNAME_ALREADY_EXISTS("05900", "이미 존재하는 닉네임입니다."),
👍👍👍👍👍👍👍👍👍👍👍👍👍

2023-09-14 16:44 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberCommandServiceTest.java
> +
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

2023-09-14 16:44 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +    @Column(nullable = false)
굉장히 좋은 의견이군요!

2023-09-14 16:44 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
> +                .replace("-", "")
오 replaceAll 이랑 기능은 똑같은데 성능이 더 좋군요! 처음 알았슴둥

2023-09-15 05:23 UTC, junpakPark approved these changes
메서드 변경 확인했습니다
수고 하셨어요~!!

2023-09-15 06:35 UTC, cpot5620 approved these changes
```
________                   ________                  .___   ________.__       .__   
\______ \   ____ ___.__.  /  _____/  ____   ____   __| _/  /  _____/|__|______|  |  
 |    |  \ /  _ <   |  | /   \  ___ /  _ \ /  _ \ / __ |  /   \  ___|  \_  __ \  |  
 |    `   (  <_> )___  | \    \_\  (  <_> |  <_> ) /_/ |  \    \_\  \  ||  | \/  |__
/_______  /\____// ____|  \______  /\____/ \____/\____ |   \______  /__||__|  |____/
        \/       \/              \/                   \/          \/                
```

2023-09-15 06:39 UTC, merged