[FE] Feat/#386 지도, 핀 이미지에 s3 적용
woowacourse-teams/2023-map-befine pull request #409
Opened 2023-09-14 07:50 UTC by GC-Park

## 작업 대상

지도, 핀 이미지에 s3 적용

## 📄 작업 내용

- 지도 생성 시 이미지 추가 s3로 구현
- 핀 생성 시 이미지 추가 s3로 구현
- 핀에 이미지 추가 s3로 구현

## 🙋🏻 주의 사항

## 스크린샷

## 📎 관련 이슈

 

## 레퍼런스

2023-09-14 16:25 UTC, semnil5202 requested changes
빠뚜릭~~ S3 구현하시느라 정말 고생 많았어요~~👍👍👍

덕분에 사용성이 정말 많이 개선 되겠군요 호호. 저 역시 file을 다루는 것은 한 번도 경험해보지 않았기 때문에 좀 꼼꼼하게 봤습니다. (그래서 좀 리뷰가 많아졌네요.. 🙃)

기능 구현 자체는 잘 되어있는 것 같아요. 하지만 네이밍이나 컨벤션 등 다소 아쉬운 부분이 있어 리퀘스트 요청 드립니다.

한 번 확인해주시고 이해가 잘 안 되거나 의견을 나눠보고 싶은 부분은 조금 이따 만나서 얘기나누면 좋을 것 같습니다. 고생하셨습니다!!

2023-09-14 16:25 UTC, semnil5202 commented on frontend/src/apis/postApi.ts
> +export const postFormApi = async (
이 api 요청 함수가 새로 만들어질 정도인지 잘 이해가 되지는 않아요. 결국 다른 부분은 payload가 컴포넌트 api 요청 로직단에서 stringify 되어와서 새로 만드신 것 같은데 가장 간단한 방법은 payload의 타입이 string인지 객체인지 판단하여 분기처리 할 수 있을 것 같습니다.

가장 좋은 방법은 stringify 를 이 레이어에서만 수행하도록 하는 것 같고요. 이 부분은 좀 이따 만나서 얘기해보시죵~

2023-09-14 16:25 UTC, semnil5202 commented on frontend/src/components/PinImageBox/index.tsx
> +const PinImageBox = ({ images }: PinImageBoxProps) => {
컴포넌트 분리 좋아용~ 👍👍 패트릭은 container 역할을 하는 컴포넌트를 Box라는 키워드를 쓰시는군요.

이 부분에 대해서도 컨벤션 이야기를 나눠봐야겠네요. 현재 List, Container, Box 이렇게 제각각인데 하는 역할은 동일해서요~~

2023-09-14 16:25 UTC, semnil5202 commented on frontend/src/pages/NewPin.tsx
> +  const formData = new FormData();
이 친구는 안쓰이는 것 같네용

2023-09-14 16:25 UTC, semnil5202 commented on frontend/src/pages/NewPin.tsx
> +    if (!formImages) return;
이 부분도 이미지는 필수값이 아니기 때문에 return 을 해주면 안 될 것 같아요. 그리고 formImages는 기본값이 빈 배열이라 위 로직은 영원히 false 일텐데요.

2023-09-14 16:25 UTC, semnil5202 commented on frontend/src/pages/NewPin.tsx
> +    const file = event.target.files && event.target.files[0];
imageLists 라는 변수를 선언해두었는데 왜 사용하지 않으시고 event.target 을 통해 타입 가드를 진행하셨을까요?

2023-09-14 16:25 UTC, semnil5202 commented on frontend/src/pages/NewPin.tsx
> +    if (!imageLists) return;
위에서 타입 가드를 진행하였는데 이곳에서 한 번더 진행하는 이유가 있나요?

2023-09-14 16:25 UTC, semnil5202 commented on frontend/src/pages/NewPin.tsx
> +  const [showImages, setShowImages] = useState<string[]>([]);
show 라고 동사를 쓰니 함수 네이밍 같은 느낌이 살짝 들어요~~ '화면에 있는', '보여진' 등의 명사의 느낌으로 네이밍 해보면 어떨까요?

2023-09-15 01:18 UTC, GC-Park commented on frontend/src/pages/NewTopic.tsx
> +      console.log('1');
아이고.. 콘솔 모두 지우도록 하겠습니다~!!

2023-09-15 01:22 UTC, GC-Park commented on frontend/src/components/PinImageBox/index.tsx
> +const ImageLi = styled.li`
저도 동의합니다~!! 수정하도록 하겠습니다!

2023-09-15 01:23 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +  const handlePinImageChange = (event: React.ChangeEvent<HTMLInputElement>) => {
아 맞네요! 알려주셔서 감사해요 세인! 바로 반영할게요 !! 👍

2023-09-15 01:26 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +  const handlePinImageChange = (event: React.ChangeEvent<HTMLInputElement>) => {
아 맞네요! 알려주셔서 감사해요 세인! 바로 반영할게요 !! 👍

2023-09-15 01:33 UTC, GC-Park commented on frontend/src/components/PinImageBox/index.tsx
> +const PinImageBox = ({ images }: PinImageBoxProps) => {
프로젝트 참고하니 대부분 Container로 되있는 것 같아서 일단 변경해두도록 하겠습니다~!!

2023-09-15 01:38 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +  const [showImages, setShowImages] = useState<string[]>([]);
좋습니다! 반영했습니다~!

2023-09-15 01:40 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +      showToast('error', 'No file selected');
세인 말에 공감합니다! 한국어로 변경하도록 하겠습니다!

2023-09-15 01:42 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +        '이미지 개수는 최대 8개까지만 선택 가능합니다. 다시 선택해 주세요.',
아 그냥 정보를 알려주는거니 info가 맞는 것 같습니다!! 👍

2023-09-15 01:45 UTC, GC-Park commented on frontend/src/pages/NewTopic.tsx
> +          {showImage && <ShowImage src={showImage} alt={`토픽 사진 대체`} />}
토픽이라는 단어 변경하도록 하겠습니다! 그리고 이거 변경하면서 다른 쪽에서도 쓰이던 토픽도 같이 변경했습니다~!

2023-09-15 01:51 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +    for (let i = 0; i < imageLists.length; i++) {
아 이 부분은 저도 javascript 처럼 작성하고 싶었으나 imageLists의 타입이 FileList | null 라서 forEach가 지원이 안 되더라구요! 그래서 for문으로 대체하였습니다!

2023-09-15 01:55 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +              style={{ display: 'none' }}
오히려 한 줄이라서 인라인으로 적었는데 생각해보니 저희가 정해둔 컨벤션에 맞게 수정하도록 하겠습니다!!

2023-09-15 02:12 UTC, afds4567 approved these changes
파일 추가 버튼이 생기면서 이미지 추가하는 기능이 메인 구현인거 같은데 세인이 남긴 컨벤션관련 제외하고 postApi부분만 하나로 합치면 좋을것 같아요 😄

2023-09-15 02:26 UTC, GC-Park commented on frontend/src/pages/NewTopic.tsx
> +      if (!formImage) return;
아! 이 부분에 대해서는 s3 구현할 때 생각하지 못했었네요..! 말씀해주셔서 감사합니다 세인!

고치도록 하겠습니다!

2023-09-15 02:36 UTC, GC-Park commented on frontend/src/pages/PinDetail.tsx
> +  }, [pinId, searchParams, pin]);
파일 업로드를 하면 이미지가 바로 렌더링 되지 않아 get을 다시 해오려고 추가 했었습니다. 

어제 pin을 넣었는데도 깜빡임이 발생하지 않아 무한 렌더링이 되지 않는다고 안일하게 판단한 것 같습니다! 

network 탭을 확인해보니무한 리렌더링에 빠지네요.. 허허 세인 알려주셔서 감사합니다!

파일을 업로드 하고 getPinData()를 실행해주는 방식으로 변경하였습니다!

2023-09-15 02:41 UTC, GC-Park commented on frontend/src/types/Pin.ts
> +export interface ImagesType {
저희 props로 통일인거 파일 다시 보고 확인했습니다! 컨벤션 잘 지키겠습니다 수정 완료 입니다!

2023-09-15 02:43 UTC, GC-Park commented on frontend/src/types/FormValues.ts
> +export interface DefaultFormProps {
음.. 아마 전에 있던 타입이고 이번에 새로 pull 땡겨오면서 충돌로 감지하지 않은 것 같아요! 

검색해보니 쓰고 있는 곳이 없어 지우도록 하겠습니다!

2023-09-15 02:45 UTC, GC-Park commented on frontend/src/apis/postApi.ts
> +  process.env.NODE_ENV === 'development'
아 그러기 위해 추가했었는데 지금은 필요없는 것 같아 지워도 될 것 같습니다! 수정할게요!!

2023-09-15 02:59 UTC, GC-Park commented on frontend/src/apis/postApi.ts
> +export const postFormApi = async (
합치는게 확실히 좋을 것 같습니다!! 수정하도록 하겠습니다~!!

2023-09-15 02:59 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +  const formData = new FormData();
오우 꼼꼼히 봐주셨네요! 굿 👍

2023-09-15 03:02 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +    if (!formImages) return;
이미지를 추가하면 setFormImages([...formImages, file]); 이라는 코드를 통해 빈 배열이 아닌 경우도 있습니다! 

그리고 핀 추가할 때도 이미지가 필수값이 아니기 때문에 수정이 필요하다는 생각이 듭니다!!

다양한 방법을 시도해 봤으나 blob 객체는 빈 값으로 보내지 못하는 것 같아 백엔드와 상의해서 방법을 찾아보도록 하겠습니다!

2023-09-15 03:16 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +    const file = event.target.files && event.target.files[0];
핀 이미지를 추가할 때는 여러개를 추가할 수 있도록 해두었고 파일을 올리는 즉시 볼 수 있도록 구현하였습니다. 이러는 과정에서 imageLists랑 file이 별개의 역할을 가진다고 생각했는데 세인의 리뷰를 보고 file이 없어도 된다는 것을 알았고 이미지를 여러개를 등록할 때 하나밖에 올라가지 않는 버그를 발견할 수 있었습니다!! 완전 👍👍

2023-09-15 03:17 UTC, GC-Park commented on frontend/src/pages/NewPin.tsx
> +    if (!imageLists) return;
수정하였습니다!

2023-09-15 11:44 UTC, kpeel5839 commented on frontend/src/pages/NewPin.tsx
> +      showToast('error', 'No file selected');
한국어로 쓰셨어야죠! 차아암...

2023-09-15 11:45 UTC, kpeel5839 commented on frontend/src/pages/NewPin.tsx
> +  const handlePinImageChange = (event: React.ChangeEvent<HTMLInputElement>) => {
on prefix 써줘요오오 차아아암

2023-09-15 11:46 UTC, kpeel5839 commented on frontend/src/pages/NewPin.tsx
> +    for (let i = 0; i < imageLists.length; i++) {
image List 말고 images 로 네이밍 부탁드릴게요 ~!

2023-09-15 11:47 UTC, kpeel5839 commented on frontend/src/pages/NewTopic.tsx
> +      if (!formImage) return;
아니요! 이미지를 선택하지 않았다면 아예 값이 안넘어오는게 좋을 것 같슴둥글레차

2023-09-15 11:47 UTC, kpeel5839 commented on frontend/src/pages/NewTopic.tsx
> +  const handleTopicImageFileChange = (
on 프리픽스 써달라구요

2023-09-15 11:47 UTC, kpeel5839 commented on frontend/src/pages/NewTopic.tsx
> +      console.log('No file selected');
console 좀 쓰고 지우라니까여어어

2023-09-15 11:48 UTC, kpeel5839 commented on frontend/src/pages/NewTopic.tsx
> +    console.log(formValues);
c.o.n.s.o.l.e

2023-09-15 11:48 UTC, kpeel5839 commented on frontend/src/pages/NewTopic.tsx
> +          {showImage && <ShowImage src={showImage} alt={`토픽 사진 대체`} />}
지도라고 해주시죠

2023-09-15 11:49 UTC, kpeel5839 commented on frontend/src/pages/PinDetail.tsx
> +    const getPinData = async () => {
세인 말투 너무 귀여웟

빠뚜릭 인덴트는 생명 ~ ^.^

2023-09-15 11:49 UTC, kpeel5839 commented on frontend/src/pages/PinDetail.tsx
> +  }, [pinId, searchParams, pin]);
오 이건 세인이 아주 잘 봐주셨네요

2023-09-15 11:49 UTC, kpeel5839 commented on frontend/src/pages/PinDetail.tsx
> +  const handlePinImageFileChange = async (
on 프리픽스 써달라구요 빠뚜릭..

2023-09-15 11:49 UTC, kpeel5839 commented on frontend/src/pages/PinDetail.tsx
> +      showToast('error', 'No file selected');
show toast 는 사용자에게 보인다구요..

2023-09-15 11:50 UTC, kpeel5839 commented on frontend/src/types/Pin.ts
> +export interface ImagesType {
이러면서 또 어기면! 엉덩이 때려버립니다.

2023-09-15 11:50 UTC, kpeel5839 commented on frontend/src/apis/postApi.ts
> +  process.env.NODE_ENV === 'development'
싸이코패스는요?

2023-09-15 11:51 UTC, kpeel5839 commented on frontend/src/apis/postApi.ts
> +export const postFormApi = async (
분기처리 시러잉

2023-09-15 11:51 UTC, kpeel5839 commented on frontend/src/components/PinImageBox/index.tsx
> +const PinImageBox = ({ images }: PinImageBoxProps) => {
Container 로 가시죠 Box 보다는 Container 가 간지 나잖아요

2023-09-15 11:52 UTC, kpeel5839 commented on frontend/src/pages/NewPin.tsx
> +  const formData = new FormData();
세인 visual studio code 이용해서 리뷰하시나요?

2023-09-15 11:53 UTC, kpeel5839 commented on frontend/src/pages/NewPin.tsx
> +    if (!formImages) return;
빈 배열이 아닌 경우도 있군요.

이미지는 필수로 넘어오게 되면 매번 동일한 사진이 S3 에 올라가기 때문에 굉장히 비효율적인 것 같습니다.

그래서 제가 그냥 이미지 파일을 넘기지 않으면 기본 이미지로 대체할 수 있도록 저장 로직을 변경하였습니다.

2023-09-15 11:54 UTC, kpeel5839 commented on frontend/src/pages/NewPin.tsx
> +    if (!imageLists) return;
타입 가드는 한번만 해버렷

2023-09-15 11:54 UTC, kpeel5839 commented on frontend/src/pages/NewPin.tsx
> +  const [showImages, setShowImages] = useState<string[]>([]);
패트릭은 파주 영어마을의 명물이기 때문에 네이밍을 잘 할 수 있어요.

2023-09-15 11:55 UTC, kpeel5839 commented on frontend/src/apis/postApi.ts
> +export const postFormApi = async (
아이크 댓글 한개!

2023-09-15 13:21 UTC, semnil5202 commented on frontend/src/pages/NewPin.tsx
> +    for (let i = 0; i < imageLists.length; i++) {
아하 유사배열인가보군요. FileList 는 처음 들어보네용. 우선은 for 문으로 안전하게 진행하는게 좋겠네요. 유사배열이라면 아래처럼 작성이 가능은 할거에요.

```js
[...imageLists].forEach()
```

2023-09-15 13:22 UTC, semnil5202 commented on frontend/src/pages/NewTopic.tsx
> +      if (!formImage) return;
ㅋㅋㅋㅋㅋㅋㅋㅋ매튜 심심해요?

2023-09-15 13:23 UTC, semnil5202 commented on frontend/src/types/Pin.ts
> +export interface ImagesType {
매튜 사심 채우지마용^_^

2023-09-15 13:26 UTC, kpeel5839 commented on frontend/src/pages/NewTopic.tsx
> +      console.log('1');
console

2023-09-15 13:27 UTC, semnil5202 commented on frontend/src/types/FormValues.ts
> +export interface DefaultFormProps {
엥 이 타입 아래처럼 다 사용하고 있는 것으로 알고 있어요. 지우면 안돼요!! 빠뚜릭!! 멈춰!!

<img width="454" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/89172499/df53a4c6-c829-40b2-a5d8-a6f1289ae14d">

<img width="374" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/89172499/2e17dd2b-3a80-4efe-be6e-00ab1d7d7c18">

제가 궁금했던 것은 머지 충돌로 인한 여파인가? 그런 종류입니다 ㅎㅎ

2023-09-15 13:27 UTC, kpeel5839 commented on frontend/src/pages/NewPin.tsx
> +    for (let i = 0; i < imageLists.length; i++) {
forEach 시러!

2023-09-15 13:28 UTC, kpeel5839 commented on frontend/src/pages/NewTopic.tsx
> +      if (!formImage) return;
이건 진심입니당 ~❤️

2023-09-15 13:29 UTC, kpeel5839 commented
패트릭 이 PR 보니까 Conflict 나네요 진짜 나 너무 화나!

2023-09-15 13:29 UTC, semnil5202 commented on frontend/src/apis/postApi.ts
> +export const postFormApi = async (
백은 분기처리 잘 안하나영?

2023-09-15 13:30 UTC, kpeel5839 commented on frontend/src/types/FormValues.ts
> +export interface DefaultFormProps {
빠뚜릭 멈춰!! 사랑스러운 빠뚜릮

2023-09-15 13:30 UTC, kpeel5839 commented on frontend/src/pages/NewPin.tsx
> +    if (!formImages) return;
이거도 따봉 눌러달라고요 세민씨

2023-09-15 13:31 UTC, semnil5202 commented on frontend/src/pages/NewPin.tsx
> +  const formData = new FormData();
처음에는 파일체인지로 쭉보다가 잘 이해가 안가는 부분 있으면 VSCode PR an Issue? 그 확장프로그램 써서 체크아웃해서 동시에 둘다 봐여~ 실제 화면 구동하면서

그래도 이해가 안 되면 마지막으로 커밋로그 보고 직접 물어보기~

2023-09-15 13:32 UTC, semnil5202 commented on frontend/src/pages/NewPin.tsx
> +    if (!formImages) return;
아하 빈 배열이 아닌 경우도 있군요! 굳 좝 베이비들 ❤️

2023-09-15 13:39 UTC, kpeel5839 commented on frontend/src/pages/NewPin.tsx
> +  const formData = new FormData();
당신 사랑스러워.

2023-09-15 13:40 UTC, semnil5202 approved these changes
오우 빠뜨릭 짧은 시간안에 다 수정하셨군요 고생많으셨습니다 👍👍

베리 나이스 하네용~ 추후 머지 충돌이 좀 걱정되긴 하지만.. ㅋㅋㅋㅋㅋ 저랑 같이 페어프밍해서 잘 해결해보시죠~~

월욜날 봬영 😀

2023-09-15 13:40 UTC, semnil5202 commented on frontend/src/apis/postApi.ts
> +  if (payload instanceof FormData) {
좋습니다 👍 중복 로직이 조금 있기는 한데 추후에 개선하면 충분할 것 같아요~~ 👍

2023-09-15 13:40 UTC, semnil5202 commented on frontend/src/types/FormValues.ts
> +export interface NewTopicFormProps {
아하 DefaultFormProps? 그 타입만 삭제하신 거군요 굳굳👍👍

2023-09-19 06:32 UTC, merged