[BE] Feature/#388 refresh token 및 로그아웃 기능 구현
woowacourse-teams/2023-map-befine pull request #411
Opened 2023-09-14 10:49 UTC by junpakPark

## 작업 대상

- [x] application.yml
- [x] Member 패키지
- [x] Oauth 패키지
## 📄 작업 내용

- [x] Refresh Token 적용
## 🙋🏻 주의 사항

- 테스트를 Mock으로 진행해서 불안합니다 눈에 띄는 로직 오류가 있다면 칼같이 잡아주세요!
## 스크린샷

## 📎 관련 이슈

 
closed #388 

## 레퍼런스

-  [행록: RefreshToken, AccessToken 이용한 로그인 기능 구현](https://github.com/woowacourse-teams/2023-hang-log/pull/404/files#top)
- [보투게더: 리프레시 토큰 기능(로그아웃 포함) 구현](https://github.com/woowacourse-teams/2023-votogether/pull/545/files#top)

2023-09-14 12:18 UTC, kpeel5839 requested changes

2023-09-14 12:18 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +    @PostMapping("/refresh-token")
`/refresh-token` api 는 프론트에서 access token 이 만료됨을 인지하고 요청을 보내 사용하는건가요?

2023-09-14 12:18 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java
> +        jwtTokenProvider.validateAccessToken(authInfo.accessToken());
👍👍👍👍👍👍👍👍

2023-09-14 12:18 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java
> +
RefreshToken 은 만료되고, AccessToken 은 만료되지 않은 경우를 방지하기 위해서 AccessToken 을 재발급할 때 RefreshToken 도 재발급 하는 것이 좋을 것 같다는 생각이 들어요!

준팍은 어떠신가요?

2023-09-14 12:18 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
>          return Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token).getBody().getSubject();
저희가 코드 짤 때 생활체조원칙을 지키지 못했군요 흠흠..

2023-09-14 12:18 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +    @PostMapping("/refresh-token")
그렇다면 프론트가 Access Token 이 만료되었는지 어떻게 확인할 수 있을까요?

2023-09-14 12:19 UTC, kpeel5839 commented
이 정도면 제가 학습 능력이 없군요.

또 바로 버튼을 눌러버렸습니다.

제 눈에는 리뷰할 부분이 크게 보이지 않아서 아주 조금의 의견 남겼습니다.

확인해주시고 의견 남겨주세요!

고생하셨어요 준파아악~!

2023-09-14 12:30 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java
> +
세부 정책은 다 같이 얘기해보면서 더 조율하면 좋을 것 같습니다.

> RefreshToken 은 만료되고, AccessToken 은 만료되지 않은 경우를 방지하기 위해서

해당 상황에서 매튜는 어떤 보안적 위험성이 있다고 판단하셨나요?

2023-09-14 12:48 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java
> +
보안적인 이유는 아니구요 access token 이 만료되지 않고 refresh token 이 만료된 상태의 유저가 활동을 하다가 access token 까지 마저 만료되었을 때 갑자기 로그인이 풀리고 다시 로그인 해야하는 플로우가 살짝 어색할 것 같아서요.

2023-09-14 12:52 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java
> +
[RTR 적용](https://hudi.blog/refresh-token/)하면 보안적으로나 UX적으로나 둘 다 챙길 수 있긴 할 것 같네요 ㅋㅋ

2023-09-14 12:53 UTC, cpot5620 requested changes
준팍 고생 많으셨습니다 !!

꼭 확인해보셔야 할 부분(Cookie 헤더 관련)이 있어서, request changes 하겠습니다 ㅎㅎ

2023-09-14 12:53 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/exception/AuthErrorCode.java
> +public enum AuthErrorCode {
허헛.. 저도 이거 만들었는데 충돌 나겠군요...

2023-09-14 12:53 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
> +    }
부정 조건문 지양 하는건 어떨까요 ?

예를 들어, 아래와 같이 수정할 수 있을 것 같아요 !

```java
    public void validateTokensForRemoval(String refreshToken, String accessToken) {
        boolean canRemoveRefreshToken = !isExpired(refreshToken) && !isExpired(accessToken);
        if (canRemoveRefreshToken) {
            return;
        }
        throw new AuthUnauthorizedException(EXPIRED_TOKEN);
    }
```

2023-09-14 12:53 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +    @DeleteMapping("/logout")
로그아웃 기능을 구현해본 적이 없어서 궁금해서 그런데 logout할 때, DeleteMapping을 사용하나요 ?
(진짜진짜모름)

2023-09-14 12:53 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +            @CookieValue("refresh-token") String refreshToken,
refreshToken에 대한 Max-Age는 프론트에서 인지할 필요가 없을까요 ?

필요 없을 것 같기도 하고... 있으면 좋을 것 같기도 해서요 ㅎㅎ

2023-09-14 12:53 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java
> +            authService.validateMember(memberId);
👍

2023-09-14 12:53 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/application/OauthService.java
> +    public LoginTokens login(OauthServerType oauthServerType, String code) {
생각해보니. OauthService에 `@Transactional` 어노테이션이 없었네요..

Query / Command Service로 분리할 필요가 없다면, 클래스 상단에 readOnly를 넣어주는 것은 어떨까요 ~?

2023-09-14 12:53 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/dto/LoginTokens.java
> +    }
해당 메서드는 불필요할 것 같다는 생각이 드는데요.

혹시 구현하신 이유가 따로 있을까요 ?

2023-09-14 12:53 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/presentation/OauthController.java
> +        response.addCookie(cookie);
Cookie 헤더는 exposedHeaders 안 해주어도 CORS 발생 안 하나요 ??

2023-09-14 12:55 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +    @DeleteMapping("/logout")
refresh token 지워서 delete 의 느낌이 나긴하네영

2023-09-14 12:56 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/presentation/OauthController.java
> +        response.addCookie(cookie);
지렸다

2023-09-14 12:57 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/application/OauthService.java
> +    public LoginTokens login(OauthServerType oauthServerType, String code) {
지금 당장은 Transactional이 필요한 메서드(= repository에 접근하난 메서드)가 하나뿐이라 이렇게 구현했습니다!
추후에 OauthService에 다른 메서드가 추가될 때 반영하는 건 어떠세요?

2023-09-14 12:58 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/exception/AuthErrorCode.java
> +public enum AuthErrorCode {
쥬니꺼 보고 아차했습니다 ㅋㅋ
조율해서 남길 것만 남겨요 ㅋㅋ

2023-09-14 12:59 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/presentation/OauthController.java
> +        response.addCookie(cookie);
이거 깜빡했네요 ㅋㅋ 감사합니다

2023-09-14 13:09 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +    @DeleteMapping("/logout")
매튜 의견처럼 생각해서 Delete 쓰긴 했는데
GPT는 뜬금없이 POST를 얘기하는군요..?

2023-09-14 13:18 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +    @DeleteMapping("/logout")
https://www.baeldung.com/logout-get-vs-post
벨덩에서도 POST를 권장하네요 !!

2023-09-14 13:21 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +    @DeleteMapping("/logout")
해당 링크 일부 내용입니다.

> In contrast, the RFC describes the POST method as one that can submit data (our session or session ID) to a data-handling process (logout). This is a more appropriate description of what we are trying to accomplish.  

> (번역) 이와 대조적으로, RFC에서는 POST 메서드를 데이터 처리 프로세스(로그아웃)에 데이터(세션 또는 세션 ID)를 제출할 수 있는 메서드로 설명합니다. 이것이 우리가 달성하고자 하는 바를 더 적절하게 설명합니다.

+ Spring Security에서도 기본적으로 로그아웃 요청을 POST로 받는다구 하네여

2023-09-14 13:31 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +    @DeleteMapping("/logout")
굿굿..!

2023-09-14 14:39 UTC, yoondgu requested changes
준팍 정말 수고 많으셨습니다 !! 🐼  
개인 리뷰가 늦어서 죄송합니다 ㅜㅜ   
다른 분들이 먼저 알차게 리뷰 해주셔서 제가 달 내용은 크게 많지 않지만요.  
아래 테스트 코드 관련 확인 먼저 하고서 리뷰 달려고 하다보니 늦어졌습니다 ㅜ  
https://github.com/woowacourse-teams/2023-map-befine/pull/411#discussion_r1326048808

깔끔하게 구현해주셔서 수월하게 확인할 수 있었어요. 감사합니다  
다만 
`로그아웃 Http 메서드를 POST로 변경`에 대해 request changes로 남길께요!!

추가로 만약 시간이 오래 걸리지 않는다면, 앞서 인용한 코멘트 부분도 검토해주시면 감사하겠습니다 ㅎㅎ  
하지만 Mock 제거가 어렵다는 건 너무 이해하기에.. 오래 걸릴 것 같다면 머지하고 실제 동작시키면서 확인해도 될 것 같아요

2023-09-14 14:39 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/auth/application/TokenServiceTest.java
> +    }
아래 코드처럼 하면 Mock을 쓰지 않고 테스트할 수 있을 것 같아서 
맞는지 먼저 확인해보고 제안드리는 게 맞는 것 같아서 테스트를  돌려봤는데요...  
일단 아래처럼 하면 빈, 설정값은 다 정상 주입되는 것 같아요.  

```java
@DataJpaTest
@Import(JwtTokenProvider.class)
@TestPropertySource(locations = "classpath:application.yml")
class TokenServiceTest {

    @Autowired
    private JwtTokenProvider jwtTokenProvider;
    @Autowired
    private RefreshTokenRepository refreshTokenRepository;
    @Autowired
    private MemberRepository memberRepository;

    private TokenService tokenService;
    private Member member;

    @BeforeEach
    void setUp() {
        member = memberRepository.save(MemberFixture.create("member", "member@gmail.com", Role.USER));
        tokenService = new TokenService(jwtTokenProvider, refreshTokenRepository);
    }

    @Test
    void reissueAccessToken_success() {
         // given
        String payload = String.valueOf(member.getId());
        // expired된 액세스 토큰을 만들기
        String accessToken = jwtTokenProvider.createToken(payload, 0L);
        String refreshToken = jwtTokenProvider.createRefreshToken();
        refreshTokenRepository.save(new RefreshToken(refreshToken, this.member.getId()));

        // when
        AccessToken result = tokenService.reissueAccessToken(refreshToken, accessToken);

        // then
        assertThat(payload).isEqualTo(jwtTokenProvider.getPayload(result.accessToken()));
    }
```
**하지만!!**
대신 테스트가 아래처럼 터집니다.  
제가 로직을 잘못 이해해서 테스트를 잘못 짠걸까요..? 🥹  
그래도 혹시 실제 작동에서 오류가 있는지 확인하거나, 테스트에서 mock을 제거하는데 도움이 되지 않을까 해서 코멘트로 남겨봅니다.  

![image](https://github.com/woowacourse-teams/2023-map-befine/assets/97426362/8c9d906c-18e3-4569-b7ca-cb488e5ca051)

2023-09-15 00:55 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
> +        final Date validity = new Date(now.getTime() + validityInMilliseconds);
아아앗...

2023-09-15 02:50 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
> +        final Date validity = new Date(now.getTime() + validityInMilliseconds);
적용했습니다

2023-09-15 02:51 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/auth/application/TokenServiceTest.java
> +    }
테스트 수정 완료했습니다.
우선 성공케이스에 대해서만 테스트 작성하였습니다

2023-09-15 03:05 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/auth/application/TokenServiceTest.java
> +    }
크 짱입니다 👍👍 확인했습니다 !!

2023-09-15 03:11 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/presentation/OauthController.java
> +        response.addCookie(cookie);
설정 완료했습니다

2023-09-15 03:11 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +            @CookieValue("refresh-token") String refreshToken,
설정 완료했습니다

2023-09-15 03:11 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/AuthController.java
> +    @DeleteMapping("/logout")
설정 완료했습니다

2023-09-15 03:13 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
> +    }
설정 완료했습니다

2023-09-15 03:18 UTC, yoondgu approved these changes
수고 많으셨습니다 준팍 !!

2023-09-15 03:26 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/dto/LoginTokens.java
> +    }
Pn으로 따졌을 때 몇정도신가요? P4이하라면 그냥 이대로 가겠습니당 ㅋㅋ

2023-09-15 06:37 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/dto/LoginTokens.java
> +    }
P 99였습니다 ㅋ

2023-09-15 06:38 UTC, cpot5620 approved these changes
```
___________                __             ________                  .___
\__    ___/____    _______/  |_  ____    /  _____/  ____   ____   __| _/
  |    |  \__  \  /  ___/\   __\/ __ \  /   \  ___ /  _ \ /  _ \ / __ | 
  |    |   / __ \_\___ \  |  | \  ___/  \    \_\  (  <_> |  <_> ) /_/ | 
  |____|  (____  /____  > |__|  \___  >  \______  /\____/ \____/\____ | 
               \/     \/            \/          \/                   \/ 
```

2023-09-15 07:06 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java
> +
RTR 적용 완료하였습니다.
적용하면서, OauthController와 AuthController 통합 후 LoginController로 네이밍 변경,
OauthService와 TokenService 역할과 책임 재분배하였습니다.

2023-09-15 07:28 UTC, yoondgu requested changes
클래스 분리가 한층 깔끔해져서 좋네요!! 감사합니당 준팍  
displayName이 누락된 곳이 몇 곳 있어서 P2로 몇 개 남겼습니다.
P4는 원하시면 반영해주세요 ~

2023-09-15 07:28 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/auth/application/TokenServiceTest.java
> +    @DisplayName("")
P2. 빈 DisplayName 검거 😎

2023-09-15 07:28 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/auth/presentation/LoginControllerTest.java
> +    void reissueTokens() throws Exception {
P2. DisplayName이 없어요 !

2023-09-15 07:28 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/auth/presentation/LoginControllerTest.java
> +    void logout() throws Exception {
얘두용

2023-09-15 07:28 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
> +    }
```java
        Cookie refreshTokenCookie = createCookie(loginTokens.refreshToken());
        response.addCookie();

        return ResponseEntity.ok(new LoginInfoResponse(loginTokens.accessToken(), memberDetail));
    }

    private Cookie createCookie(String refreshToken) {
        Cookie cookie = new Cookie("refresh-token", refreshToken);
        cookie.setHttpOnly(true);
        cookie.setMaxAge(14 * 24 * 60 * 60);
        return cookie;
    }

```

P4. 이렇게 하는건 어떨까용?? response에 addCookie하는 게 눈에 더 잘 들어오면 좋을 것 같아요 !

2023-09-15 07:46 UTC, cpot5620 requested changes
고생하셨어요 준팍  !!

Mock 테스트로 짜서 불안하다고 말씀해주셨는데, E2E 테스트는 구현할 수 없나여 ?

2023-09-15 07:46 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/TokenProvider.java
> +public interface TokenProvider {
👍

2023-09-15 07:46 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
> +        cookie.setMaxAge(14 * 24 * 60 * 60);
이게 어느정도의 시간을 의미하는지 잘 모르겠는데, 상수로 추출하는 것은 어떨까요 ?

2023-09-15 07:46 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
> +        cookie.setMaxAge(14 * 24 * 60 * 60);
14일인건 느낌적으로 알긴 하지만 ㅎㅎ

2023-09-15 07:46 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/common/TestAuthHeaderProvider.java
refresh Token은 generate하지 않나요 ?

메서드 명에 어떤 토큰을 생성하는지 나타나지 않고 있는 것 같아서요 !

2023-09-15 07:54 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/auth/application/TokenServiceTest.java
> +    @DisplayName("")
반영했습니다

2023-09-15 07:54 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/auth/presentation/LoginControllerTest.java
> +    void reissueTokens() throws Exception {
반영했습니다

2023-09-15 07:54 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/auth/presentation/LoginControllerTest.java
> +    void logout() throws Exception {
반영했습니다

2023-09-15 07:54 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
> +    }
반영했습니다

2023-09-15 07:56 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/dto/LoginTokens.java
> +    }
귀요미 ㅋㅋ

2023-09-15 07:57 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
> +        cookie.setMaxAge(14 * 24 * 60 * 60);
적용했습니당ㅋㅋ

2023-09-15 08:02 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/oauth/application/OauthService.java
> +    public LoginTokens login(OauthServerType oauthServerType, String code) {
TokenService와의 책임과 역할 재분배 후 해당 서비스 내 `@Transactional` 어노테이션 모두 제거했습니다

2023-09-15 08:03 UTC, kpeel5839 approved these changes
야무집니다 준팍~!

나머지 분들이 야무지게 남겨주셔서 저는 작은 피드백 드렸습니다~!

고생하셨더연!

2023-09-15 08:03 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java
> +    }
issueTokens() 랑 위치가 바뀌었으면 좋겠네요!

2023-09-15 08:03 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
> +        return ResponseEntity.ok(loginTokens.toAccessToken());
👍👍👍👍👍👍👍👍👍👍

2023-09-15 08:04 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java
> +    }
`issueTokens()`도 퍼블릭 메서드이고, LoginController에서도 사용중이기 때문에 현재처럼 배치했습니당ㅋㅋ

2023-09-15 08:07 UTC, yoondgu approved these changes
변경 요청에 대한 반영 확인했으므로, approve 부터 남기도록 할게요! 수고하셨슴다

2023-09-15 08:46 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/TokenService.java
> +    }
흠 그렇군요.

Token Service 만 봤을 때에는 reissueToken() 이 issueTokens() 메서드를 사용해서 헷갈렸던 것 같아요~

위와 같은 이유라면 현재 배치가 더 나을 것 같네용

2023-09-15 10:32 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/common/TestAuthHeaderProvider.java
적용했습니당~!!

2023-09-17 03:37 UTC, cpot5620 approved these changes
고생하셨습니다 준팍 ~ 

질문 하나 남겨두었는데, 확인 부탁드리고 approve 하도록 하겠습니다.

2023-09-17 03:37 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
> +                .build();
제가 이해한 것이 맞다면, Cookie로 refresh token만 넘겨주는 것 같아요.
access-token은 body에 값을 담아서 넘겨주는 것 같은데, 이런 구조를 가진 이유가 있을까요 ?

둘 다 Cookie로 넘겨주거나 / 둘 다 body로 넘겨주는 방법이 있을 것 같아서요 ~! 
말씀해주셨는데, 제가 놓친 부분이 있었을 수도 있어서 ㅎㅎ 다시 한 번 답변 부탁드립니당

2023-09-17 03:43 UTC, merged

2023-09-17 04:15 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
> +                .build();
각 토큰의 특성과, 탈취되었을 때의 위험성을 생각해서 지금과 같이 나눴습니당!
그리고 저장 장소를 이원화하면, 한번에 두개의 토큰이 모두 털릴 위험성을 방지할 수 있을 것으로 기대하고 있습니다.

리액트가 access token을 response body로 받은 후, local storage에 저장하면서
리액트로 XSS 공격을 일차적으로 막아주고, local Storage에서 CSRF 취약점을 막고자 했습니다.
local storage 저장 이후의 xss 공격에 대해서는 토큰 자체의 만료기간을 짧게 둠으로써 막고자 합니다.

RefreshToken의 경우 가지고 있으면 새로 AccessToken을 발급받을 수 있다는 문제가 있기 때문에
HTTPOnly와 Secure, SameSite 플래그가 있는 쿠키에 저장하여 CSRF 취약점을 막았습니다.

[레퍼런스](https://tecoble.techcourse.co.kr/post/2021-10-20-refresh-token/)