Refactor/#406
woowacourse-teams/2023-map-befine pull request #412
Opened 2023-09-14 18:29 UTC by yoondgu

## 작업 대상

## 📄 작업 내용

## 🙋🏻 주의 사항

## 스크린샷

## 📎 관련 이슈

 

## 레퍼런스

2023-09-14 18:50 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/permission/presentation/PermissionController.java
> +        PermissionMemberDetailResponse response = permissionQueryService.findPermissionById(permissionId);
이 메서드명 변경은 실수로 바꾸고 커밋한 겁니다 ,,  
지금 바꿀 대상은 아닌 것 같아서 원래로 복구시켰습니다 ([해당 커밋](https://github.com/woowacourse-teams/2023-map-befine/pull/412/commits/e60fa9c9c258456bb7a709c45a7fc24decd27e90))

2023-09-15 00:37 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +    @Column(nullable = false)
email은 nullable하더라도 unique 하면 더 좋지 않을까요?

2023-09-15 00:41 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java
> +        /// TODO: 2023/09/15 이럴거면 topic.getPermissions 로 하는 게 나을 수도 있나? TopicController 에서 하는 게 더 자연스러운 것 같기도..
저도 TODO처럼 생각합니당
Topicdetail을 볼 때 TopicAccessDetailResponse이 그 안에 들어가있는게 자연스러울 것 같아요!

2023-09-15 00:42 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +    @Column(nullable = false)
아 이 부분은 #408 PR에 해당되는 커밋인데요! 커밋에만 적고 자세히 말씀을 못드렸네용  
아래와 같은 이유로 변경했는데 어떻게 생각하시나요??![image](https://github.com/woowacourse-teams/2023-map-befine/assets/97426362/6250e9fd-b56d-4121-a1b8-32ef3fc944c8)

2023-09-15 00:45 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/permission/domain/Permission.java
> +    // TODO 매핑 테이블인데 Id를 가져야 할까?
저도 [값타입 컬렉션 - map](https://www.youtube.com/watch?v=CPIgicoqLnM)을 써보는 건 어떨까 생각하긴 했어요 ㅋㅋ

2023-09-15 00:47 UTC, junpakPark requested changes
p2 확인 부탁드립니다!

2023-09-15 00:49 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +    @Column(nullable = false)
저는 2번째 경우는 두번째 회원 가입을 막아야한다고 생각하긴 했어요!
아이디가 다중으로 필요한 경우는 보통 어뷰저일 가능성이 높다고 생각해서요 ㅋㅋ
(차단을 당했거나, 여러 아이디로 분란을 조장하거나 등등)

2023-09-15 01:13 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +    @Column(nullable = false)
@cpot5620 @kpeel5839  의견은 어떠신가요??

2023-09-15 01:30 UTC, kpeel5839 approved these changes
따로 변경사항으로 의견 드릴 것은 없더라고요!

고생하셨습니다 또이또이!

2023-09-15 01:51 UTC, cpot5620 approved these changes
고생하셨슴둥글레차

2023-09-15 01:51 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/permission/dto/response/PermissionedMemberResponse.java
> +public record PermissionedMemberResponse(
Permission은 명사 아니에여 ????!?!!??!?

2023-09-15 01:51 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/permission/presentation/PermissionController.java
> +    //  회원 정보 조회는 /members 에서 하는 걸로 충분하지 않나? 재사용성이 떨어진다. 테스트의 DisplayName도 매칭이 안된다.
프론트에서도 사용하지 않고 있다면, 굳이.... 존재할 필요가 없을 것 같아요

2023-09-15 01:51 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java
> +        /// TODO: 2023/09/15 이럴거면 topic.getPermissions 로 하는 게 나을 수도 있나? TopicController 에서 하는 게 더 자연스러운 것 같기도..
저두요 ~!~!

2023-09-15 01:53 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
> +    @Column(nullable = false)
저도 unique할 필요는 없다고 생각해요 !!!!!!

만약, unique하게 갈거라면 어떤 OAuth로 연동되어있는지도 알려주는 기능이 필요할 것 같아요.

2023-09-15 03:11 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/permission/dto/response/PermissionedMemberResponse.java
> +public record PermissionedMemberResponse(
그냥 생각없이 ed 붙여보고 직관적인 것 같고 deepL에서 잘 해석되길래 쓰긴 했는데 ㅋㅋㅋ 어색한가용..?

2023-09-15 05:10 UTC, junpakPark approved these changes

2023-09-15 07:11 UTC, merged