[BE] Fix/#426 Token CORS 재설정
woowacourse-teams/2023-map-befine pull request #427
Opened 2023-09-17 10:26 UTC by junpakPark

## 작업 대상

- [x] loginController
- [x] webConfig

## 📄 작업 내용

- [x] Credentials 재설정
- [x] allowHeaders 쿠키 추가
- [x] sameSite None 설정
 
## 🙋🏻 주의 사항

## 스크린샷

## 📎 관련 이슈

 
closed #426 

## 레퍼런스

2023-09-17 13:32 UTC, yoondgu requested changes
주말에도 수고 많으셨습니다 준팍 !!
지난 PR에 더불어서 설정값 변경 이유를 PR에 설명해주시면 좋을 것 같아요 ~!
기존 코드 리뷰에서 제가 놓친 부분이긴 한데 궁금한 것 하나 남겨놨습니다
설명받으면 바로 approve 하겠습니다!

2023-09-17 13:32 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
> +                .sameSite("None")
이 설정은 어떤 건가용??  
기존 코드 리뷰에서 질문을 드렸어야 하는데 죄송합니다. 자세히 못봤네요 ..

2023-09-18 00:11 UTC, kpeel5839 approved these changes
코드리뷰 요청하실 때 자세히 설명해주셔서 읽으면서 바뀐 설정들이 무엇을 의미하는지 수월하게 알 수 있었습니다~!

고생하셨어요 준팍~~~

2023-09-18 00:59 UTC, cpot5620 approved these changes
고생하셨스빈당 ~~

2023-09-18 03:26 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/auth/presentation/LoginController.java
> +                .sameSite("None")
[sameSite](https://velog.io/@seowj0710/Cookie-SameSite-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0) 관련 설명입니다.

간단하게 요약하자면, SameSite 속성으로 서로 다른 도메인간의 쿠키 전송에 대한 보안을 설정하는데요.

None: 쿠키는 모든 요청에 대해 전송되며, 서드 파티 쿠키를 허용
단, 2020년 이후로는 SameSite=None 설정시 Secure 플래그도 함께 설정해야만 합니다 (쿠키는 HTTPS 연결만을 통해 전송됩니다).

Lax: Strict 설정에 일부 예외(HTTP GET method/a href/link href)를 두어 적용되는 설정입니다.
Lax 설정은 사용자가 사이트간 상호 작용을 하지 않을 때 쿠키 유출을 방지하는 데 유용합니다.

Strict: 이 설정은 쿠키가 같은 사이트에서 생성된 요청을 통해서만 서버에 전송됩니다. 이는 CSRF 공격을 막는데 효과적이지만, 사용자가 서로 다른 사이트 간에 쉽게 네비게이션 할 수 없게 만들어 사용자 편의성을 저해할 수 있습니다.

2023-09-18 04:17 UTC, merged