[BE] S3 를 통한 Image Upload 기능 구현
woowacourse-teams/2023-map-befine pull request #428
Opened 2023-09-17 12:01 UTC by kpeel5839

## 작업 대상

Image 를 Upload 하는 API 수정

## 📄 작업 내용

- POST /pins (핀 생성과 함께 Image 리스트를 받을 수 있도록 수정)
- POST /pins/images (Pin 에 단일 이미지를 추가하는 기능)
- POST /topics/new 
- POST /topics/merge

1. 기존에 위 API 들 모두 String 으로 Image URL 을 받고 있었는데, 해당 부분을 `MultipartFile` 를 받을 수 있도록 수정
2. 받은 MultipartFile 을 AWS S3 2023/team-projects/2023-map-be-fine/(dev, prod) 에 upload
3. cloud front url + "/" + 생성한 image name 으로 DB 에 Image URL 저장
4. DB 에 저장된 Image URL 로 S3 에 올라가 있는 Image 로 접근가능

이 이외에 이해가 안되는 부분이 있다면 질문 남겨주시면 감사할 것 같아요!

## 🙋🏻 주의 사항

여러분들! 제가 revert 와 cherry-pick 을 이용해서 S3 관련해서 변경사항을 이번 PR 에 담아보려 했는데, 잘 안되네요 ㅠㅠ

죄송합니다 ㅠㅠ

대신 중요 코드들에 대해서는 본문에다가 남기도록 하겠습니다.

불편을 끼쳐드려 죄송합니다.

# 중요 코드

### 의존성 추가
```gradle
implementation platform('com.amazonaws:aws-java-sdk-bom:1.11.1000')
implementation 'com.amazonaws:aws-java-sdk-s3'
```

이번에 s3 를 위해서 추가한 의존성이에용

### S3 에 접근하기 위해 필요한 Bean 등록
```java
@Bean  
public InstanceProfileCredentialsProvider instanceProfileCredentialsProvider() {  
    return InstanceProfileCredentialsProvider.getInstance();  
}  
  
@Bean  
public AmazonS3 amazonS3() {  
    return AmazonS3ClientBuilder.standard()  
            .withRegion(Regions.AP_NORTHEAST_2)  
            .withCredentials(instanceProfileCredentialsProvider())  
            .build();  
}
```

S3 에 접근하기 위해 필요한 빈을 등록 및 설정하는 코드입니다.

### 기존 코드의 변경을 최소화하고 Image 를 받기 위해 변경한 DTO 

제가 S3 업로드 기능 구현을 진행하면서 처음으로 문제를 맞닥뜨렸던 부분은, MultipartFile 을 한 객체에 포함시켜서 받을 수 없다는 점이었는데요.

아래와 같은 상황을 예로 들 수 있을 것 같아요.

```java
public record TopicCreateRequest(  
        String name,  
		MultipartFile image,
        String description,  
        Publicity publicity,  
        PermissionType permissionType,  
        List<Long> pins  
) {  
}
```

그렇기 때문에 Dto 에서 image 를 빼고 Controller 에서 직접 MultipartFile 을 받는 방법밖에 없었어요.

그래서 아래와 같이 새로운 TopicCreateRequestWithoutImage 와 같은 DTO 를 만들어  TopicCommandService, PinCommandService 의 `saveTopic`, `addImage` 파라미터를 변경하지 않는 방법으로 진행했어요

- Topic 저장
```java
public record TopicCreateRequestWithoutImage(  
        String name,  
        String description,  
        Publicity publicity,  
        PermissionType permissionType,  
        List<Long> pins  
) {  
}
```

```java
@LoginRequired  
@PostMapping( // MultipartFile 과 Json 을 한번에 받기 위해서 Consume 을 해당 방법으로 지정해야 했습니다.
        value = "/new",  
        consumes = {MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE}  
)  
public ResponseEntity<Void> create(  
        AuthMember member,  
        @RequestPart TopicCreateRequestWithoutImage request,  
        @RequestPart(required = false) MultipartFile image  
) {  
    TopicCreateRequest topicCreateRequest = TopicCreateRequest.of(request, image);  
    Long topicId = topicCommandService.saveTopic(member, topicCreateRequest);  
  
    return ResponseEntity.created(URI.create("/topics/" + topicId))  
            .build();  
}
```

- Pin 에 이미지 추가
```java
@LoginRequired  
@PostMapping(  
        value = "/images",  
        consumes = {MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE}  
)  
public ResponseEntity<Void> addImage(  
        AuthMember member,  
        @RequestPart Long pinId,  
        @RequestPart(required = false) MultipartFile image  
) {  
    pinCommandService.addImage(member, new PinImageCreateRequest(pinId, image));  
  
    return ResponseEntity.status(HttpStatus.CREATED).build();  
}
```

### S3 에 이미지를 upload 를 하기 위해 필요한 클래스들

- S3 Service
```java
@Service
public interface S3Service { 
// Test 환경에서는 다른 Component 를 띄워 실제 S3 에 접근하지 않기 위해 interface 를 만들었습니다.

    String upload(MultipartFile multipartFile);

}
```

- 테스트에서 사용되는 S3 Service 구현체
```java
@Service
@Profile("test")
public class TestS3ServiceImpl implements S3Service {

    @Override
    public String upload(MultipartFile multipartFile) { // 그냥 String 만 반환하도록 했습니다.
        return "https://mapbefine.github.io/favicon.png";
    }

}
```

- 실제 Service 에 사용되는 S3Service 구현체
```java
@Service
@Profile("!test")
public class S3ServiceImpl implements S3Service {

    @Value("${prefix.upload.path}") // prefix.upload.path 는 private repo 에서 확인 부탁드려요
    private String prefixUploadPath;
    private final S3Client s3Client;

    public S3ServiceImpl(S3Client s3Client) {
        this.s3Client = s3Client;
    }

    @Override
    public String upload(MultipartFile multipartFile) {
        try {
            UploadFile uploadFile = UploadFile.of(multipartFile);
            s3Client.upload(uploadFile);
            return getUploadPath(uploadFile);
        } catch (IOException exception) {
            throw new RuntimeException(exception);
        }
    }

    private String getUploadPath(final UploadFile uploadFile) {
        return String.join(
                "/",
                prefixUploadPath,
                uploadFile.getOriginalFilename()
        );
    }

}
```

- S3 Client (실제로 S3 에 업로드를 진행하는 부분입니다.)
```java
@Component  
public class S3Client {  
  
    @Value("${s3.bucket}")  
    private String bucket;  
    private final AmazonS3 amazonS3;  
  
    public S3Client(AmazonS3 amazonS3) {  
        this.amazonS3 = amazonS3;  
    }  
  
    public void upload(MultipartFile multipartFile) throws IOException {  
        File tempFile = null;  
  
        try {  
            tempFile = File.createTempFile("upload_", ".tmp");  
            multipartFile.transferTo(tempFile);  
            amazonS3.putObject(new PutObjectRequest(  
                    bucket,  
                    multipartFile.getOriginalFilename(),  
                    tempFile  
            ));  
        } catch (IOException exception) {  
            throw new IOException(exception);  
        } finally {  
            removeTempFileIfExists(tempFile);  
        }  
    }  
  
    private void removeTempFileIfExists(File tempFile) {  
        if (!Objects.isNull(tempFile) && tempFile.exists()) {  
            tempFile.delete();  
        }  
    }  
  
    public void delete(String key) {  
        // 현재는 일단 기능만 만들어놓고, API 는 만들어놓지 않았습니다 회의를 통해서 결정해야 할 사항이 있는 것 같아서요!  
        amazonS3.deleteObject(new DeleteObjectRequest(bucket, key));  
    }  
  
}
```

- MultipartFile 을 구현하여, 이름을 커스터마이징합니다. (사용할 필요가 없는 Override 된 메서드들은 고정된 값을 반환하도록 하였습니다.)
```java
public class UploadFile implements MultipartFile {

    private final String fileName;
    private final byte[] bytes;

    private UploadFile(
            String fileName,
            byte[] bytes
    ) {
        this.fileName = fileName;
        this.bytes = bytes;
    }

    public static UploadFile of(
            MultipartFile multipartFile
    ) throws IOException {
        ImageName imageName = ImageName.from(multipartFile.getOriginalFilename());
        byte[] multipartFileBytes = multipartFile.getBytes();

        return new UploadFile(imageName.getFileName(), multipartFileBytes);
    }

    @Override
    public String getName() {
        return fileName;
    }

    @Override
    public String getOriginalFilename() {
        return fileName;
    }

    @Override
    public String getContentType() {
        return null;
    }

    @Override
    public boolean isEmpty() {
        return false;
    }

    @Override
    public long getSize() {
        return 0;
    }

    @Override
    public byte[] getBytes() throws IOException {
        return bytes;
    }

    @Override
    public InputStream getInputStream() throws IOException {
        return new ByteArrayInputStream(bytes);
    }

    @Override
    public Resource getResource() {
        return MultipartFile.super
                .getResource();
    }

    @Override
    public void transferTo(File dest) throws IOException, IllegalStateException {
        try (FileOutputStream fileOutputStream = new FileOutputStream(dest)) {
            fileOutputStream.write(bytes);
        }
    }

}
```

- Image 이름은 DateTimeFormatter 를 이용합니다! (현재시각을 정해진 양식으로 치환 후, 확장자를 붙여 반환)
```java
public class ImageName {  
  
    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyyMMddHHmmssSSSSSS");  
  
    [...]

2023-09-17 16:44 UTC, yoondgu commented
전체 코드 흐름 파악, 아래에 주신 질문 읽고 전체적인 리뷰 먼저 코멘트로 남겨둡니다!
코드에 대한 리뷰는 내일 아침에 진행할게용

## 구현 내용 관련 질문
1. 서비스 메서드의 시그니처를 유지해야 하는 이유가 있을까용? `TopicCreateDtoWithOutImage` -> `TopicCreateDto` 이렇게 Dto에 depth가 있는 게 조금 어색하게 느껴져서요! Dto는 하나만 사용하고, Service에서 MultipartFile을 직접 받으면 안되나요?!

2. S3는 이미지를 저장하기 위한 기술의 이름인데, 상위 패키지명, 인터페이스명에 쓰이는 게 조금 어색한 것 같아요.  
아래와 같은 네이밍은 어떨까요?
```
패키지명: image
인터페이스: ImageService
구현체: S3ImageService
테스트 구현체: TestImageService
```

## 의논 사항 답변
1. DB에 URL 저장 vs fileName 저장
	- 아래 기존 데이터 이관을 하고 나면 fineName에 제시해준 단점이 모두 사라질 것 같아요.
	- 그렇다면 기존 데이터 이관을 전제로, fileName 을 저장하는 게 어떨까요?
	-  URL을 저장하면, (그럴 일은 잘 없겠지만) 저희의 이미지 저장소가 바뀐다면 그 때 또 DB 데이터에 쓰인 URL도 다 수정해줘야 하는 단점도 있을 것 같아요.
	- 대신 그러면 MemberInfo에서 쓰는 Image 클래스만 따로 분리해야 할 것 같아요.

2. DB에 저장된 기존 이미지 URL은 S3 URL이 아닌 문제
    기존 데이터 이관 쪽에 동의합니다! 아래처럼 하면 어떨까용
	- 개발 서버 이미지는 유의미한 데이터가 아니니 모두 S3에 저장된 기본 이미지를 바라보도록 PinImage UPDATE 쿼리 날리기
	- 운영 서버 이미지는 기존 데이터를 S3에 이관, DB에 저장된 컬럼 값 수정

- 이미지 삭제
	- PinImage는 Pin이 여러 이미지를 가지기에 존재하는 매핑 테이블로, pin_id 컬럼도 있어서 URL에 따라 하나로 묶는 건 어렵지 않을까요?  삭제 시에는
	
```
1. PinImage 테이블에, 동일한 URL(또는 파일명)를 가진 레코드가 있는지 확인한다.
2. 있으면, 테이블 레코드만 지운다.
3. 없으면, 테이블 레코드도 지우고 S3에도 이미지 삭제 요청을 한다.
```

이렇게 하는 건 어떨까요?

2023-09-18 00:05 UTC, kpeel5839 commented
> 전체 코드 흐름 파악, 아래에 주신 질문 읽고 전체적인 리뷰 먼저 코멘트로 남겨둡니다! 코드에 대한 리뷰는 내일 아침에 진행할게용
> 
> ## 구현 내용 관련 질문
> 1. 서비스 메서드의 시그니처를 유지해야 하는 이유가 있을까용? `TopicCreateDtoWithOutImage` -> `TopicCreateDto` 이렇게 Dto에 depth가 있는 게 조금 어색하게 느껴져서요! Dto는 하나만 사용하고, Service에서 MultipartFile을 직접 받으면 안되나요?!
> 2. S3는 이미지를 저장하기 위한 기술의 이름인데, 상위 패키지명, 인터페이스명에 쓰이는 게 조금 어색한 것 같아요.
>    아래와 같은 네이밍은 어떨까요?
> 
> ```
> 패키지명: image
> 인터페이스: ImageService
> 구현체: S3ImageService
> 테스트 구현체: TestImageService
> ```
> 
> ## 의논 사항 답변
> 1. DB에 URL 저장 vs fileName 저장
>    
>    * 아래 2번 항목의 기존 데이터 이관을 하고 나면 fineName에 제시해준 단점이 모두 사라질 것 같아요.
>    * 그렇다면 기존 데이터 이관을 전제로, fileName 을 저장하는 게 어떨까요?
>    * URL을 저장하면, (그럴 일은 잘 없겠지만) 저희의 이미지 저장소가 바뀐다면 그 때 또 DB 데이터에 쓰인 URL도 다 수정해줘야 하는 단점도 있을 것 같아요.
>    * 대신 그러면 MemberInfo에서 쓰는 Image 클래스만 따로 분리해야 할 것 같아요.
> 2. DB에 저장된 기존 이미지 URL은 S3 URL이 아닌 문제
>    기존 데이터 이관 쪽에 동의합니다! 아래처럼 하면 어떨까용
>    
>    * 개발 서버 이미지는 유의미한 데이터가 아니니 모두 S3에 저장된 기본 이미지를 바라보도록 PinImage UPDATE 쿼리 날리기
>    * 운영 서버 이미지는 기존 데이터를 S3에 이관, DB에 저장된 컬럼 값 수정
> 
> * 이미지 삭제
>   
>   * PinImage는 Pin이 여러 이미지를 가지기에 존재하는 매핑 테이블로, pin_id 컬럼도 있어서 URL에 따라 하나로 묶는 건 어렵지 않을까요?  삭제 시에는
> 
> ```
> 1. PinImage 테이블에, 동일한 URL(또는 파일명)를 가진 레코드가 있는지 확인한다.
> 2. 있으면, 테이블 레코드만 지운다.
> 3. 없으면, 테이블 레코드도 지우고 S3에도 이미지 삭제 요청을 한다.
> ```
> 
> 이렇게 하는 건 어떨까요?



> 전체 코드 흐름 파악, 아래에 주신 질문 읽고 전체적인 리뷰 먼저 코멘트로 남겨둡니다! 코드에 대한 리뷰는 내일 아침에 진행할게용
> 
> ## 구현 내용 관련 질문
> 1. 서비스 메서드의 시그니처를 유지해야 하는 이유가 있을까용? `TopicCreateDtoWithOutImage` -> `TopicCreateDto` 이렇게 Dto에 depth가 있는 게 조금 어색하게 느껴져서요! Dto는 하나만 사용하고, Service에서 MultipartFile을 직접 받으면 안되나요?!
> 2. S3는 이미지를 저장하기 위한 기술의 이름인데, 상위 패키지명, 인터페이스명에 쓰이는 게 조금 어색한 것 같아요.
>    아래와 같은 네이밍은 어떨까요?
> 
> ```
> 패키지명: image
> 인터페이스: ImageService
> 구현체: S3ImageService
> 테스트 구현체: TestImageService
> ```
> 
> ## 의논 사항 답변
> 1. DB에 URL 저장 vs fileName 저장
>    
>    * 아래 2번 항목의 기존 데이터 이관을 하고 나면 fineName에 제시해준 단점이 모두 사라질 것 같아요.
>    * 그렇다면 기존 데이터 이관을 전제로, fileName 을 저장하는 게 어떨까요?
>    * URL을 저장하면, (그럴 일은 잘 없겠지만) 저희의 이미지 저장소가 바뀐다면 그 때 또 DB 데이터에 쓰인 URL도 다 수정해줘야 하는 단점도 있을 것 같아요.
>    * 대신 그러면 MemberInfo에서 쓰는 Image 클래스만 따로 분리해야 할 것 같아요.
> 2. DB에 저장된 기존 이미지 URL은 S3 URL이 아닌 문제
>    기존 데이터 이관 쪽에 동의합니다! 아래처럼 하면 어떨까용
>    
>    * 개발 서버 이미지는 유의미한 데이터가 아니니 모두 S3에 저장된 기본 이미지를 바라보도록 PinImage UPDATE 쿼리 날리기
>    * 운영 서버 이미지는 기존 데이터를 S3에 이관, DB에 저장된 컬럼 값 수정
> 
> * 이미지 삭제
>   
>   * PinImage는 Pin이 여러 이미지를 가지기에 존재하는 매핑 테이블로, pin_id 컬럼도 있어서 URL에 따라 하나로 묶는 건 어렵지 않을까요?  삭제 시에는
> 
> ```
> 1. PinImage 테이블에, 동일한 URL(또는 파일명)를 가진 레코드가 있는지 확인한다.
> 2. 있으면, 테이블 레코드만 지운다.
> 3. 없으면, 테이블 레코드도 지우고 S3에도 이미지 삭제 요청을 한다.
> ```
> 
> 이렇게 하는 건 어떨까요?

도이! 빠른 답변 감사합니다!

> 1. 서비스 메서드의 시그니처를 유지해야 하는 이유가 있을까용? TopicCreateDtoWithOutImage -> TopicCreateDto 이렇게 Dto에 depth가 있는 게 조금 어색하게 느껴져서요! Dto는 하나만 사용하고, Service에서 MultipartFile을 직접 받으면 안되나요?!

이 부분은 레벨 2에서 코일에게 리뷰를 받은적도 있고, 초기에 저와 쥬니가 Pin CRUD 기능을 개발할 때 Controller 에서 받는 Dto 와 Service 에서 받는 Dto 를 분리하자는 의견을 낸적도 있는 걸로 기억해요! (그 때 Dto 가 너무 많아져서 선택을 안하긴 했었죠 허허허)

제가 해당 방법을 선택한 이유는 Action Method 의 파라미터가, 내용은 동일하지만 형태가 달라졌다고 해서 Service 의 파라미터도 바뀐다면 변경사항이 너무 많아질 것 같다고 생각했어요.

실제로도 위와 같이 진행해서 변경사항이 많이 줄어들었던 것 같기도해요!

이 이상으로 고민하지는 않았지만, 위에서 설명드린 근거를 바탕으로 Service 의 파라미터를 그대로 유지하기로 판단했던 것 같아요!

다만, 이 방법이 올바르지 않다고 생각하시면 다시 한번 말씀해주세요!

그러면 이 부분도 수정하도록 하겠습니다!

그리고 나머지 부분들... 완전히 동의합니다.

삭제 부분도 제가 생각했던 플로우랑 동일해요.

다만, 제가 잘못 생각했던 부분은 Pin 복사시에 PinImage 도 똑똑하게 복사한다는 것을 잠시 잊고 있었네요! 짚어주셔서 감사해요.

긴 의견 감사합니다 도이! 이따가 더 이야기 해봐요~!

2023-09-18 01:18 UTC, yoondgu requested changes
수고 많으셨습니다 매튜 ~!!  
이번에도 쉬운 확인을 위해 질문/제안 위주로 리뷰 남겼습니다.
다같이 합의해야할 부분 하나를 P1으로 남겼고, P2/P3 몇개 가볍게 남겼으니 확인 부탁드려요 ㅎㅎ

이전 코멘트에 대해서도 빠르게 답변해주셔서 감사합니다.  
서비스 Dto에 대해서는..! 이전에 제안해주셨던 방향과 비슷한 거군요. 
저는 딱 이미지에 대해서만 서비스 Dto가 분리된 것 같아서 / 네이밍만 봤을 때는 이를 유추하기 어려워서 고민인 것 같아요 ㅜㅜ
근데 변경이 매우 많아진다는 것엔 동의해서, 다른 분들의 의견이랑 함께 얘기나눠봐요!

2023-09-18 01:18 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/s3/domain/ImageExtension.java
> +    public static ImageExtension fromByImageFileName(String imageFileName) {
P3. 메서드명 `from`으로 하는 건 어떨까요?! imageFileName이 파라미터에 이미 명시가 되어있어서요!

2023-09-18 01:18 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/s3/domain/ImageName.java
> +        return ImageExtension.fromByImageFileName(originalFileName);
P3. 메서드 분리 한 김에 `.getExtension()` 도 분리한 메서드 안에서 하면 어떨까요? + 메서드명을 `findExtension`으로 해서 덜 헷갈리게 하면 어떨까요?!

2023-09-18 01:18 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicInfo.java
> +    );
이전과 이 링크의 차이는 어떤거죠...?! 단순 궁금증입니닿 😀

2023-09-18 01:18 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/pin/PinIntegrationTest.java
> +    @DisplayName("Image List 없이 Pin 을 정상적으로 생성한다.")
굿굿

2023-09-18 01:18 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/exception/TopicErrorCode.java
> +    TOPIC_NOT_FOUND("10400", "지도가 존재하지 않습니다."),
P1. 앗 S3ErrorCode가 패키지 순서 중간에 생기면서 번호를 같이 바꿔주셨군요!! 
이 부분 전체 논의가 필요할 것 같아요 ! 
저는 에러코드 처음 작성 시 패키지 순서 대로 부여한 번호  / 그 이후에 새로 생기는 패키지는 그 다음 새 번호(10, 11)를 부여하는 걸로 생각하고 있었거든요.  그럼 패키지 당 번호가 조금 헷갈리겠지만, 대신 패키지가 추가될 때마다 문서에 이를 업데이트하는 걸로요.  
같이 얘기해봐요 !!

2023-09-18 03:32 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/s3/application/S3ServiceImpl.java
> +@Profile("!test") // Test 시에는 TestS3ServiceImpl 를 Component 로 띄우기 위해 Profile 을 분리하였습니다.
TODO 를 붙이는 것을 까먹었네요 수정하도록 하겠슴돠!

2023-09-18 03:37 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/s3/application/S3ServiceImpl.java
>          }
네 질문에 대답 잘해주셨어요!

하지만 IOException 가 checked exception 으로 알고 있어서, 저기서 IOException 을 throws 를 하면 해당 메서드를 사용하는 메서드들에서도 throws 를 추가해줘야 해서 고민하고 있었어요.

그냥 checked exception 을 던져야 할까요?

2023-09-18 03:37 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/s3/domain/ImageExtension.java
> +    public static ImageExtension fromByImageFileName(String imageFileName) {
맞네요! 수정하겠습니다

2023-09-18 03:38 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/s3/domain/ImageName.java
> +        return ImageExtension.fromByImageFileName(originalFileName);
수정하겠습니당!

2023-09-18 03:39 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicInfo.java
> +    );
이미지가 다른 걸로 알아요! 확인하지는 않긴 했지만 허허허..

현재 저희 괜찮을지도 서비스에서 기본적으로 제공하는 이미지가 저 이미지더라고요 빠뚜릭이 보내줘서 바꿨습니다.

2023-09-18 03:41 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/exception/TopicErrorCode.java
> +    TOPIC_NOT_FOUND("10400", "지도가 존재하지 않습니다."),
아 맞아요!

사실 저도 그냥 그대로 둘려고 했었는데 아무리 봐도 패키지 순서로 정하신 것 같고, 제가 임의대로 10번부터 시작해버리면 헷갈릴 수도 있을 것 같아서 위와 같이 바꿨었습니다.

하지만 계속 이렇게 바꾸게 되면 추후 변경사항이 너무 많아질 것 같긴합니다.

한번 이야기 해보죠!

2023-09-18 12:57 UTC, junpakPark reviewed
매튜 코드 꼼꼼히 다 읽어봤습니다.
코드 구현에서 아쉬운 점은 하나도 발견 되지 않았습니당 👍👍👍

다만 사진 저장에 실패하면, 핀이나 토픽 자체가 저장이 되지 않게 할 것인지,
아니면 그냥 이미지가 없는 상태로 저장이 되게할 것인지 하는 정책적인 부분과,

pin이나 topic 서비스들에 필드로 S3imageService를 주기보다는
controller의 필드로 둬서 upload 메서드의 리턴 String만 pin이나 topic 서비스로 내려주는 건 어떨까
하는 제안 두가지만 같이 고민해보고 싶어서 코멘트 남깁니다.

수고하셨어요~!!

2023-09-18 13:45 UTC, kpeel5839 commented
> 매튜 코드 꼼꼼히 다 읽어봤습니다.
> 코드 구현에서 아쉬운 점은 하나도 발견 되지 않았습니당 👍👍👍
> 
> 다만 사진 저장에 실패하면, 핀이나 토픽 자체가 저장이 되지 않게 할 것인지,
> 아니면 그냥 이미지가 없는 상태로 저장이 되게할 것인지 하는 정책적인 부분과,
> 
> pin이나 topic 서비스들에 필드로 S3imageService를 주기보다는
> controller의 필드로 둬서 upload 메서드의 리턴 String만 pin이나 topic 서비스로 내려주는 건 어떨까
> 하는 제안 두가지만 같이 고민해보고 싶어서 코멘트 남깁니다.
> 
> 수고하셨어요~!!

준팍 코멘트 감사해요 ~!

제시해준 두 가지 포인트 너무 좋은 것 같아요!

내일 백엔드 다 같이 해당 부분에 대해 논의해보고 결정하게되면 코드에 반영하도록 할게요~~~~~

2023-09-19 11:34 UTC, cpot5620 requested changes
안녕하세요 매튜.
File changes가 33개군요...
이런식이면 저는 .. ㅈㅅ

고생 많았써여 매튜 !
확인해야할 부분 조금 있는 것 같아서 request changes 날리겠습니다.

> DB 에 저장해야 할 내용은 Image URL 이라고 생각하시나요? 아니면 fileName 이름이라고 생각하시나요? 

저장되는 데이터의 크기로 보나, 어색함(?)으로 보나 fileName이 적절할 것 같아요 !
기존에 저장된 값들은.. 수동으로 해결하는걸로.. 해야할 것 같아요..

> 기존 데이터를 어떻게 활용할 것일까?

매튜가 직접 update 해주세요.

> 이미지 삭제.. 전에 많이 이야기 나눴지만 막상 S3 와 함께 구현해보려 하니까 쉽지 않아요
>> 도이 의견 1. PinImage 테이블에, 동일한 URL(또는 파일명)를 가진 레코드가 있는지 확인한다.

흠.. 도이가 좋은 해결책을 제시해주신 것 같은데, 한 가지 걱정되는 부분은 문자열이다 보니, 성능 이슈일 것 같아요. 우선은 도이 의견이 최선책으로 보이긴 합니다 ~!

2023-09-19 11:34 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/image/application/S3ImageService.java
> +public class S3ImageService implements ImageService {
개인적으로 `Profile` 어노테이션을 안 좋아하는데요. (프로덕션 코드가 환경 설정에 의존적인 느낌이라)

테스트 수행시 발생하는 빈 충돌로 해당 어노테이션을 사용하신 것 같아요.
수동 빈 등록 vs 자동 빈 등록에서 수동으로 등록된 빈이 우선순위를 갖게되는데요.
혹시 이를 활용하는 방법은 어떠실까요 ?

구현하는데 많은 비용이 들 것 같으면, 무시하고 넘어가셔도 좋습니다 ~!

2023-09-19 11:34 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/image/application/S3ImageService.java
>      }
서버 에러로 봐도 무방할 것 같아용

2023-09-19 11:34 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/image/domain/ImageName.java
>      }
메서드 명을 결정하는데에 고민하신 흔적이 남아 있네요 ㅋㅋㅋ 바보

개인적으로, 파일 명에서 확장자를 `추출`하는 것이니 extract~~ 로 작성하는 것은 어떨까 싶어요,

2023-09-19 11:34 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/image/domain/S3Client.java
> +        if (!Objects.isNull(tempFile) && tempFile.exists()) {
`Objects.nonNull` 을 사용하는 건 어떨까요 ?

2023-09-19 11:34 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/image/domain/S3Client.java
> +        // 현재는 일단 기능만 만들어놓고, API 는 만들어놓지 않았습니다 회의를 통해서 결정해야 할 사항이 있는 것 같아서요!
todo ^^

2023-09-19 11:34 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/image/exception/S3ErrorCode.java
> +    ILLEGAL_IMAGE_FILE_EXTENSION("09000", "이미지 파일이 아닙니다."),
`지원하지 않는 이미지 파일` 이라고 하는 것이 자연스러울 것 같아요.

2023-09-19 11:34 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
> +        if (0 < pinIds.size()) {
무슨 고민을 하신 겁니까 ~!!!!!!!!!!!!!!!!!

2023-09-19 11:34 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/exception/TopicErrorCode.java
> +    TOPIC_NOT_FOUND("10400", "지도가 존재하지 않습니다."),
저한테는 결과만 알려주세요.
아무래도 상관없으니까요 힛

2023-09-19 11:34 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
> +            consumes = {MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE}
M보다 A가 알파벳 순서상 빠르기 때문에, 순서가 바뀌어야 할 것 같은..... 죄송합니다.

리뷰하다가 정신줄을 놔버렸어요

2023-09-19 11:41 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/image/application/S3ImageService.java
> +public class S3ImageService implements ImageService {
오 저는 수동 빈 등록이 더 우선순위를 갖는지 몰랐어요!

그러면 TestImageService 를 수동으로 빈 등록 하면 되는건가요?

2023-09-19 11:41 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/image/domain/ImageName.java
>      }
이거 또이또이가 findExtension 하자고 했는데에에에엥

2023-09-19 11:42 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/image/domain/S3Client.java
> +        if (!Objects.isNull(tempFile) && tempFile.exists()) {
이거 있는지 몰랐는데 개꿀

2023-09-19 11:42 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/image/domain/S3Client.java
> +        // 현재는 일단 기능만 만들어놓고, API 는 만들어놓지 않았습니다 회의를 통해서 결정해야 할 사항이 있는 것 같아서요!
어쩔 tv

2023-09-19 11:42 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/image/exception/S3ErrorCode.java
> +    ILLEGAL_IMAGE_FILE_EXTENSION("09000", "이미지 파일이 아닙니다."),
맞네요! 그게 더 자연스러울 것 같아요

2023-09-19 11:42 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
> +        if (0 < pinIds.size()) {
i...s...Empty....

2023-09-19 11:42 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
> +            consumes = {MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE}
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 바꿀게요 미션하고 ^.^

2023-09-19 12:01 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/image/domain/ImageName.java
>      }
extract 좋은데요? 고고

2023-09-20 02:37 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/image/application/S3ImageService.java
> +public class S3ImageService implements ImageService {
테스트 패키지에 `@Bean` 어노테이션을 통해 수동 빈 등록을 해주면 될 거에요.

근데, 아마 스프링 부트에서 수동 빈 등록과 자동 빈 등록을 통한 충돌을 기본적으로 지원하지 않아서, yml파일에 override 옵션을 켜줘야하는걸로 알아요 ~

2023-09-20 13:18 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/exception/TopicErrorCode.java
> +    TOPIC_NOT_FOUND("10400", "지도가 존재하지 않습니다."),
어쩔 tvtv

2023-09-20 13:19 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/image/application/S3ImageService.java
> +public class S3ImageService implements ImageService {
해줘.

2023-09-20 13:19 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/image/application/S3ImageService.java
>      }
그러면 그냥 RuntimeException 던져도 된다는 말로 이해해도 될까요?

2023-09-21 01:45 UTC, yoondgu approved these changes
수고 많으셨습니다 !!

2023-09-21 01:53 UTC, merged