[BE] Refactor/#400 토픽 조회 시 업데이트 일시를 최근에 핀이 추가/변경된 일시로 변경
woowacourse-teams/2023-map-befine pull request #429
Opened 2023-09-17 12:54 UTC by yoondgu

## 작업 대상

- Topic, Pin : `@PrePersist`, `@PreUpdate` EntityListener 메서드 추가
- TopicQueryService : 최신순 토픽 조회 시, 기존 Pin을 모두 가져와 가공 후 정렬해야 했던 것을 lastPinUpdatedAt 컬럼으로 바로 정렬 가능하도록 바뀌었습니다.
    - TopicRepository(정렬 조회 쿼리 추가), PinRepository(정렬 조회 쿼리 삭제)
- TopicResponse, TopicDetailResponse : updatedAt 필드에 topic.getLastUpdatedAt을 넣어줍니다.
- 관련 테스트 작성

## 📄 작업 내용

#400 참조.

### 사전 논의 내용
> 논의할 땐 핀이 '추가'되는 일시만 기준으로 얘기했었는데, 기존 '새로울 지도' 구현 코드를 보니 핀이 변경된 일시도 고려하고 있었더라구요. 핀이 변경된 일시도 '업데이트 일자'에 반영하는 게 자연스러운 것 같아 똑같이 진행했습니다!

토픽을 조회할 때, 토픽이 가진 핀이 추가/변경된 일시를 '업데이트 일자'로 보여주는데,  
항상 핀을 가져와 이를 조회하는 대신 ,  
토픽에 `lastPinUpdatedAt` 컬럼을 두고 핀이 추가/변경될 때 해당 컬럼을 업데이트하도록 합니다.

쓰기 작업보다 조회 작업이 더 많을 것으로 예상되어, 이 방식이 더 성능적으로 유리하다고 판단했습니다.

### 구현 방식

기존에 저희가 `createdAt`, `updatedAt`을 저장할 때에는, `AuditingEntityListner.class`에 의해 **객체를 영속화 할 때** 해당 값이 저장됩니다.
(때문에 영속화 하기 전에 객체에 `getCreatedAt`을 하면 Null 을 반환합니다.)  

그래서, 

```java
    public void addPin(Pin pin) {
        pins.add(pin);
        lastPinUpdatedAt = LocaldateTime.now(); // 영속화하는 시점이 아니라, 핀을 추가하는 코드 실행 시 시간을 저장
    }
```
**위와 같은 방식으로 구현하면 `Pin.getCreatedAt()`과 `Topic.getLastPinUpdatedAt`이 미묘하게 다른 문제가 발생합니다.**
때문에 시간을 저장하는 시점을 일관적으로 관리할 필요가 있다고 판단해 `lastPinUpdatedAt`도 **영속화 시점에 설정**되도록 하였습니다.

따라서 Pin 클래스에 아래와 같은 메서드를 추가했습니다.
```java
    @PrePersist // 엔티티를 영속화할 때(save) 메서드가 실행됩니다.
    protected void prePersist() {
        topic.updateLastPinUpdatedAt(getUpdatedAt()); // pin의 updatedAt으로 맞춰줌
    }

    @PreUpdate // flush나 commit을 호출해 데이터 베이스 업데이트를 할 때 메서드가 실행됩니다.
    protected void preUpdate() {
        topic.updateLastPinUpdatedAt(getUpdatedAt()); // pin의 updatedAt으로 맞춰줌
    }
```

이 어노테이션들은 Jpa에서 제공하는 이벤트입니다.  
BaseEntity에 쓰고 있는 `AuditingEntityListener`도 `@PrePersist`, `@PreUpdate`를 사용해 동작합니다.  
그것처럼 별로의 리스너 클래스를 분리해서 써도 되지만, 저희 로직에서는 Pin 내부에서 동작하는 게 깔끔하다고 판단했습니다.

## 🙋🏻 주의 사항

ServiceTest에서 해당 내용을 테스트하기 위해, `@ServiceTest`에 `JpaConfig.class`를 추가했습니다.
추가하지 않으면 JpaConfig 설정이 안되어있어서 JpaAuditing이  작동하지 않기때문입니당

### 배포하기 전에!!
LastPinUpdatedAt 컬럼이 새로 추가되기 때문에,  
ddl-auto : update 로 실행할 경우  
기존 레코드에 대해 새로 추가된 컬럼에 현재 시간이 추가되어 비정상적인 데이터 변경이 일어날 것으로 예상됩니다.  
따라서 배포 직후 기존 레코드에 대해 해당 컬럼에, 최신 핀 추가일시를 조회해 Update 해주는 쿼리를 작성해 직접 실행하는 게 좋을 것 같습니다.

## 스크린샷

## 📎 관련 이슈

 

## 레퍼런스

[JPA Auditing과 제대로 알아야 할 @PreUpdate](https://newwisdom.tistory.com/109)
[[JPA] 리스너 - 엔티티의 생명주기에 따른 이벤트 처리](https://ttl-blog.tistory.com/191)

2023-09-18 00:32 UTC, kpeel5839 requested changes
도이! PR 본문에 설명이며 주의사항이며 너무 잘적어주셔서 코드 이해하는데 정말 많은 도움이 되었습니다!

간단한 코멘트 남겼으니 확인부탁드려요!

2023-09-18 00:32 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/common/entity/BaseTimeEntity.java
> +    @Column(updatable = false)
해당 라인을 추가하지 않을시에는 createdAt 도 update 되는 경우가 있나요?

2023-09-18 00:32 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
> +        topic.updateLastPinUpdatedAt(getUpdatedAt());
처음에는 왜 getUpdatedAt 이지 ? 라는 생각을 했는데, 곰곰히 생각해보니 getUpdatedAt 이 맞군요!

도이짱!

2023-09-18 00:32 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
> +                topic.getLastPinUpdatedAt()
fromGuestQuery() 는 updatedAt 이 topic 의 lastPinUpdatedAt 으로 바뀌지 않아도 괜찮을까요?

2023-09-18 00:32 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/common/annotation/ServiceTest.java
> +@Import(JpaConfig.class)
따봉!

2023-09-18 00:32 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicTest.java
> +    @DisplayName("토픽 정보를 변경한다.")
displayName 이 없었군용

2023-09-18 01:15 UTC, cpot5620 approved these changes
고생하셨습니다 도이 ~~
질문 남겼는데 확인 부탁드려여

2023-09-18 01:15 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/common/entity/BaseTimeEntity.java
> +    @Column(updatable = false)
우리는 리플렉션을 배웠다.
만약, createdAt에 접근하여 값을 수정한다면, 어떻게 되겠는가 ? 
ㅎㅎ

2023-09-18 01:15 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
> +
`@PrePersist`가 save() 메서드 호출시 실행되는 메서드라면, 해당 메서드는 불필요한 것 아닌가요 ??
제가 이해를 잘 못했을수도 ㅠㅠ

2023-09-18 01:15 UTC, cpot5620 commented on backend/src/main/resources/data-default.sql
> +VALUES ('dummyMember', 'dummy@gmail.com', 'https://map-befine-official.github.io/favicon.png', 'USER', 'NORMAL',
헐 이거 까먹고 안 했네요 제가 ㅠㅠㅎㅎ

2023-09-18 01:15 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
> +        pinRepository.flush();
와 Repository에도 flush가 있군요 ?

em에만 있는줄..

2023-09-18 01:16 UTC, kpeel5839 commented
도이께서 주의 사항에 남겨주신 

> LastPinUpdatedAt 컬럼이 새로 추가되기 때문에,
ddl-auto : update 로 실행할 경우
기존 레코드에 대해 새로 추가된 컬럼에 현재 시간이 추가되어 비정상적인 데이터 변경이 일어날 것으로 예상됩니다.
따라서 배포 직후 기존 레코드에 대해 해당 컬럼에, 최신 핀 추가일시를 조회해 Update 해주는 쿼리를 작성해 직접 실행하는 게 좋을 것 같습니다.

이 부분 쿼리 짜봤습니다!

다들 검토 부탁드릴게요! 일단 제가 개발 서버 DB dump 떠놓은게 있어서 거기서 테스트 할 때에는 잘 돌아갔어요.

```sql
update topic
set last_pin_updated_at = (select IFNULL(max(p.updated_at), topic.updated_at)
				         from pin p
                                         where p.topic_id = topic.id);
```

2023-09-18 01:17 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
> +
저도 이 부분이 의아했어요!

2023-09-18 01:21 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
> +                topic.getLastPinUpdatedAt()
아앗. 실수ㅎㅎㅎ 수정할게요!!

2023-09-18 01:29 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
> +
`@PrePersist`는 비영속 상태의 객체를 영속화할 때 호출되는데요  
저희가 Pin을 업데이트할 때에는, pin.updateInfo 를 호출해서 원래 영속화 상태인 Pin을 변경합니다.
이 때는 save() 메서드를 호출하지 않고 Update 쿼리가 날라가죵
그래서 이 경우에는 PrePersist에 해당하지 않고, PreUpdate에 해당합니다!!
테스트 상으로도 그렇게 작동하는 것 같아용

2023-09-18 01:29 UTC, yoondgu commented
> 도이께서 주의 사항에 남겨주신
> 
> > LastPinUpdatedAt 컬럼이 새로 추가되기 때문에,
> > ddl-auto : update 로 실행할 경우
> > 기존 레코드에 대해 새로 추가된 컬럼에 현재 시간이 추가되어 비정상적인 데이터 변경이 일어날 것으로 예상됩니다.
> > 따라서 배포 직후 기존 레코드에 대해 해당 컬럼에, 최신 핀 추가일시를 조회해 Update 해주는 쿼리를 작성해 직접 실행하는 게 좋을 것 같습니다.
> 
> 이 부분 쿼리 짜봤습니다!
> 
> 다들 검토 부탁드릴게요! 일단 제가 개발 서버 DB dump 떠놓은게 있어서 거기서 테스트 할 때에는 잘 돌아갔어요.
> 
> ```sql
> update topic
> set last_pin_updated_at = (select IFNULL(max(p.updated_at), topic.updated_at)
> 		           from pin p
>                            where p.topic_id = topic.id);
> ```


👍👍👍👍👍👍👍👍👍👍

2023-09-18 01:39 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
> +                topic.getLastPinUpdatedAt()
반영했습니다!

2023-09-18 01:51 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
> +
와우 깔끔한 답변 구두우우욷

2023-09-18 03:32 UTC, junpakPark commented on backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
> +        pinRepository.flush();
이거 진짜 맛도린데요?

2023-09-18 03:34 UTC, junpakPark approved these changes
도이 PR이 굉장히 맛도린데요? 👍👍👍
세부적인 내용은 쥬니나 매튜가 잘 봐주셔서
저는 바로 approve 하겠습니다.

2023-09-19 02:04 UTC, kpeel5839 approved these changes
빠르게 반영해주셨는데 제가 너무 approve 를 늦게 드렸군요!

최고입니다 도이! 항상 배웁니다~!

2023-09-19 06:20 UTC, merged