[BE] Feature/#422 성능 측정을 위한 로깅 구현
woowacourse-teams/2023-map-befine pull request #434
Opened 2023-09-18 15:11 UTC by cpot5620

## 작업 대상

#422 
## 📄 작업 내용

기존 준팍이 제안해주셨던 AOP 대신, 필터를 적용하여 구현하였습니다.
(AOP에 대한 학습 곡선보다는 필터를 빠르게 적용하는 것이 낫다고 판단했습니다.)
## 🙋🏻 주의 사항

다들 바쁜 시기인 만큼, 각 라인 별 이해를 돕기 위한 설명 남겨놓도록 하겠습니다. 
## 스크린샷

## 📎 관련 이슈

#422 
 
closed #422 
## 레퍼런스

2023-09-18 15:12 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/common/filter/QueryCounter.java
> +@RequestScope
해당 Bean의 스코프를 위와 같이 설정함으로써, 생명 주기를 `각 요청`으로 설정하였습니다.

2023-09-18 15:12 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/common/filter/QueryInspector.java
> +    }
`StatementInspector`에서 쿼리를 실행하기 전에, insepct 메서드를 호출합니다.

이때, 쿼리 카운트를 증가시킴으로써 쿼리 횟수를 확인할 수 있습니다.

2023-09-18 15:14 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/common/config/HibernateConfig.java
> +    }
Hibernate에 쿼리 수 측정을 위한 QueryInspector를 등록하는 코드입니다.

2023-09-18 15:14 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/common/filter/LatencyLoggingFilter.java
> +        MDC.clear();
임무를 마치고 복귀하는 쓰레드는 자신의 로컬 정보(?)를 삭제하지 않기 때문에 로깅 정보를 clear 해주어야 합니다.

2023-09-18 15:15 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/common/filter/LatencyRecorder.java
> +        threadLocal.remove();
쓰레드 풀로 돌아가기 전에 remove를 통해, threadLocal에 저장된 값을 삭제해줍니다.

2023-09-19 01:33 UTC, junpakPark requested changes
쥬니 친절한 설명덕분에 코드를 이해하는 데 어려움이 없었습니당 ㅎㅎ
테스트도 있어서 더욱 든든하군요~ 👍👍👍

로직이나 코드 상 리뷰 남길 건 없구요
각 파일 맨 끝에 개행이 없는 것 같은데
해당 부분을 위한 Request Change 남기겠습니당 ㅎㅎ

2023-09-19 01:40 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/common/config/HibernateConfig.java
> +    }
설명 굳굳~!

2023-09-19 01:51 UTC, yoondgu approved these changes
상세한 설명 감사합니다 쥬니!! 수고 많으셨어용
approve 드리면서 의견 하나만 남길게요!

해당 로깅을 로컬 환경에서만 수행하도록 할 필요는 없을까요?
개발 서버에서는 계속 남겨도 될 로그라고 보시는지 궁금합니다!!

로컬 환경에서만 작동하도록 하는 방법 자체는 간단해보이는데, 팀원 분들의 의견에 따라 진행하면 될 것 같습니다.
[참고 링크](https://likispot.tistory.com/73) 에서 Command + f로 "profile" 찾으면 나오는 내용

2023-09-19 01:58 UTC, kpeel5839 approved these changes

2023-09-19 01:58 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/common/filter/QueryCounterTest.java
> +        assertThat(queryCounter.getCount()).isZero();
isZero 간지나네요

2023-09-19 01:58 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/common/filter/QueryCounterTest.java
> +        assertThat(queryCounter.getCount()).isOne();
isOne 도 간지나네요

2023-09-19 01:58 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/common/filter/LatencyRecorderTest.java
> +
저 이 부분 이해가 안가보렷...

이렇게 하면 첫번째 thread.sleep 과 두번쨰 thread.sleep 은 다른 thread 에서 실행되는 것인가요?

2023-09-19 01:58 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/common/filter/LatencyLoggingFilter.java
> +        MDC.clear();
굳굳~!

2023-09-19 01:58 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/common/filter/LatencyRecorder.java
> +        return (double) (end - start) / 1000;
`return (end - start) / 1000d;` 이렇게는 어떠신가용?

2023-09-19 01:59 UTC, kpeel5839 commented
조그만한 질문이랑 제안하나 드립니다~! 고생하셨어요~~~~

2023-09-19 02:02 UTC, kpeel5839 commented
> 상세한 설명 감사합니다 쥬니!! 수고 많으셨어용 approve 드리면서 의견 하나만 남길게요!
> 
> 해당 로깅을 로컬 환경에서만 수행하도록 할 필요는 없을까요? 개발 서버에서는 계속 남겨도 될 로그라고 보시는지 궁금합니다!!
> 
> 로컬 환경에서만 작동하도록 하는 방법 자체는 간단해보이는데, 팀원 분들의 의견에 따라 진행하면 될 것 같습니다. [참고 링크](https://likispot.tistory.com/73) 에서 Command + f로 "profile" 찾으면 나오는 내용

그러면 LatencyLoggingFilter 위에 @Profile("로컬 프로필명") 만 추가하면 되려나요?

2023-09-19 02:31 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/common/filter/LatencyRecorderTest.java
> +
모든 Thread에서 실행되는걸로 알아요..

테스트 의도는 새로 생성한 쓰레드에서는 6초를 기다렸고, 필드에 생성한 쓰레드는 3초만 기다렸다...
쓰레드 간의 독립성을 ,. 보여주고싶었어요

2023-09-19 02:38 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/common/filter/LatencyRecorder.java
> +        return (double) (end - start) / 1000;
Half zero Success

2023-09-19 02:38 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/common/filter/LatencyRecorderTest.java
> +
이해완!

알러뷰

2023-09-19 02:42 UTC, yoondgu commented
> > 상세한 설명 감사합니다 쥬니!! 수고 많으셨어용 approve 드리면서 의견 하나만 남길게요!
> > 해당 로깅을 로컬 환경에서만 수행하도록 할 필요는 없을까요? 개발 서버에서는 계속 남겨도 될 로그라고 보시는지 궁금합니다!!
> > 로컬 환경에서만 작동하도록 하는 방법 자체는 간단해보이는데, 팀원 분들의 의견에 따라 진행하면 될 것 같습니다. [참고 링크](https://likispot.tistory.com/73) 에서 Command + f로 "profile" 찾으면 나오는 내용
> 
> 그러면 LatencyLoggingFilter 위에 @Profile("로컬 프로필명") 만 추가하면 되려나요?

아 제가 공유드린 글은 경우가 조금 다르네요..!! 
지금 코드 상황에서는 찾아보니깐 `LatencyLoggingFilter`에서 `OncePerRequestFilter`가 제공하는 메서드를 오버라이딩하면 적용할 수 있는 것 같아요.

```java
    @Override
    protected boolean shouldNotFilter(HttpServletRequest request) {
        String activeProfile = System.getProperty("spring.profiles.active");
        return "dev".equals(activeProfile) || "prod".equals(activeProfile);
    }
```

2023-09-19 02:42 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/common/filter/LatencyRecorder.java
> +        return (double) (end - start) / 1000;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 무신 소리에요

2023-09-19 02:47 UTC, kpeel5839 commented
> > > 상세한 설명 감사합니다 쥬니!! 수고 많으셨어용 approve 드리면서 의견 하나만 남길게요!
> > > 해당 로깅을 로컬 환경에서만 수행하도록 할 필요는 없을까요? 개발 서버에서는 계속 남겨도 될 로그라고 보시는지 궁금합니다!!
> > > 로컬 환경에서만 작동하도록 하는 방법 자체는 간단해보이는데, 팀원 분들의 의견에 따라 진행하면 될 것 같습니다. [참고 링크](https://likispot.tistory.com/73) 에서 Command + f로 "profile" 찾으면 나오는 내용
> > 
> > 
> > 그러면 LatencyLoggingFilter 위에 @Profile("로컬 프로필명") 만 추가하면 되려나요?
> 
> 아 제가 공유드린 글은 경우가 조금 다르네요..!! 지금 코드 상황에서는 찾아보니깐 `LatencyLoggingFilter`에서 `OncePerRequestFilter`가 제공하는 메서드를 오버라이딩하면 적용할 수 있는 것 같아요.
> 
> ( `!로컬 프로필명.equals()`로 해도 되지만 로컬 프로필명을 따로 정의하지 않아도 적용가능하게 하려면 이렇게 될 것 같아요)
> 
> ```java
>     @Override
>     protected boolean shouldNotFilter(HttpServletRequest request) {
>         String activeProfile = System.getProperty("spring.profiles.active");
>         return "dev".equals(activeProfile) || "prod".equals(activeProfile);
>     }
> ```

최고네요~!

2023-09-19 02:50 UTC, cpot5620 commented
준팍 및 매튜 코멘트 적용했습니다.

도이가 제안해주신 부분은 이야기 나누어보아야 할 것 같은데, 저는 개발 서버에서까지 로깅해야 좋을 것 같다는 생각이 들어요 !! (운영 서버는 조금 고민해봐야겠네용)
왜냐하면, 새로운 기능을 추가하게 되었을 때에도 매번 로컬에서만 테스트를 수행할 수는 없고, 놓치는 부분들이 생길 거라고 생각해요.
개발환경에서도 로깅하면, QA를 진행하면서 자연스럽게 알게되는 문제들도 확인할 수 있을 것 같아서요 !

2023-09-19 03:17 UTC, yoondgu commented
> 준팍 및 매튜 코멘트 적용했습니다.
> 
> 
> 
> 도이가 제안해주신 부분은 이야기 나누어보아야 할 것 같은데, 저는 개발 서버에서까지 로깅해야 좋을 것 같다는 생각이 들어요 !! (운영 서버는 조금 고민해봐야겠네용)
> 
> 왜냐하면, 새로운 기능을 추가하게 되었을 때에도 매번 로컬에서만 테스트를 수행할 수는 없고, 놓치는 부분들이 생길 거라고 생각해요.
> 
> 개발환경에서도 로깅하면, QA를 진행하면서 자연스럽게 알게되는 문제들도 확인할 수 있을 것 같아서요 !

그러면 지금대로 진행해도 좋습니다 !! 👍👍

2023-09-19 07:06 UTC, junpakPark approved these changes
EOF 해결하셨군용~
수고하셨습니다~

2023-09-19 07:58 UTC, merged