[FE] refactor/#450 모아보기 기능 비회원도 가능하도록 수정
woowacourse-teams/2023-map-befine pull request #516
Opened 2023-09-27 08:55 UTC by GC-Park

## 작업 대상

모아보기 기능 비회원도 가능하도록 수정

## 📄 작업 내용

- [x] 모아보기 기능 비회원도 가능하도록 수정

## 🙋🏻 주의 사항

## 스크린샷

## 📎 관련 이슈

 
close #450 

## 레퍼런스

2023-09-28 19:41 UTC, semnil5202 requested changes
패트릭~ 고생 정말 많으셨습니다. 👍👍👍 로그인 상태에 따라서 UI를 낙관적 업데이트할지 말지, 기능 플로우도 달리 해야하고.. 여러므로 관리해야할 포인트가 많으셨을텐데 전반적으로 의도하신 기능이 잘 동작하는 것 같습니다.

다만 Navbar 로직이 예전 로직으로 덮어씌워졌습니다.. 아마도 충돌 해결하시면서 발생한 일 같네요. 이 부분 때문에 리퀘스트 체인지로 드립니다.

몇 가지 코멘트 남겼습니다. 사실 기능상 문제는 없어서 머지해도 괜찮을 것 같습니다만, Navbar 문제를 해결하면서 좀 더 개선해보면 좋을 부분이 있어서 나름 제 생각을 적어보았습니다.

몸 관리가 최우선이시니 절대 무리하시지 마시고욥!! 이 부분은 추석 끝난 이후에 머지해도 괜찮습니다. 만약 이 내용을 이번 배포에 적용시키고 싶은데 몸이 안따라준다면 제게 디엠 주세요. 제가 이어서 작업해도 괜찮을 것 같습니다!

아무튼 약 잘 드시고! 연휴인데 아쉬운대로 배달 음식도 야무지게 시켜드셔서 얼렁 회복하시길 바랍니다. 고생많으셨습니다. 👍👍

2023-09-28 19:41 UTC, semnil5202 commented on frontend/src/pages/SelectedTopic.tsx
> +    if (topicId === '-1') return;
-1 도 좋지만 'empty' 나 좀 더 명확한 네이밍이 어떨가용? 저번에 전화로 이야기를 들었는데도 잠깐 이게뭐지? 했었네요. Navbar에서 'empty'로 파라미터 넘겨주면 될 것 같아요.

가만 생각해보면.. 모아보기 기능은 페이지 분리가 필요한가 싶기도 하네요.

2023-09-28 19:41 UTC, semnil5202 commented on frontend/src/pages/SelectedTopic.tsx
> +  if (seeTogetherTopics.length === 0 && topicId === '-1') {
굳 👍

2023-09-28 19:41 UTC, semnil5202 commented on frontend/src/router.tsx
> -            <SeeTogetherTopics />
seeTogether 페이지 컴포넌트 자체도 삭제해주세용~

2023-09-28 19:41 UTC, semnil5202 commented on frontend/src/context/SeeTogetherContext.tsx
> +  setSeeTogetherTopics: Dispatch<SetStateAction<number[] | []>>;
이전에 전화로 전달해주셨을 때 그대로 써도 문제없을 것 같았는데 AddSeeTogether onChangeIsInAtlas 함수안에

```js
    else setSeeTogetherTopics((prev) => [...prev, id]);
```

요 부분 때문에 바꿔야만 하는군요 ㅋㅋㅋㅋ 좋습니다. 👍👍

2023-09-28 19:41 UTC, semnil5202 commented on frontend/src/pages/Home.tsx
> +
요 로직이 모아보기 페이지에도 있어야할 것 같네요. 제가 원래 생각했던 것은 비회원에게는 모아보기가 일회성 장바구니처럼 기능을 제공하는 쪽이었습니다. 그래서 모아보기 리스트를 초기화하면서 로그인을 하면 모아보기 리스트가 유지돼요! 이런식의 토스트를 남겨둘 생각이었어요. (로그인 유도도 좀 할겸?)

그래도 홈에도 여전히 이 로직이 필요합니다. 왜그러냐면 비회원이 접속할 수 있는 페이지가 홈이랑 모아보기 둘 뿐이면 홈에는 필요가 없지만, 안타깝게도 저희에겐 askLogin 페이지도 있기 때문입니다 ㅋㅋㅋㅋ 그래서 홈 -> 모아보기 담고 -> 즐겨찾기(애스크 로그인으로 전환) -> 홈 이렇게 이동하면 모아보기 리스트는 그대로지만 UI는 초기화 되어있겠죠.

모아보기 페이지에서 초기화를 안해주면 결정적으로 topicInfo 의 모아보기 버튼과 UI가 차이가 나는 결정적인 문제가 있기도합니다.

2023-09-29 15:50 UTC, afds4567 approved these changes
비회원용 모아보기 기능 지나가면서 듣기엔 localStorage 이용한다고 들었는데 제가 잘못 들었던것 같네요... 내부 상태로 관리하는 방법인거 같은데 좋습니다~

2023-09-29 15:50 UTC, afds4567 commented on frontend/src/components/Layout/Navbar.tsx
>  import Flex from '../common/Flex';
여기 Navbar.tsx전체 반복되는 부분 map으로 묶어서 리팩토링 해둔거 머지된거같은데 지금 패트릭 로컬에 반영 안되서 다시 원상복귀 되는거 같아요. 혹시 일부러 되돌리시는건가요??

2023-09-29 15:50 UTC, afds4567 commented on frontend/src/components/Layout/Navbar.tsx
> -interface NavbarItemProps {
이미 세인이 커멘트 남겼네요

2023-09-29 15:50 UTC, afds4567 commented on frontend/src/components/TopicCard/index.tsx
> +  const [atlas, setAtlas] = useState<boolean>(isInAtlas);
AddSeeTogether에서부터 뭔가 하고 찾아 내려왔는데 세인 커멘트처럼 비회원용인지 바로 알 수 있으면 좋을것 같아요

2023-10-04 10:58 UTC, GC-Park commented on frontend/src/components/Layout/Navbar.tsx
>  import Flex from '../common/Flex';
아이고 충돌 해결하면서 되돌아간 것 같아요! 수정하도록 하겠습니다!!

2023-10-04 10:58 UTC, GC-Park commented on frontend/src/components/Layout/Navbar.tsx
> -interface NavbarItemProps {
충돌 해결하다가 되돌아간 것 같아요!! 바로 수정하도록 하겠습니다~!!

2023-10-04 11:00 UTC, GC-Park commented on frontend/src/components/Layout/Navbar.tsx
> +    routePage(`/topics/${seeTogetherTopics?.length===0 ? -1 : seeTogetherTopics?.join(',')}`);
허헣.. 😉  충돌과정에서 되돌아온 코드로 삭제되었습니다~!!

2023-10-04 11:04 UTC, GC-Park commented on frontend/src/components/TopicCard/index.tsx
> +                onClickAtlas={onChangeIsInAtlas}
아 그럴 수도 있겠군요!!! onClick으로 통일하도록 하겠습니다 굿굿!

2023-10-04 11:06 UTC, GC-Park commented on frontend/src/components/TopicCard/index.tsx
> +  const [atlas, setAtlas] = useState<boolean>(isInAtlas);
너무 좋은 제안 바로 받아 반영하도록 하겠습니다! 👍

2023-10-04 11:09 UTC, GC-Park commented on frontend/src/components/TopicCard/index.tsx
> +                {atlas ? <SeeTogetherSVG /> : <SeeTogetherNotFilledSVG />}
와우 이 부분까지 생각하지 못하고 코드 작성했던 것 같은데 굿!

누군가가 추상화를 잘 해주었기에 예방할 수 있었던거죠 😉

2023-10-04 11:19 UTC, GC-Park commented on frontend/src/components/TopicInfo/index.tsx
> +
오 세인 말을 들어보니 아주 일리가 있습니다! showToast 적용이 더 알맞을 것 같습니다 굿 !!

2023-10-04 11:34 UTC, GC-Park commented on frontend/src/pages/SelectedTopic.tsx
> +    if (topicId === '-1') return;
아 이 부분 저도 직관적인 단어로 적용해보았는데 에러가 뜨더라구요! 아마 원인은 명세 'topics/:topicId'에서 topicId부분이 Number로 고정인 것 같아요! 

에러 발생 예시입니다!
-> get 요청 실패
<img width="700" alt="스크린샷 2023-10-04 오후 8 31 52" src="https://github.com/woowacourse-teams/2023-map-befine/assets/72205402/b34a267a-60d8-4c03-bc4e-d3ea4fc80e1c">

-> 아무것도 뜨지 않음
<img width="350" alt="스크린샷 2023-10-04 오후 8 32 07" src="https://github.com/woowacourse-teams/2023-map-befine/assets/72205402/577e93c4-5684-4351-a049-046fc3938e08">

2023-10-04 11:35 UTC, GC-Park commented on frontend/src/router.tsx
> -            <SeeTogetherTopics />
아이고 아깝다 아까버 ! 그러나 이제는 없애야 할 때 .! 삭제 갑니다~

2023-10-04 11:41 UTC, GC-Park commented on frontend/src/pages/Home.tsx
> +
세인! 이 부분은 저희 금요일에 만나서 한번 더 얘기보는게 어떨까요?! 제가 잘 이해를 못하기도 했고 실제로 만나 화면을 보면서 말하면 금방 이해할 수 있을 것 같아서요!! 일단 이 전까지 코멘트는 모두 반영하였습니다! 이 부분 만나서 화면으로 보고 바로 반영해봐요!!!

2023-10-06 02:24 UTC, semnil5202 approved these changes
확인했습니다.

2023-10-06 02:25 UTC, merged