[BE] Refactor/#540 지연로딩으로 조회하는 경우, soft delete을 반영할 수 없음
woowacourse-teams/2023-map-befine pull request #553
Opened 2023-10-05 08:21 UTC by yoondgu

## 작업 대상

Repository 메서드에 `IsDeletedFalse`를 붙여 조회 기능에 soft delete을 반영함에 따라  
지연 로딩으로 정보를 조회하는 경우, 삭제된 토픽/핀도 조회하게 되는 문제가 있었습니다.

이를 해결하기 위한 방법 중 엔티티에 `@Where`을 적용하는 것을 선택했습니다.  
stream, filter는 지연로딩인 모든 연관 관계의 getter에 대해 이를 적용해주어야 한다는 문제가 있기 때문입니다.  
빠른 적용이 필요한 상황에서도 오히려 시간이 더 오래 걸릴 수 있습니다.  
또, 그에 비해 `@Where` 적용 시, 수정이 필요한 대부분은 관리자 기능 및 테스트 코드인 데에 비해  
새로 엔티티가 추가될 때마다/연관관계가 변경될때마다 이러한 작업을 하기에는 유지보수성도 떨어진다고 판단했습니다. 

### 고려해야 할 연관관계 (테스트 작성)
- [x] topic.getPins
- [x] member.getCreatedPins
- [x] location.getPins
- [x] member.getCreatedTopics
- [x] location.getTopic
- [x] pin.getPinImages
- pin.getTopic (즉시로딩, topic이 삭제되었다면 pin도 삭제된 상황이므로 해당 X)
- atlas.getTopic (즉시로딩, soft delete 해당 X)
- bookmark.getTopic (즉시로딩, soft delete 해당 X)

### 작업 내용

## 📄 작업 내용

- [x] 지연로딩 대상인 엔티티에 Where 적용, 테스트 작성
    - [x] Where 적용으로 인해 깨지는 테스트 수정
- [x] 기존에 JPQL에 조건부를 붙인 조회 쿼리를 Where 적용으로 변경
    - [x] Where 적용으로 인해 깨지는 테스트 수정
### 추가 작업
**Pin을 삭제할 경우 Topic의 pinCount 컬럼을 업데이트하는 로직이 없는 것을 발견하여 이를 추가했습니다.** ([해당 커밋](https://github.com/woowacourse-teams/2023-map-befine/commit/9db5da3309728bc7dd9fe8d1b81951f21bb103fe))  
  - 그동안은 Pin을 삭제할 일이 없었기 때문에 놓쳤던 부분인 것 같아요.
  - 그런데 우리는 Pin을 삭제할때 Repository를 거쳐 쿼리를 실행하므로, Pin 삭제 로직과 Topic의 pinCount를 완전히 통합하기가 어려웠습니다.
  - 이 부분에 대해서는 TODO 주석을 다수 남겨두었는데, 같이 얘기해보면 좋을 것 같아요.
  

## 🙋🏻 주의 사항

일종의 버그 해결이기 때문에 Hotfix라고 생각하지만, 개발 서버에도 먼저 반영될 사안이라고 생각해 develop-BE로 PR 보냅니다.  
개발서버 배포 후 바로 운영서버 배포하면 될 것 같습니다.

## 스크린샷

## 📎 관련 이슈

 
closed #540

## 레퍼런스

2023-10-05 08:25 UTC, junpakPark approved these changes
수고하셨습니다 도이!
질문하나 남기긴했는데 merge 되도 무방하다고 생각하여 approve 남깁니다 👍👍

2023-10-05 08:25 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        entityManager.flush();
이 부분 repository에서 flush 해도 되지 않나용??

2023-10-05 12:48 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        entityManager.flush();
추가적인 주입이 필요없다는 면에서 굉장히 좋은 아이디어네요!

하지만 현재 코드는 `Permission`, `Atlas`, `Bookmark` 에 대한 `hard delete` 쿼리를 한꺼번에 날리는 `flush` 이기 때문에, `flush` 를 호출하는 의무를 어떠한 `Repository` 가 가져가야 하는지를 정하는 것도 굉장히 애매한 부분인 것 같기도 하네요.

다들 어떻게 생각하시나요?

2023-10-05 13:26 UTC, kpeel5839 requested changes
오우 도이!

where 절을 적용하면서 isDeletedFalse 가 떨어져버리니까 굉장히 메서드가 짧아졌군요!

고생하셨습니다!

낭낭하게 코멘트 남겼습니다~!

확인해주시고 대댓글을 달아주시기를 원하기 때문에 Request Changes 남기도록 하겠습니다 ^.^

확인하시면 바로 Approve 로 바꾸도록 할게요~!

2023-10-05 13:26 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        /// TODO: 2023/10/05 soft delete를 @Query로 구현하면서, pinCount 반영을 통합할 수 없음
```sql
update pin p, topic t
set p.is_deleted = true, t.pin_count = t.pin_count - 1
where p.id = "삭제하려는 pin id" AND t.id = p.topic_id;
```

금단의 영역인 것 같긴하지만, 방금 되는 것을 확인하긴 했습니다...

2023-10-05 13:26 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        /// TODO: 2023/10/05  pinImage는?
pin image 도 연계적으로 지워줘야 하겠군요....

2023-10-05 13:26 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
이건 쥬니 글에서 보았듯 @Query 어노테이션이 동반되지 않으면 짜피 clearAutomatically 가 동작하지 않으니까 빼신게 맞나요 ?

2023-10-05 13:26 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
>      }
```java
.orElseThrow(
    () -> new NoSuchElementException("findCreatorByAuthMember; member not found; id=" + memberId)
);
```

도 괜찮아보입니다 ^.^

2023-10-05 15:20 UTC, cpot5620 requested changes
도이 고생 많았어요 !!!

TODO 부분에 의견도 달아두었고, 코드 관련해서 제안드리는 부분이 있어서 RC 하겠습니당.

2023-10-05 15:20 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        entityManager.flush();
사실 저도 `entityManager`가 존재한다는게 거슬리긴 해요.

준팍이 말씀해주신 

> entityManager를 주입받을 필요없이 repository에서 flush하는 건 어떨까요??

이 부분은 별도의 설정하지 않아도 된다는 의미일까요 ?

아마, 테스트 코드 구성을 잘못해서 발생한 문제를 해결하기 위해 위와같은 구조를 갖게 된 걸로 알고있어요. (내가 짬 ㅋ)
테스트 코드에서 `//given`에서 데이터를 세팅해주는 작업과 같은 트랜잭션으로 묶이기 때문에 `flush`를 강제로 호출해주지 않으면 수정 관련 쿼리가 쓰기 지연 저장소에 저장되었다가, 트랜잭션이 커밋되기 직전에 데이터베이스로 쿼리를 날라가게 되요.
어떻게 해결 할 수 있다는 의미인지 궁금합니다 !

2023-10-05 15:20 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        /// TODO: 2023/10/05 soft delete를 @Query로 구현하면서, pinCount 반영을 통합할 수 없음
지금 방법대로 하면 안 되는건가요 ?
상관 없어보이는데..

2023-10-05 15:20 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/AuthService.java
> +    // TODO 테스트가 필요하긴 한데, MemberQueryService와 너무 중복되는 내용이다. 엔티티 테스트로 중복을 없앨 수 있으면 좋겠다.
언젠가 `MemberQueryService`의 스펙이 바뀔수도 혹은 `AuthService`의 스펙이 바뀔 수도 있을 것 같은데요.
그런 의미에서, 중복되는 테스트라고 할지라도 수행하는 것이 좋지 않을까요 ?

2023-10-05 15:20 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
코멘트 위치가 잘못된듯요

2023-10-05 15:20 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
> -    @Modifying(clearAutomatically = true)
이 부분 JPQL로 해결해야하는데... 도이꺼 PR 머지되면 브랜치 따서 해결할게요. 

잊지말자 !!!!!!!!!!!!

2023-10-05 15:20 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
>      }
Pin 자체가 hard-delete 된게 아니다 보니, pinCount 값은 그대로 두어도 무방할 것 같은데요 ?

pin이 삭제될 때에만 topic의 pinCount 값을 신경쓰고요 !

2023-10-05 15:20 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
> +    public void decrementPinCount() {
명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사명사

2023-10-05 15:20 UTC, cpot5620 commented on backend/src/test/java/com/mapbefine/mapbefine/location/application/LocationQueryServiceTest.java
>          );
아 ㅋㅋ 나도 없네 
이 아래에 있는 코드 리뷰 안함 ㅂ2

2023-10-05 15:24 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
또잉또잉 클릭 잘못했어연 바로 아래줄일듯 허허허

2023-10-05 15:26 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        /// TODO: 2023/10/05 soft delete를 @Query로 구현하면서, pinCount 반영을 통합할 수 없음
사실 soft delete 의 대가인 것 같아요 ㅋㅋㅋ delete 해줘야 하는 부분에서 연관된 다른 부분들도 신경써야 하는거요

2023-10-05 15:27 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
> -    @Modifying(clearAutomatically = true)
여기다가 제가 단 거 였는데 ㅋㅋㅋㅋ

2023-10-05 15:28 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
>      }
topic 살면 pin 도 다 다시 살아나니까?

2023-10-05 15:55 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        /// TODO: 2023/10/05 soft delete를 @Query로 구현하면서, pinCount 반영을 통합할 수 없음
근데 `@PrePost` 썼던 것처럼 `@PreRemove`로 할 수 있을지도..?? 해보고 아니면 냅둘게요 ㅎㅎ

2023-10-05 15:58 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/AuthService.java
> +    // TODO 테스트가 필요하긴 한데, MemberQueryService와 너무 중복되는 내용이다. 엔티티 테스트로 중복을 없앨 수 있으면 좋겠다.
맞아요 근데 AuthService 의존성 문제때문에 귀찮아서... + 중복 코드로 인해 발생하는 테스트 중복이 많은 것 같아서요.  
더 작은 단위에서 테스트하면 좋을텐데 엔티티 테스트 해보려니 TestEntityManager 잔뜩 써야 할 것 같아서 일단 안했습니다.  
테스트 추가할게용  (왜 여태 테스트 없었죠? 😄)

2023-10-05 15:59 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
>      }
반영할게용

2023-10-05 15:59 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        entityManager.flush();
@yoondgu 
<img width="1159" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/112045553/c6fea1fa-9b07-4a75-b434-b5d8c6b9c1b9">
저는 이 메서드를 의미한거긴 해용!!
이 메서드를 사용하면 entityManager의 flush를 사용한것과 동일하게 작동합니다!

2023-10-05 16:00 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/location/application/LocationQueryServiceTest.java
> +    }
역시 SQL 천재시네요

2023-10-05 16:02 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
>      }
저도 똑같이 생각해서 적용 안했는데 주석이 남아있었네요! 지울게욥

2023-10-05 16:03 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        entityManager.flush();
GPT 센세의 첨언...

<img width="737" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/112045553/462c832c-bd16-4e81-86cb-6d45c39071cd">

2023-10-05 16:03 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
> +    public void decrementTopicPinCount() {
엥 맞아요 왜 저렇게 썼을까요 ? 영어 천재시네요 . 고칠게용

2023-10-05 16:03 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
> +    public void decrementPinCount() {
ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ

2023-10-05 16:04 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
> +        assertThat(pinImageRepository.findById(pinImage.getId())).isEmpty();
바로 위 테스트가 뭘까요 ? existById와의 차이라면 pinImage는 List라서 이렇게 했습니다 !

2023-10-05 16:05 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
> -    @Modifying(clearAutomatically = true)
Service에서 EntityManager 불러오는 대신 JPQL로 바꾸고 @Modifying 다시 적용한다는거죵 ?  
아주 좋습니다아

2023-10-05 16:08 UTC, junpakPark commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        entityManager.flush();
세 레포지터리 중 어떤 것을 써도 동일하게 동작할텐데
매튜 말대로 뭐 써야될지 조금 고민되긴 하겠네요 ㅋㅋ

2023-10-05 16:09 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        entityManager.flush();
아 아까 트러블슈팅하다가 clear까지 해보려고 entityManager를 받아왔다가 이 생각을 못했네요 !!  
근데 대신 delete 메서드에 JPQL 직접 쓰고 Modifying 으로 해결하는 건 어떠세요?  
[쥬니가 쓴 기술 블로그 참고](https://github.com/map-befine-official/map-befine-official.github.io/pull/5/files?short_path=4d63932#diff-4d639323e1944d12b4d624db0ff10b9740b39552a3d75701248343da0a986af7)

2023-10-05 16:12 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/auth/application/AuthService.java
> +    // TODO 테스트가 필요하긴 한데, MemberQueryService와 너무 중복되는 내용이다. 엔티티 테스트로 중복을 없앨 수 있으면 좋겠다.
허허허허

2023-10-05 16:13 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/location/application/LocationQueryServiceTest.java
> +    }
반영안할거잖아요!

2023-10-05 16:13 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
> +        assertThat(pinImageRepository.findById(pinImage.getId())).isEmpty();
글 헛 군 요!

2023-10-05 16:14 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
> +    public void decrementTopicPinCount() {
천재아닌데요!

2023-10-05 18:00 UTC, yoondgu commented
말씀해주신 사항들 반영했습니다 !  
delete flush문제는 일단 repository.flush를 호출하도록 변경했고,  
`@Modifying`으로 일괄 적용은 쥬니가 추가 PR에서 하신다고 하셔서 따로 작업하지 않았습니다 ㅎㅎ  
AuthServiceTest 작성하면서 차단,탈퇴 사용자 예외처리도 추가했습니다.

2023-10-06 01:57 UTC, kpeel5839 approved these changes
도이 넘흐넘흐 고생하셨어요!

Approve 드립니다!

2023-10-06 01:57 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        /// TODO: 2023/10/05 soft delete를 @Query로 구현하면서, pinCount 반영을 통합할 수 없음
좋아연

2023-10-06 01:57 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        pinRepository.deleteAllByTopicId(topicId);
하나의 repository 가 flush 의무를 갖는 것이 애매하기 때문에 모든 repository 가 flush 를 호출할 수 있도록 하셨군요! 좋습니다.

그리고, 이 부분은 추후에 개선할 수 있으면 개선하도록 해보죠! (명시적으로 flush 호출 안해보도록)

2023-10-06 01:57 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/auth/application/AuthServiceTest.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
야무지게 쓰셨네요

2023-10-06 01:57 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/permission/presentation/PermissionController.java
> +    @Deprecated(since = "2023.10.06")
👍

2023-10-06 05:44 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
> +        pinRepository.deleteAllByTopicId(topicId);
앗 저 각각 해야 하는줄알았어요...ㅎㅎ 근데 매튜 말대로 곧 사라질 내용인걸로!

2023-10-06 08:49 UTC, cpot5620 approved these changes
+1

2023-10-06 08:49 UTC, merged