[BE] Refactor/#547 로그인 회원 프로필 조회 API 명세 변경
woowacourse-teams/2023-map-befine pull request #561
Opened 2023-10-06 15:05 UTC by yoondgu

## 작업 대상

#547 참조

## 📄 작업 내용

#547 참조
- MemberController
- MemberQueryService findById -> findProfile
- 관련 테스트
- RestDocs

## 🙋🏻 주의 사항

API 명세의 변경으로, 프론트 측 해당 코드 변경 PR과 시점을 맞추어 배포할 필요가 있습니다.  

## 스크린샷

## 📎 관련 이슈

 
closed #547

## 레퍼런스

2023-10-06 16:55 UTC, kpeel5839 requested changes
간단한 질문 및 제안 남겼습니다!

답변 주시면 바로 Approve 드리도록 하겠습니다!

항상 고생많으십니다 또이또이또이~~ 내일 생일 재미있게 즐기십셔~

2023-10-06 16:55 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +    public MemberDetailResponse findProfile(AuthMember authMember) {
해당 메서드는 무조건 본인의 profile 을 찾아오니까, `findMyProfile` 도 괜찮을 것 같아요!

2023-10-06 16:55 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +    public ResponseEntity<MemberDetailResponse> findMyProfile(AuthMember authMember) {
앗 Controller 의 메서드 명이 findMyProfile 이라서 Service Method 명은 다르게 하신건가??

2023-10-06 16:55 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
> +                .isInstanceOf(MemberNotFoundException.class);
현재 이런 경우가 발생할 수 있을까요 ??

Interceptor 를 거치면서 Token 에 담겨있는 memberId 가 유효한지 확인하니까요!

2023-10-07 05:12 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +    public ResponseEntity<MemberDetailResponse> findMyProfile(AuthMember authMember) {
저는 컨트롤러 메서드는 API 의미에 가깝게 하는 걸 선호해서 그렇게 하고, 서비스메서드는 다르게 했는데
오히려 좀 헷갈렸을 것 같네요!  
서비스 메서드명은 개발 로직에 더 가깝게 findMemberDetail로 하겠습니당

2023-10-07 05:13 UTC, yoondgu commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +    public MemberDetailResponse findProfile(AuthMember authMember) {
아래 코멘트 남겠습니다!

2023-10-07 05:15 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
> +                .isInstanceOf(MemberNotFoundException.class);
맞아요 정상적인 상황에서는 발생할 일이 없는데, 서비스 단에서도 검증을 해주자는 이전의 논의가 생각나서 검증 로직을 유지해봤어요.  
만에 하나 토큰의 시크릿 키를 탈취당해 외부에서 토큰을 만드는 경우를 생각해봤습니다!

2023-10-07 05:15 UTC, kpeel5839 commented on backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
> +    public ResponseEntity<MemberDetailResponse> findMyProfile(AuthMember authMember) {
좋습니당!

2023-10-07 05:15 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
> +                .isInstanceOf(MemberNotFoundException.class);
도이 (유도영) 님이 입력중입니다.

2023-10-07 05:16 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
> +                .isInstanceOf(MemberNotFoundException.class);
ㅋㅋㅋㅋㅋㅋ입력 완료상태입니다

2023-10-07 05:22 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
> +                .isInstanceOf(MemberNotFoundException.class);
좋습니다! 이전에 쥬니가 adminService 에서 해줬던 고민과 동일하군요!

저는 OK 입니다~!!

근데, jwt 시크릿 키를 탈취당한 경우를 생각해보셨다고 하셨는데, 조금만 더 자세히 설명 해주실 수 있을까요?

시크릿 키를 탈취 당해서 외부에서 토큰을 만든다고 하더라도 Controller 단에서 먼저 검증을 진행하고, 만일 유효한 MemberId  로 토큰을 만들어 Controller 단이 뚫린다면 현재 Service 도 뚫리지 않나 싶어서요!

2023-10-07 05:23 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
> +                .isInstanceOf(MemberNotFoundException.class);
제 이해력이 딸려서 잘 못 이해한 것 같기도 합니다 허허허

2023-10-07 05:31 UTC, yoondgu commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
> +                .isInstanceOf(MemberNotFoundException.class);
> 만일 유효한 MemberId 로 토큰을 만들어 Controller 단이 뚫린다면 현재 Service 도 뚫리지 않나 싶어서요!

맞아요! 잘 말씀해주신 것 같아요. 위 검증 로직은 유효하지 않은 232392024 이런 아이디로 보내는 경우만 막아줘요.  
근데 말씀해주신 경우를 막으려면 AuthMember가 정말 본인인지 아닌지 확인하는 수단이 하나 더 필요해지기 때문에  
쉽지 않겠네용...
생각해보니 위 검증 로직은 차선책이고, 시크릿 키 탈취에 대한 대책은 별도의 문제인 것 같네요! (그리고 지금은 시크릿 키가 탈취될 가능성이 거의 적으니..)

2023-10-07 05:34 UTC, kpeel5839 commented on backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
> +                .isInstanceOf(MemberNotFoundException.class);
시크릿 키는 탈취당하면 admin 큰일 나버렷...

쉬는 날에 긴 답변 정말 감사합니다 도이!

푹 쉬십쇼!

2023-10-07 05:34 UTC, kpeel5839 approved these changes
도이 너무 고생하셨어요~~~!!!

2023-10-07 10:07 UTC, junpakPark approved these changes
수고하셨습니다 👍👍👍

2023-10-08 05:36 UTC, cpot5620 approved these changes
고생하셨습미다 도이 !

2023-10-08 05:36 UTC, cpot5620 commented on backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
> +        return MemberDetailResponse.from(member);
👍

2023-10-09 07:49 UTC, merged