feat/#564 poi 적용
woowacourse-teams/2023-map-befine pull request #566
Opened 2023-10-09 16:35 UTC by afds4567

## 작업 대상

- 핀을 추가하는 경우 식당명과 같은 키워드로도 위치 검색 가능하도록 구현
## 📄 작업 내용

- tmap poi 적용으로 장소명으로도 주소 검색(자동완성) 가능
- 연관 검색어 요청 debounce 적용
- tmap zoom level관련 수정
## 🙋🏻 주의 사항

- tmap api를 일단 ga처럼 숨기긴 해뒀는데 잘 될지 모르겠네여...
- new-pin 페이지의 이전 input 코드를 주석 처리만 해둬서 확인해보고 전부 삭제해도 되면 반영 예정입니다
- 실행 안될경우 대비해 스크린샷 첨부합니다
## 스크린샷

![image](https://github.com/woowacourse-teams/2023-map-befine/assets/33995840/6cdedbe7-f25d-4ff3-8f11-e4e993400d16)
![image](https://github.com/woowacourse-teams/2023-map-befine/assets/33995840/2e07f95d-40aa-46d0-878a-278440f07972)

## 📎 관련 이슈

#564 
 
closed #564 
## 레퍼런스

2023-10-09 17:02 UTC, semnil5202 commented
오호 미리보기만 봐도 야무지군요

2023-10-10 05:05 UTC, GC-Park requested changes
궁금한 것들 코멘트로 남겼습니다~ 천천히 답 주십시오~!

2023-10-10 05:05 UTC, GC-Park commented on frontend/src/components/common/Input/Autocomplete.tsx
> +const Autocomplete = ({
자동완성 멋졍 굿~

2023-10-10 05:05 UTC, GC-Park commented on frontend/src/components/common/Input/Autocomplete.tsx
> +
오 여기서는 확실히 memo가 있으면 좋겠군욧 !!

2023-10-11 04:01 UTC, afds4567 commented on frontend/src/types/Poi.ts
> +
타입 안에서 쓰이는 거라 굳이 필요할까 생각되는데 세인이랑 얘기해보죠

2023-10-11 05:04 UTC, semnil5202 reviewed
전반적으로 아주아주 나이스하군요~~ 👍👍 완성도가 정말 야무집니다. UI도 깔끔하네요.

네이밍과 스타일링 관련해서 몇 가지 코멘트 남겼습니다. (패트릭 질문에 대한 답변도 포함)

확인해보시고 알려주세요~~

2023-10-11 05:04 UTC, semnil5202 commented on frontend/src/hooks/useClickedCoordinate.ts
> +      map.setZoom(currentZoom);
개인적으로 사용자가 suggestionList 에서 주소를 클릭했을 때 줌 레벨이 최대가 되었으면 좋겠습니다. suggestionList의 상세설명으로도 사용자가 선택한 주소가 맞는지 확인할 수 있지만 지도를 통해서도 확인할 수 있다고 생각해서요.

다만 currentZoom이 제각각일테니 (어느 페이지에서 왔냐에 따라서) `map.setZoom(currentZoom <= 17 && 17)` 이런 분기 처리 로직이 필요할 수도 있을 것 같습니다.

2023-10-11 11:44 UTC, afds4567 commented on frontend/src/pages/NewPin.tsx
> +            defaultValue={clickedCoordinate.address}
Autocomplete을  핀 목록과 같은 다른곳에서 사용할 수 있도록 최대한 재사용가능하도록 만들어보려고 defaultValue라고 했는데 어떤가요

2023-10-11 11:45 UTC, afds4567 commented on frontend/src/pages/NewPin.tsx
> +  // const onClickAddressInput = (
ok

2023-10-11 11:51 UTC, afds4567 commented on frontend/src/components/common/Input/Autocomplete.tsx
> +    );
여기서 ref는 값을 저장하는 용도로 사용했는데 state 변화에 끄덕없는 timer를 만들려고 ref를 사용했습니다

2023-10-11 11:52 UTC, afds4567 commented on frontend/src/components/common/Input/Autocomplete.tsx
> +              }}
음...사라진다는게 어떤 의미인지 상황을 조금 더 알려주시면 바로 설명해보겠습니다

2023-10-11 11:55 UTC, afds4567 commented on .github/workflows/fe-merge-dev.yml
> +          cache: "npm"
또 이러는데ㅋㅋㅋ 저는 더블인데

2023-10-11 12:00 UTC, afds4567 commented on frontend/src/components/common/Input/Autocomplete.tsx
> +  const [inputValue, setInputValue] = useState<string | undefined>(
저때는 아직 검색어를 정하지 않았다고 생각되서 undefined라고 뒀던거 같은데 뭔가 null로 명시하는것보다 더 좋다고 볼만한 점이 그닥 없는것 같네여. 수정했습니다~

2023-10-11 12:16 UTC, afds4567 commented on frontend/src/components/common/Input/Autocomplete.tsx
> +      console.error(error);
<img width="381" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/33995840/fdd289af-5219-4ba9-a4be-8ec1da275ba5">
이 부분분 에러인거 같은데 제가 확인바로는 input이 비어지는 순간 저 에러가 발생하는데 무시해도 되는 에러라고 보는데 어떻게 생각하시나요?(사실  정확히 뭐가 문젠지 잘 모름)

2023-10-11 12:17 UTC, afds4567 commented on frontend/src/components/common/Input/Autocomplete.tsx
> +      500,
자동완성을 input에 onchange에 걸다보니 api 요청이 너무 많아져서 api 횟수 제한 때문에 debounce를 걸었는데 느려보인다면 400 좋습니다

2023-10-11 12:29 UTC, afds4567 commented on frontend/src/components/common/Input/Autocomplete.tsx
> +  border: 1px solid #ccc;
border-top: none;

2023-10-11 12:31 UTC, afds4567 commented on frontend/src/components/common/Input/Autocomplete.tsx
> +`;
Text를 깜빡했네여, 적용했습니다

2023-10-11 12:37 UTC, afds4567 commented on frontend/src/hooks/useClickedCoordinate.ts
> +      map.setZoom(currentZoom);
우선 세인이 제안해준 방식대로 적용은 했는데 실제 사용해보면서 zoom 레벨에 대해서(어느 페이지에서 왔는지라던지) 더 고민해보죠

2023-10-11 12:39 UTC, afds4567 commented
커멘트남겨주신 부분 우선 반영했습니다
자동완성 리스트에 설명이 필요한지와 같은 ui 부분은 같이 얘기해보고 추가로 반영하고 머지하겠습니다~

2023-10-12 04:41 UTC, GC-Park approved these changes

2023-10-12 04:41 UTC, GC-Park commented on frontend/src/components/common/Input/Autocomplete.tsx
> +    );
아이크가 설명해주셔서 이해해버렸습니다 굿굿

2023-10-12 04:41 UTC, GC-Park commented on frontend/src/components/common/Input/Autocomplete.tsx
> +              }}
제가 오해했네요 하하하핳  설명으로 다 들었습니다 굿 ~~

2023-10-12 05:24 UTC, semnil5202 commented on frontend/src/pages/NewPin.tsx
> +            defaultValue={clickedCoordinate.address}
아하 그런 의미로 두었군요. 좋습니다 👍

2023-10-12 05:29 UTC, semnil5202 commented on frontend/src/components/common/Input/Autocomplete.tsx
> +  border: 1px solid #ccc;
![image](https://github.com/woowacourse-teams/2023-map-befine/assets/89172499/c8b4ea4d-3a34-4565-b78e-d8c94029f94c)

요만큼 남아요 ㅋㅋㅋㅋㅋ bottom을 없애야할듯?

2023-10-12 05:32 UTC, semnil5202 commented on frontend/src/components/common/Input/Autocomplete.tsx
> +  border: 1px solid #ccc;
아 bottom 하고 top 둘다 없애야하네요 아래 없앤건데 어떤가요?

<img width="356" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/89172499/337c4a2e-a136-49ab-9be1-6f7a26ba2d8d">

<img width="344" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/89172499/cf7dfefc-a833-489f-b04d-5f7c1fa6b3ac">

<img width="349" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/89172499/97b8e004-48b3-432c-a803-3a90c622753d">

2023-10-12 05:32 UTC, semnil5202 commented on .github/workflows/fe-merge-dev.yml
> +          cache: "npm"
ㅋㅋㅋㅋㅋ 우선은 두죠..

2023-10-12 05:44 UTC, semnil5202 commented on frontend/src/components/common/Input/Autocomplete.tsx
> +      console.error(error);
아하 에러를 반환하는 경우가 두 가지가 있네요.

* 검색어에 해당하는 장소가 없을 때 (예시 : ㅁㄴㅇㄹㅈㄷㄹ) -> network 에러는 안나고 콘솔에 에러(정확히는 예외상황)
* 검색어를 빈 값으로 보낼 때 -> network 에러 발생

첫 번째로 위 두 상황은 모두 검색어에 대한 검색 결과가 없을 때 발생한다는 공통점이 있습니다. 그래서 catch 문에 말씀하신 대로 `setSuggestions(['검색결과가 없습니다']);` 와 같은 구문이 필요해보입니다. 👍

두 번째로 검색어를 빈문자열로 보내면 network 에러가 발생하고 이는 결과적으로 불필요한 행동이므로 아래 처럼 e.target.value가 빈 값이면 api 요청 자체를 하지 않는 로직을 추가해보면 어떨가 싶습니다.  (간단하게 짰습니다.)

```js
// 54번째 줄부터

debounceTimeoutRef.current = setTimeout(
  () => e.target.value !== '' && fetchData(e.target.value),
  500,
);
```
이렇게 하면 network 에러 발생 안 하고 불필요한 api 호출도 하지 않네여~

![Oct-12-2023 14-42-06](https://github.com/woowacourse-teams/2023-map-befine/assets/89172499/96aaf419-705e-46c2-8cac-4b4944dbde8c)

2023-10-12 06:57 UTC, semnil5202 approved these changes
굳 잡 고생했습니다 👍

2023-10-12 06:57 UTC, merged