[FE] Feature/#560 메인 페이지에 swiper 및 배너 적용
woowacourse-teams/2023-map-befine pull request #569
Opened 2023-10-10 11:58 UTC by semnil5202

## 작업 대상

* Home 페이지 Banner 와 TopicCard

## 📄 작업 내용

- [x] Swiper 컴포넌트를 구현
- [x] TopicCard UI를 변경
- [x] 배너 생성
- [x] Swiper 컴포넌트를 모아보기, 배너 등에 적용

## 🙋🏻 주의 사항

* swiper 사용 방법은 [여기서](https://www.npmjs.com/package/seeen-tab-layout) 확인해볼 수 있으나 버전 업데이트가 한 단계 밀려있습니다. (elementMediaQueries 관련) 추후 오프라인으로 얼라인하겠습니다.
* topicCard Image 최소 사이즈를 지정할 필요가 있어보입니다. (image compression 관련) 너무 작은 이미지는 반응형 상황에서 조작이 어렵습니다.
* 최소한의 스와이프만 가능합니다. (솔로스타 급 기대 금지)
* 자잘한 반응형 버그가 있을 수 있습니다. 알려주시면 감사하겠습니다.. 이는 차츰 개선해보겠습니다.
* ❗️layout 컴포넌트에서 padding이 제거 되었습니다.❗️ 반응형 상황에서 topicCard 가 가려지는 오류를 도저히 해결할 수가 없어서 제거하였고, 현재까지 UI가 깨지는 현상은 없었습니다. 이 부분도 추후 보완하겠습니다.

## 스크린샷
![Oct-10-2023 20-46-21](https://github.com/woowacourse-teams/2023-map-befine/assets/89172499/db2e8c14-5441-4955-9dcb-36d660ca26b9)
![Oct-10-2023 20-46-05](https://github.com/woowacourse-teams/2023-map-befine/assets/89172499/4598c39a-10fc-48d7-af03-6425bcc10550)

## 📎 관련 이슈

#560 
 

## 레퍼런스

2023-10-12 01:37 UTC, afds4567 reviewed
👍 👍 
구현부가 복잡해서 리뷰하기 싫었는데 사용하긴 아주 좋아보야요

2023-10-12 01:37 UTC, afds4567 commented on frontend/src/components/common/Swiper/hooks/useMatchMedia.ts
> +      const matchMedia = window.matchMedia(mediaQuery);
여기랑 L47에서각 미디어 쿼리에 대해 matchMedia 인스턴스를 생성하고 change 이벤트 리스너를 cleanup에서 제거하는데 뭔가 더 좋은 방법이 있을꺼같아서 고민해봤는데요...
한 번만 matchMedia 인스턴스를 생성하고 이걸 listener?(라이브러리같은데 많더라고요?)배열에 넣어두고 사용하면 어떨까?라고 코드를 만들려하는데 시간부족상 여기까지^^

2023-10-12 01:37 UTC, afds4567 commented on frontend/src/components/common/Swiper/hooks/useSwipeable.ts
> +    if (pos < childrenListLength - 1 && diff < -10) {
웹에서 클릭이랑 다르게 스와이프는 diff변경량이 특정값 이상인걸 통해서 스와이프 했는지 안했는지 판단하는거 같은데 맞나요?

2023-10-12 01:37 UTC, afds4567 commented on frontend/src/components/common/Swiper/hooks/useSwipeable.ts
> +    if (pos < childrenListLength - 1 && diff < -10) {
코멘트 순서가 좀 섞였는데 handleTouchMove에서 diff변화량 감지해서 acceleratePos에서 pos값을 바꿔주면서 스와이프가 넘어가는거 같네여

2023-10-12 01:37 UTC, afds4567 commented on frontend/src/components/common/Swiper/hooks/useAutoplay.ts
> +  }, [childrenListLength, pos, setPos, $autoplayTime, isPlaying]);
굳이 리뷰 달자면 setPos까지 굳이 들어가야하나요?

2023-10-12 01:37 UTC, afds4567 commented on frontend/src/components/common/Swiper/hooks/useAutoplay.ts
> +      intervalId.current = setInterval(
클로저를 요즘 좀 봐서 궁금한점 남기자면
setInterval에서 pos가 선언된 시점에서의 pos값을 기억하는데 콜백 내부 pos가 리액트 생명주기 관련해서 과연 최신의 상태인가? 헷갈리는데요
그냥 intervalid처럼 pos도 useeffect 위에 useRef로 만들어서 사용하면 어떤가요?

2023-10-12 01:37 UTC, afds4567 commented on frontend/src/components/common/Swiper/index.tsx
> +function Swiper({
hook들이 잘 만들어져서 swiper자체는 어려운 로직이 없어서 좋네요 😄 
Css부분은 주석이 아주 큰 도움이었습니다 👍

2023-10-12 03:05 UTC, GC-Park requested changes
세인의 강의가 필요한 pr입니다 허헣 시간 되실 때 해주시면 넘나 감사하겠습네다 ~

2023-10-12 03:05 UTC, GC-Park commented on frontend/src/components/common/Swiper/hooks/useSwipeable.ts
강의 please...~

2023-10-12 09:06 UTC, semnil5202 commented on frontend/src/components/common/Swiper/hooks/useAutoplay.ts
> +      intervalId.current = setInterval(
pos는 useState 로 선언된 상태값 입니다!

2023-10-12 09:06 UTC, semnil5202 commented on frontend/src/components/common/Swiper/hooks/useAutoplay.ts
> +      if (intervalId.current) clearInterval(intervalId.current);
완료!

2023-10-12 09:06 UTC, semnil5202 commented on frontend/src/components/common/Swiper/hooks/useAutoplay.ts
> +  }, [childrenListLength, pos, setPos, $autoplayTime, isPlaying]);
저도 굳이 들어가야하나 했는데 lint가 넣어야 한다고 하더라구요 ㅋㅋㅋㅋㅋ 처음에 저도 setPos는 setStateAction 타입인데 변경될 경우도 없어서 필요없을텐데 했었습니다.

lint에 잡히는 이유는 아마도 props로 받아온 값이라 그런것 같습니다.

2023-10-12 09:06 UTC, semnil5202 commented on frontend/src/components/common/Swiper/hooks/useMatchMedia.ts
> +      const matchMedia = window.matchMedia(mediaQuery);
오호 저는 media query 분기점마다 이벤트리스너를 달아줘야한다고 생각해서 배열 순회는 어쩔 수 없는 부분인줄 알았는데 하나의 인스턴스로 재사용할 수 있다면 훨씬 좋겠군요.

아이크의 강의를 기다립니다~~~

2023-10-12 09:06 UTC, semnil5202 commented on frontend/src/components/common/Text/mediaText.ts
> +const MediaText = styled(Text)`
TopicCard 입니다~~

2023-10-12 09:06 UTC, semnil5202 commented on frontend/src/pages/Bookmark.tsx
> +  @media (max-width: 1180px) {
topicCard UI가 변경되면서 더 이상 필요가 없어졌습니다. 1140px로 반응형 시작 값이 변경된 것도 이 이유입니다.

파일 자체는 추후 모바일 반응형 리팩토링 작업에서 진행해보겠습니다. 혹시 모를 오류를 대비하기위해..

2023-10-13 01:14 UTC, GC-Park commented on frontend/src/components/TopicCard/index.tsx
>  `;
세인 요거 값이 달랐는데 4%로 통일이 되나욧 ?!!

2023-10-13 01:14 UTC, semnil5202 commented on frontend/src/components/TopicCard/index.tsx
>  `;
네! %이니 부모요소에 영향을 받아서 알아서 정렬

2023-10-13 01:24 UTC, GC-Park commented on frontend/src/components/TopicCardList/index.tsx
> +        ]}
결국 그리드 ~~ 굿 ~~ 좋아엿

2023-10-13 01:24 UTC, GC-Park commented on frontend/src/components/common/Grid/index.ts
> +`;
grid-template-columns가 중복되는 것 맞나용 ??! 일부러 중복시켜서 $mediaQueries가 있으면 밑에서 선언된 grid-template-columns 적용되도록 ?!

2023-10-13 01:41 UTC, afds4567 approved these changes
useMediaQuery부분 코멘트 남긴대로 수정해볼려했는데 에러나서 일단 어프로브하고 제 로컬에서 잘 되면 같이 얘기해보죠

2023-10-13 01:42 UTC, semnil5202 commented on frontend/src/components/common/Grid/index.ts
> +`;
예압~~ media Query 여러개라고 생각하시면 돼영~

2023-10-13 03:34 UTC, GC-Park approved these changes

2023-10-13 03:34 UTC, merged