[FE] Feat/#597 댓글 기능 구현
woowacourse-teams/2023-map-befine pull request #598
Opened 2023-10-17 12:05 UTC by afds4567

## 작업 대상

- 댓글 및 대댓글 기능을 구현한다.
- 수정,삭제 기능을 구현한다.
## 📄 작업 내용

- pinDetail페이지에서 댓글 추가, 수정, 삭제 기능 구현했습니다
## 🙋🏻 주의 사항

- UI관련 개선사항은 BE 머지 되고 빠르게 할 예정입니다 
## 스크린샷

## 📎 관련 이슈

#597 
 
closed #597 
## 레퍼런스

2023-10-17 18:51 UTC, kpeel5839 commented
테스트 통과 안하는데요!

2023-10-18 07:00 UTC, GC-Park requested changes
아이크 댓글 기능 빨리 만들어주셔서 넘나 감사합니다~ 심지어 아주 잘 만들어 주셨군요 믓져믓져

간단한 것들을 위주로 코멘트 드렸습니다~!

2023-10-18 07:05 UTC, afds4567 commented on frontend/src/components/common/Input/SingleComment.tsx
> +  );
아직 명세가 확정이 안되서 임시로 해뒀는데 반영할께여~

2023-10-18 07:05 UTC, afds4567 commented on frontend/src/components/common/Input/SingleComment.tsx
> +                답글남기기
ㅇㅋ

2023-10-18 07:05 UTC, afds4567 commented on frontend/src/components/common/Input/SingleComment.tsx
> +          parentPinCommentId: comment.id,
넵

2023-10-18 10:24 UTC, kpeel5839 commented on frontend/src/components/common/Input/SingleComment.tsx
> +                답글남기기
ㅋㅋㅋㅋ ㅇㅋ

2023-10-19 02:02 UTC, semnil5202 approved these changes
추후 확인하겠습니다.

2023-10-19 02:04 UTC, afds4567 commented
패트릭 리뷰 반영했습니다~

2023-10-19 02:04 UTC, GC-Park approved these changes
굿~ 반영 확인 했습니다~

2023-10-19 02:06 UTC, merged